### ISSUE TITLE
React + Typescript doesn't work with extended Dexie class

### ISSUE THREAD

**Issue by jkavalec** [dexie/Dexie.js#1023]
I am unable to make Dexie work with Typescript and CRA TS React app.

I have basic db from examples:

```
class FriendDatabase extends Dexie {
  // ts ignore is required to silence CRA settings, may this interfere with Dexie?
  // @ts-ignore
  friends: Dexie.Table<IFriend,number>;
  constructor() {
    super("FriendsDatabase");
    this.version(1).stores({
      friends: "++id,name,age"
    });
  }
}
var db = new FriendDatabase();
```

I am able to access database table like this
`db.table("friends").each(function (obj) {....`

However when I try to access the database with friends property like this:
`db.friends.add(...)`
I get error saying that friends is undefined, when I print content of DB inside console friends field is indeed undefined.

I am using latest 3.0.0-rc.7 version, same issues with 2.x version.
Any solution to this problem?

**Comment by mierak** [comment]
You are missing assignment to friends class property in your constructor.

Put this at the end in your constructor.
`this.friends = this.table("friends");`

```javascript
class FriendDatabase extends Dexie {
  // ts ignore is required to silence CRA settings, may this interfere with Dexie?
  // @ts-ignore
  friends: Dexie.Table<IFriend,number>;
  constructor() {
    super("FriendsDatabase");
    this.version(1).stores({
      friends: "++id,name,age"
    });
    this.friends = this.table("friends");
  }
}
var db = new FriendDatabase();
```

**Comment by jkavalec** [comment]
This helped me to solve the issue, thank you.

Still, in the Typescript Dexie samples, I didn't see direct assignment of table, yet the sample was still working properly did I overlook anything? Mostly curious as my issue is pretty much solved.

**Comment by mierak** [comment]
It is mentioned in the typescript part of [documentation](https://dexie.org/docs/Typescript).

**Comment by jkavalec** [comment]
I missed that Babel compilation needs it. Thanks again!

**Comment by dfahlander** [comment]
The suggested solution in this issue is not valid anymore, since: 

 1. Dexie 3 and 4 has had explicit support around this case for years. 
 2. Typescript has evolved since, and will be confused by the assignment, extending the table type to `Table<IFriend> | Table<any>` which might give other typing errors.

Instead, follow the advice on https://dexie.org/docs/Typescript
