### ISSUE TITLE
Changes applied during applyRemoteChanges are not synced back to remote

### ISSUE THREAD

**Issue by ohowden** [dexie/Dexie.js#1095]
Hello,
In our syncable implementation, we have a remote database that is synced to the client. 
The addition of some of these items to our local database will trigger hooks, which in turn can sometimes generate new data in other tables. 
Currently, the data that is created during a sync application is not then synced to the remote. Is this by design? 
Do you have any suggestions on how we would achieve the result that after sync application, all this data was pushed in the changes array to the remote? 

We're using Dexie 3.0 and syncable latest beta.

Thank you
Oliver

**Comment by oliverhowden** [comment]
After a few hours of debugging, from what I understand this is due to the fact that dexie-observable sets                 // Derive ```
"source" property from parent transaction by default
                if (trans.parent && trans.parent.source)
                    trans.source = trans.parent.source;
```
This means any data created during the hook is treated as being owned by the remote. 
Is there a built in way we are able to mitigate this by any chance?

Cheers

**Comment by oliverhowden** [comment]
Any thoughts on this? Currently forked the package but it's very brute-ish...

**Comment by dfahlander** [comment]
I'm afraid it is not configurable. But if it wouldn't check source, the remote changes would be sent back again to the same remote that sent them, possibly triggering an infinite stream back and forth between the client and the remote.

**Comment by oliverhowden** [comment]
Only if the sync server implemented the same modification. If it were in either one, there is no infinite loop.

**Comment by quolpr** [comment]
@dfahlander do you have a possible idea of how to solve this issue? Maybe we should store the ids of already applied changes(and give changes the UUID), instead of marking the source of change in the transaction. Or maybe you have a better idea. Thanks 🙂

**Comment by dfahlander** [comment]
I don't like the idea of automatically generating additional mutations on the client that has to be synced back to the server in the same transaction. IMHO, the sync transaction should do its job only.

When that transaction commits, it could possibly wake up a subscriber to do some computation or other job that would generate new mutations, but in different transaction if so.
