### ISSUE TITLE
Transaction time under load

### ISSUE THREAD

**Issue by DZakh** [dexie/Dexie.js#1116]
I've noticed, that when I have a lot of heavy operations In my code without a break the transaction time becomes too long.
It just looks like that unlike other promises in code the result of the transaction doesn't want to be put at the end of the event loop. 
So the time increases from the initial ~100ms to ~5000+
What's more interesting, in Chrome it doesn't even finish till I clear the event loop. In firefox, it continues to work but very slow.
Moreover, it doesn't matter if the table is empty or has smth like 1000+ objects.

I know that it's not normal, that my app is under such a heavy load, but js built the way that even in this case the result should go at the and of a queue and at least work in some way.

**Comment by dfahlander** [comment]
Hi! Not sure I understand the issue completely. What do you mean with clearing the event loop? Could you give a code example with code comments that explains what you expect and what is happening?

**Comment by DZakh** [comment]
Talking about clearing event loop, I meant a lot of constant heavy operations, that fills it, and that I have an ability to stop these operations.

Also, I've made some measuring.
On average it took:
2000ms to get data from dexie, using only toArray()
and +-200ms if I did it with pure indexeddb.
These tests were with empty dbs.

But when I tried more complex selectors, dexie didn't resolve any data till I stopped heavy operations on the background.

Looking at these results I've realized that the issue isn't fully on dexie's side, because indexeddb itself works equally slow.
But after that I've made an experiment and tried to put my db in a web-worker and it started resolving data after 50-200ms.
Although, this test was with pure indexeddb, but I think it'll work well with dexie either.

**Comment by dfahlander** [comment]
Ok i get it! Are you using Zone.js? (probably if you use Angular).

**Comment by DZakh** [comment]
No, I don't use any specific async libraries.
Talking about the project, it's React/Redux with many optimization issues.
I'm currently dealing with them, but they somehow lead to another problem with indexeddb :)

**Comment by dfahlander** [comment]
Ok. IndexedDB use a lot of events when you use IDBCursor which can starve the main thread a bit. Using it from a worker can help. In your case it seems to help a lot. It would be interesting to know what about how you choose to proceed. Dexie uses getAll() / getAllKeys() whenever possible to avoid IDBCursor iteration, but as soon as you do more complex queries, it has to use IDBCursor- that is among other stuff:

* Queries that has an offset. (Limit is ok and can still use the optimized methods)
* case insensitive queries
* Dexie's Collection.filter(). Work around it by using toArray() and do manually filter on the resulting array.
* or-queries.
* inAnyRange-queries
* notEqual()
* noneOf()
* startsWithAnyOf()
* Avoid each(). Prefer use toArray() instead.

**Comment by DZakh** [comment]
Thank you for such a detailed answer. I'll definitely move db to the web worker. After that, if I still have problems with queries, I'll only use toArray and then filter it afterward.
