### ISSUE TITLE
dexie-cloud: cloud  sync flickering

### ISSUE THREAD

**Issue by maor700** [dexie/Dexie.js#1359]
Hi, i'm implementing treeview base on dexie as a model;
locally all fine.
but in cloud mode there is some issues with  tree duplication
and with multi select nodes;

code:

```ts
duplicateTree = async (treeId: string) => {
    return await this.transaction("rw", this.trees, this.treesItems, async () => {
      if (!await this._canAddTree()) return;
      // check if exist
      const currentTree = await treesDB.trees.get(treeId);
      if (!currentTree) return;
      // create new Tree with no treeItems
      const { treeName } = currentTree;
      const newTreeId = await this.createNewTree(`${treeName}-copy`, false, currentTree);
      if (!newTreeId) return false;

      // get all items from current tree
      const coll = await this.getAllTreeItemsCollection(treeId);
      const idsMap: any = {};

      // iterate over them and add each with the new treeId
      await coll.each(async (item) => {
        const newNodeId = await this.treesItems.add({ ...item, treeId: newTreeId, id: undefined as any });
        idsMap[item.id] = newNodeId;
      });

      const newTreeColl = await this.getAllTreeItemsCollection(newTreeId);
      await newTreeColl.modify((item, ref) => {
        const { parentPath } = item;
        // fix parrentPath with new ids
        const newParentPath = parentPath.split("/").map(_ => idsMap[_]).join("/")
        const newItem = { ...item, parentPath: newParentPath };
        ref.value = newItem;
      })
    })
  }
```

sorry about the mess with github etidor;
her is my repo:
[https://github.com/maor700/trees-creator](https://github.com/maor700/trees-creator)
and this is the app online:
[https://trees-creator.vercel.app/](https://trees-creator.vercel.app/)

thanx

**Comment by dfahlander** [comment]
Thanks for a nice sample. I could successfully use your deployed app and create trees and duplicate them. However, I didn't find a way to reproduce the issue. Not sure if I understand how the bug manifest itself. Maybe need a way to trigger db.cloud.login() to reproduce the issue?

I've fixed a lot of issues in the latest versions of dexie@next (3.2.0-beta.2) and dexie-cloud-addon@latest (1.0.0-beta.3) that was published last night. Try `yarn add dexie@next dexie-cloud-addon@latest dexie-react-hooks@latest` to make sure you have the latest versions.

Would it be possible to deploy a new version of the app that can be used to reproduce the issue (with a login button or similar)?

Kind regards
David

**Comment by maor700** [comment]
Thank you David.
I really appreciate your efforts to help me these days ...
You're right, the issues only appear in "logged-in" mode so I added the login btn again.
Anyway, I upgraded the packages as you recommended.
You can try again on the same page:
https://trees-creator.vercel.app/

List of issues:
1. Duplication does not work.
2. Multi-select flickering when you select everything and deselects a specific node and tries to re-select everything.
3. Synchronization of two clients works, but very quickly does not

**Comment by dfahlander** [comment]
Thanks! This is a good repro. I will troubleshoot it and come back. Might take some time as I will be traveling this week. Probably able to trace it down until some time next week.

**Comment by dfahlander** [comment]
I was able to find an issue with request queueing that was hit when duplicating a tree on a synced table. I am not able to verify if this solves this issue in whole right now (just took the chance to look at it during morning coffee at a hotel) but the issue that was solved was definitely a bug so if we're lucky this could take us one step further. Will continue looking at it next week. The issue I found is resolved in dexie-cloud@1.0.0-beta.5.

**Comment by maor700** [comment]
Wow! Don't sucrefice you vication for that.
When beta 5 will be released?

**Comment by dfahlander** [comment]
I'm too curious to find out what it could be. Found a bug and released beta 5 this morning so you could try it. But I don't know if it fixed the issues as there might be more bugs around the case that happens in your .each() callback - it needs to queue up the requests and that part was obviously not tested before. Either this was fixed on its whole with beta.5 or there are other issues to solve there. If still issue to duplicate trees with beta.5 you could also work around this bug by using toArray() instead of each () and then do a bulkAdd() instead from the result (after mapping it). This would avoid forcing the framework to queue up requests.

**Comment by dfahlander** [comment]
This morning I was able to debug the "flickering" issue as well, which turned out to be a bug on the server for comparing array keys. I've published an updated cloud service with the issue fixed. It seems also that dexie-cloud-addon 1.0.0-beta.5 did fix the tree duplication issue. So it seems both bugs are gone now. Please confirm when you have a chance.

**Comment by maor700** [comment]
I updated the version, and as you said it did solve the issues.
Thank you so much for this wonderful product.
An unrelated question, when two clients on the same user become offline and make local changes when they go back online how does the cloud decide what to do with the different versions? Unite them? Taking the latest? What happens when there is conflict? This is a serious problem.
