### ISSUE TITLE
dexie-cloud OTP auth needs

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1386]
I can tell auth is still a work in progress, so it might be early to make comments on it, but I thought I'd write up what I'm looking for so far. I've read through the dexie-cloud-addon sources and I think I've got a decent grasp on what is and isn't there.

* I don't want to use custom auth; the OTP flow is much more pleasant than futzing around with netlify identity or auth0. But I do want some control over _when_ it is kicked off.
* The first thing that's missing is a `logout` feature. I can't test the auth flows easily if I can't turn it off. 😀 I _think_ I can mimic it with a delete query on the `$logins` table, but I haven't tried it yet. 
* I'd like a `useCurrentUser` react hook. I found the `db.cloud.currentUser` and it has the info I need, but it's not clear to me how best to react to changes in it. That is probably because I don't fully understand BehaviourSubject. I might dig through `useLiveQuery` and see if I can extract the parallels, but a hook would be easier.
* Docs as to how to manually kick off the OTP sequence if `requireAuth` is `false`. I think this _should_ be as easy as calling `db.cloud.login()`, but I wasn't able to test easily because my user is already authenticated (see point 1 🤣). Related discussion: https://github.com/dfahlander/Dexie.js/discussions/1362

**Comment by dusty-phillips** [comment]
Turns out my research wasn't that hard... If anyone wants to support manual auth, here are a couple functions that will get you what you need:

```typescript
import db from 'Db/database'
import { useLiveQuery } from 'dexie-react-hooks'

export interface User {
  email: string
  isLoggedIn: boolean
  name: string
  lastLogin: Date
}

export async function logOut(): Promise<void> {
  await db().table('$logins').clear()
}

export async function logIn(): Promise<void> {
  await db().cloud.login()
}

export function useGetUser(): User {
  return useLiveQuery(() =>
    db()
      .table('$logins')
      .filter((u) => u.isLoggedIn)
      .first(),
  )
}
```

I don't think these are the "correct" versions in the sense that I will put up a PR against dexie-cloud for them, but they are serving my needs for the time being.

**Comment by dfahlander** [comment]
Thanks for your feedback! The docs are indeed a long way behind, but the code you posted should be correct. I haven't tried myself to delete logins but the result should be that next sync should remove all authorized data from indexeddb, keeping only public data. This is almost the same as deleting the entire db or clearing out all the tables in case there are no public data.

There are a couple of observables such as `currentUser` on `db.cloud`. These can be consumed using [useObservable](https://github.com/streamich/react-use/blob/HEAD/docs/useObservable.md)  from the 3rd party library [react-use](https://github.com/streamich/react-use). My intention is to refer to react-use or possibly other similar libraries in the docs for consuming the observables.

The api is still being extended and there will be some new properties on db.cloud in the next version. I could have been offering hooks directly from dexie-react-hooks but it feels like it would expose a bit to much of a redundant api surface.

**Comment by dusty-phillips** [comment]
Confirmed that deletion works exactly as you describe.

`useObservable(db().cloud.currentUser)` works fine in Javascript, but I don't think `UserLogin` is exported from a public interface yet, so I had to `import { UserLogin } from 'dexie-cloud-addon/dist/types/db/entities/UserLogin'`.

The new version of my file, for anyone watching:

```typescript
import db from 'Db/database'
import { useObservable } from 'react-use'
import { UserLogin } from 'dexie-cloud-addon/dist/types/db/entities/UserLogin'

export async function logOut(): Promise<void> {
  await db().table('$logins').clear()
}

export async function logIn(): Promise<void> {
  await db().cloud.login()
}

export function useGetUser(): UserLogin | undefined {
  return useObservable(db().cloud.currentUser)
}
```

**Comment by j-5-s** [comment]
i see that `db.cloud.login()` creates its own overlay ui:

![Screen Shot 2023-09-23 at 4 16 31 PM](https://github.com/dexie/Dexie.js/assets/666455/55ad3d9f-5a7d-4e22-ae62-d0214a4bd826)

Are there plans to expose the methods to the client library so that I can add my own UI and just call a method like 
`db.cloud.sendLoginEmail(someEmail)`?

**Comment by dfahlander** [comment]
Yes, there's the configuration parameter `customLoginGUI`  in [db.cloud.configure()](https://dexie.org/cloud/docs/db.cloud.configure()). Seeing it to true will disable the built-in prompts. To replace them, listen to the observable [db.cloud.userInteraction](https://dexie.org/cloud/docs/dexie-cloud-addon#api) and prompt user accordingly.

The code from the [defaul-ui](https://github.com/dexie/Dexie.js/tree/194abe82b6dc5c073652e5e86a1eed4d984a05a0/addons/dexie-cloud/src/default-ui) might be the best way to see how it can be done.

**Comment by dusty-phillips** [comment]
@dfahlander i think this can be closed. 🎉

**Comment by dfahlander** [comment]
Thanks, it's an example on https://dexie.org/cloud/docs/authentication#customizing-login-gui that was published after this issue.

**Comment by retotito** [comment]
Hey David

I checked out your example for customizing the login Gui: 
 https://dexie.org/cloud/docs/authentication#customizing-login-gui

I'm not familiar with react.
Do you have an example for that in Javascript or Typescript?

Thanks for your answer

**Comment by dfahlander** [comment]
You basically subscribe to the observable in db.cloud.userInteraction and act accordingly. I could try give an example but it would depend on GUI framework - Svelte, Vue, vanilla Web components, classical DOM manipulation or jQuery would all give different examples. What would be your preferred choice?

**Comment by retotito** [comment]
Hey thanks for your quick response.

I just figured it out from your example and made a Svelte version that is working.
(Just don't know if the alert messages are working, cause didn't get any alerts so far.)

Here the code if somebody is looking for a Svelte solution:

https://github.com/retotito/dexieClou_login_GUI_svelte/tree/main
