### ISSUE TITLE
Dexie cloud check if online

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1391]
Is there a way to check if the cloud db is in offline or online (syncing available) mode? I would like to render certain components conditionally depending on status. I could hit an arbitrary http endpoint, but am hoping there is/can be a useLiveQuery access for connection status.

**Comment by dfahlander** [comment]
There's a property `db.cloud.syncState` which is an instance of Rx' [BehaviorSubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md). If you are in ReactJS, you can consume the observable using react-use' [useObservable](https://github.com/streamich/react-use/blob/master/docs/useObservable.md). The properties of the result is a [SyncState](https://github.com/dfahlander/Dexie.js/blob/master/addons/dexie-cloud/src/types/SyncState.ts) with property `status` that can be any of "not-started" | "connecting" | "connected" | "disconnected" | "error" | "offline". Where "disconnected" means that user has been idle for more than 3 minutes and the client has chosen to disconnect the websocket.

Theres an example in [SyncStatusIcon.tsx](https://github.com/dfahlander/Dexie.js/blob/master/samples/dexie-cloud-todo-app/src/components/navbar/SyncStatusIcon.tsx) of the todo-app.

**Comment by dusty-phillips** [comment]
This is working well for me.
