### ISSUE TITLE
Re-Indexing the key field

### ISSUE THREAD

**Issue by cpgb85** [dexie/Dexie.js#1458]
I have software I'm writing that will be running constantly, possibly for years.  Is there a way to reindex the the key field so i don't eventually hit the ceiling of the max number?

**Comment by dfahlander** [comment]
There is no risk it would ever reach the max number of 2^53 for autoIncremented primary keys in indexeddb. If you would constantly add a new object every single millisecond continuously, the max number would be reached after 285 000 years.
