### ISSUE TITLE
Not able to check if a table exists

### ISSUE THREAD

**Issue by Rednas83** [dexie/Dexie.js#1460]
Just started using dexie. 

How can you check if a table exists?

Tried (v3.2.0):
```
db.tables // Only returns used tables (with 1 or more rows)
db['table'] // Only returns 'true' when the table is used (with 1 or more rows)
```

Suggestion:
```
db.tables // Returns all existing tables (whit 0 or more rows!)
db['table'] // Returns 'true' when the table exists (with 0 or more rows!)
```

**Comment by dfahlander** [comment]
If you are looking for a way to open a database without declaring the schema using version().stores(), and instead inspect what tables there are on the database, have a look in these docs: https://dexie.org/docs/Dexie/Dexie.open()#sample and learn the difference between opening a declared database and open one in dynamic mode.

When you declare the database using version().stores(), the table-properties are there instantly before the call to db.open() completes. Table properties won't reveal any rows until you query them with for example db.myTable.toArray().

When you do not declare the database using version().stores(), you can never know anything about the database tables until you've opened it. To do that, call db.open() and await its Promise, Then you can inspect the schema that it found.

**Comment by Rednas83** [comment]
I am just trying dynamic mode, but I am a bit confused about what the idea behind this is. 
`const db = new Dexie('organizer').open()`

What are the differences with 'normal mode'?

Tried:
```
db.tables // Returns undefined (with 3 'stores'  inside the 'organizer' database)
await db.tables // Returns undefined (with 3 'stores'  inside the 'organizer' database)
await db.friends.add({ name: "Josephine", age: 21 }); // Returns 'Cannot read properties of undefined (reading 'add')'
await db // Returns dexie but without the stores like in 'declaration' mode?
```

Just my notes after reading the docs:
![image](https://user-images.githubusercontent.com/25219229/145221613-f084078a-51e0-4ed8-b8c1-29076d681af3.png)

**Comment by dfahlander** [comment]
I though I explained everything in the docs.

db.open() returns a Promise. Promises must be waited for.

Either using await:

```js
try {
  const db = await new Dexie('organizer').open();
  console.log(db.tables);
} catch (error) {
  console.error(error);
}
```

...or using .then():

```js
new Dexie('organizer').open().then(db => {
  console.log(db.tables);
}).catch(error => {
  console.error(error);
});
```

**Comment by Rednas83** [comment]
Thank you, I indeed was missing `await` when calling `open`. Unfortunately I am still not able to read/write in 'dynamic mode'
```
import Dexie from 'dexie'
// this.db = new Dexie('organizer')
// const db = await new Dexie('organizer').open()
export default {
  data() {
    return {
      db: undefined
    }
  },
  async mounted() {
    // this.db = new Dexie('organizer') // Normal mode
    this.db = await new Dexie('organizer').open() // Dynamic mode
  },
```
```
db.tables // Returns undefined (with 5 'stores'  inside the 'organizer' database)
await db.tables // Returns undefined (with 5 'stores'  inside the 'organizer' database)
await db.friends.add({ name: "Josephine", age: 21 }); // Returns 'Cannot read properties of undefined (reading 'add')'
await db // Returns dexie but without the stores like in 'declaration' mode?
```
In 'normal mode' I get:
![image](https://user-images.githubusercontent.com/25219229/145236354-6be4dc58-796a-41c9-8554-abf59ea7fafb.png)
I am getting the 'correct _StoreNames', but I still can't read/write like in the 'normal mode'.

In 'dynamic mode' I get:
![image](https://user-images.githubusercontent.com/25219229/145239478-6c84c053-d174-4858-9983-dde1f1240acc.png)

Looks like the 'table objects' are only there in 'normal mode' after declaration. Is this expected?

**Comment by dfahlander** [comment]
> db.tables // Returns undefined (with 5 'stores'  inside the 'organizer' database)

You are not describing where you get this `db` from. If it's `tables` property returns undefined, it's probably not a Dexie instance.

No generated props on db are only when opening non-dynamically: https://dexie.org/docs/Dexie/Dexie.[table]

**Comment by Rednas83** [comment]
Tried setting up a sandbox to show what I mean but I get unknown error
https://codesandbox.io/s/black-brook-fcdpw?file=/src/App.vue

Do you also have a working sandbox for vue? The one provided for vue doesn't seem to work
https://codesandbox.io/s/vue-dexie-livequery-87exj?file=/src/main.js

**Comment by dfahlander** [comment]
Need to close this for book keeping.

The example codesandbox for vue that we link to from the web page (and that you also link to here) is working in my various browsers (chrome, firefox, safari, different profiles etc).

**Comment by Rednas83** [comment]
Not sure what the problem was previously but the sandbox is now also working on my end.

I forked it and added 'dynamic mode'.
* 'Static mode' is working as expected with adding, clearing, deleting, etc.
* But with 'dynamic mode' I get errors

Can you have a look? It's really driving me crazy why I don't understand 'dynamic mode' yet🤪
https://codesandbox.io/s/vue-dexie-dynamicmode-iek4o

**Comment by dfahlander** [comment]
In dynamic mode you store a promise in this.db, not a Dexie instance.
![image](https://user-images.githubusercontent.com/6791329/146166289-6267bd55-894a-48ba-94a7-2126cea8449e.png)

If you need more assistance, you are welcome to [order private support](https://dexie.org/contact)

**Comment by Rednas83** [comment]
I am not sure if private support will help anymore. I will stick to 'static mode' and will write a script to automaticly declare the tables. I was hoping 'dynamic mode' could do this trick for me

Something like:
![image](https://user-images.githubusercontent.com/25219229/146171948-8a1deca3-8964-41dc-8b37-b2794a3ffc0a.png)

Thank you for your support and your great work on this cool library
