### ISSUE TITLE
Store single key:value pair

### ISSUE THREAD

**Issue by justinmoon** [dexie/Dexie.js#1466]
Stupid question: is it possible to store a single `key:value` pair in Dexie? No table, no collection, just `key -> value`.

My app keeps track of a `cursor` from an API. After first load there is always one `cursor` so it seems kinda stupid to store it in a collection ...

**Comment by dfahlander** [comment]
```js
const db = new Dexie('myKvDB');
db.version(1).stores({
  keyvals: ''
});
```

## Store item
```js
db.keyvals.put(
  {x: 'bar'}, // value
  'foo' // key
);
```

## Load item
```js
await db.keyvals.get('foo');
```

## Observe item
```js
liveQuery (
  () => db.keyvals.get('foo')
).subscribe(x => console.log(x));
```

```

**Comment by justinmoon** [comment]
Thanks and sorry I couldn't figure that out myself! Thanks for the great product.

**Comment by josh-tt** [comment]
I had the same struggle. :) Would be great some more basic examples with roundtrip were in the getting started docs. I imagine a lot of people investigating options for storage (local forage, idb etc. ) are looking for this as well as a first step.
