### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Song')

### ISSUE THREAD

**Issue by ampossardt** [dexie/Dexie.js#1474]
`
SongArtist.ts:7 Uncaught TypeError: Cannot read properties of undefined (reading 'Song')
    at Module.Song (SongArtist.ts:7)
    at Module../src/database/db.ts (db.ts:28)
    at Module.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Module../src/database/models/Song.ts (Artist.ts:7)
    at Module.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Module../src/database/models/index.ts (SongArtist.ts:7)
`

My app is failing on this line where I define class mappings (after custom DB instantiation):
`db.songs.mapToClass(Song);`

Everything was functioning previously (put a bunch of records to the database) and is failing now that I'm trying to read them.

My db file looks like this:
```
class MyDb extends Dexie {
  songs!: Table<Song>;
  artists!: Table<Artist>;
  albums!: Table<Album>;
  songArtists!: Table<SongArtist>;
  
  constructor() {
    super("MyDb");

    this.version(1).stores({
      songs: 'id, name, addedOn, albumId',
      songArtists: '++id, songId, artistId',
      albums: 'id, title, smallThumbnail, largeThumbnail',
      artists: 'id, name, genres'
    });
  }
}

const db = new MyDb();

db.artists.mapToClass(Artist);
db.songArtists.mapToClass(SongArtist);
db.albums.mapToClass(Album);
db.songs.mapToClass(Song);

export { db };
```

The class of the table in question looks like this:
```
import { IAlbum, IArtist } from ".";
import { db } from "../db";
import { SongArtist } from "./SongArtist";

export interface ISong {
  id: string;
  name: string;
  addedOn: Date;
  artists: IArtist[];
  album: IAlbum;
}

export class Song implements ISong {
  id: string;
  name: string;
  addedOn: Date;
  artists: IArtist[];
  albumId: string;
  album: IAlbum;

  constructor(id: string, name: string, addedOn: string | Date, albumId?: string) {
    this.id = id;
    this.name = name;
    this.addedOn = typeof addedOn === 'string' ? new Date(addedOn): addedOn;
    
    if(albumId !== undefined) this.albumId = albumId;
  }

  addArtists(artists: IArtist[]) {
    this.artists = artists;
  }

  addAlbum(album: IAlbum) {
    this.album = album;
  }

  create() {
    return db.transaction('rw', db.songs, db.songArtists, db.artists, db.albums, () => {
      return Promise.all<any>(
        [
          Promise.all(
            this.artists.map(artist => db.artists.put(artist))
          ),
          Promise.all(
            this.artists.map(artist => db.songArtists.put(new SongArtist(this.id, artist.id)))
          ),
          db.albums.put(this.album)
        ]
      ).then(results => {
        const albumId = results[2];

        db.songs.put(new Song(this.id, this.name, this.addedOn, albumId))
          .then(result => console.log("Song saved."))
      })
    })
  }
}
```

I'm scratching my head on this one a little bit since the error message isn't telling me much at this point. It's complaining about SongArtist which in this case is just a join table I'm using to keep track of all of the artists that are related to a song. Here's that class:
```
export interface ISongArtist {
  id: number;
  songId: string;
  artistId: string;
}

export class SongArtist implements ISongArtist {
  id: number;
  songId: string;
  artistId: string;

  constructor(songId: string, artistId: string) {
    this.songId = songId;
    this.artistId = artistId;
  }
}
```

Not sure if something is obviously misconfigured here but SongArtist is only referenced and used in one of the helper functions that exists on Song to create a record and all of the associated records (Album, SongArtist). Any ideas?

**Comment by dfahlander** [comment]
I believe this is due to recursive imports. I would suppose that Song.ts imports db.ts and db.ts imports Song.ts ? The problem is that the runtime gracefully allows recursive imports but omits executing certain modules (based on the order in which they are imported). The problem happens when calling mapToClass() - 'Song' was imported but since it recursively imports the same module as is being executed, the runtime skips to execute it - so Song is still undefined instead of being a class.

I suppose a solution is to split db.ts between declaration and class mapping:

* db.ts: Declare the class but omit calling mapToClass
* db-map-classes.ts: Import db + the models and call mapToClass
* index.ts (or similar): make sure to import db-map-classes so that the code there is excecuted on startup.

**Comment by ampossardt** [comment]
ah, that makes sense. moved my mappings to a separate file and everything's working again, thanks! i really appreciate the quick response
