### ISSUE TITLE
Dexie.Observable Missing dexie version 3.x

### ISSUE THREAD

**Issue by gotjoshua** [dexie/Dexie.js#1492]
Observable is supposed to be compatible with 4.x (according to [package.json](https://github.com/dexie/Dexie.js/blob/4d94d2dbe8f456e79b3423626e7415989ec45c0b/addons/Dexie.Observable/package.json#L82)) but there is an extra check that throws this error:
```
Dexie.Observable.js:64 Uncaught Error: Missing dexie version 3.x
    at Observable (Dexie.Observable.js:64:15)
    at dexie.ts:222:29
    at Array.forEach (<anonymous>)
    at new Dexie2 (dexie.ts:222:12)
    at new TodoDB (dexie.ts:34:5)
    at dexie.ts:65:23
```

**Comment by dfahlander** [comment]
Resolved with dexie-observable@[4.0.0-beta.13](https://www.npmjs.com/package/dexie-observable/v/4.0.0-beta.13)
