### ISSUE TITLE
mapToClass does it work for class properties too?

### ISSUE THREAD

**Issue by pankajsoni19** [dexie/Dexie.js#1502]
I have a class structure like this

```
export default class Message {
    id: string = "";
    media: Array<Media> = [];
}

export default class Media {    
    thumbKey: string = ""
    
    isImage = (): boolean => {
        return this.mimeType.includes("image");
    }
    
}
```

I am creating tables like this

```
export default class MyDB extends Dexie {

message!: Table<Message, string>;

private constructor() {
    super('my-db');
    
    this.version(1).stores({
      message: 'id',
    });

    this.message.mapToClass(Message);
  }
}
```

now when I query

```
let message. = table.message.get("id")

message.media[0]. isImage()

```

the `media` is simple object array instead of being of class type `Media`. and the `isImage()` function call fails.

so does `mapToClass` take class properties into account?

**Comment by dfahlander** [comment]
No it only maps resulting objects to become instances of given class without executing its constructor. It uses`Object.create(MappedClass.prototype)` instead of `new MappedClass()`.

**Comment by pankajsoni19** [comment]
As there is nothing more to this, closing the issue.
And more so, this sort of property based on classes should get mapped too, maybe in a later version of dixie.
for now, someone using mapToClass this caveat should be documented. ( I am not that well versed with JS nuances).
for now dixie has all the features that I want, going to deploy it soon to prod in use.

**Comment by dfahlander** [comment]
> As there is nothing more to this, closing the issue. And more so, this sort of property based on classes should get mapped too, maybe in a later version of dixie. for now, someone using mapToClass this caveat should be documented. ( I am not that well versed with JS nuances). for now dixie has all the features that I want, going to deploy it soon to prod in use.

Thanks for the feedback. The reason behind the current behavior is to reserve constructors for the job of instanciating entities from application code using new() and let the DB-backed instances only return what is in the DB. If we'd expect a default constructor to be in place, we'd put a requirement on the app code to not declare parameterized constructors, or at least to always support the case when constructor is called without parameters.

But I think you have a point and there might be a future version that will use your approach.

**Comment by relvingonzalez** [comment]
It seems that using the example of Typescript with Mapped Classes on version 4 (found here https://dexie.org/docs/Typescript),  one cannot create a new instance of the classes (const myClass = new MyClass()). It throws a TypeError at new Entity (dexie.js:1191:26) from extending Entity. Is this expected, or in these cases is it advised to use the "old" way?

**Comment by dfahlander** [comment]
> It seems that using the example of Typescript with Mapped Classes on version 4 (found here https://dexie.org/docs/Typescript), one cannot create a new instance of the classes (const myClass = new MyClass()). It throws a TypeError at new Entity (dexie.js:1191:26) from extending Entity. Is this expected, or in these cases is it advised to use the "old" way?

It's intendedly throwing because Entity subclasses are only meant to be new:ed by Dexie and not by application code. To add new entries, use db.myTable.add({...PoJo props}) and not by new:ing them. To obtain an instance of the entity, one must add it and then get it from DB to get the instance.
