### ISSUE TITLE
Svelte liveQuery not returning data

### ISSUE THREAD

**Issue by staab** [dexie/Dexie.js#1504]
I have the following sveltekit route:

```
<script>
  import {liveQuery} from 'dexie'
  import shimIndexedDB from 'indexeddbshim'
  import {Dexie} from 'dexie'
  import {browser} from '$app/env'

  const opts = {}

  if (!browser) {
    shimIndexedDB(opts, {checkOrigin: false})
  }

  const db = new Dexie('test', opts)

  db.version(1).stores({
    things: "id",
  })

  db.open().then(async db => {
    console.log('Database ready')
  }).catch(err => {
    console.error(err)
  })

  const things = liveQuery(async () => console.log('a', await db.things.toArray()))
  const addThing = id => db.things.add({id})

  $: console.log('b', $things)
</script>

<button on:click={() => addThing(Math.random())}>click</button>
{#each ($things || []) as thing}
  <div>{thing.id}</div>
{/each}
```

When I press the button, no list items show up, and the console reads:

```
b undefined
Database ready
a []
a [{…}]
a (2) [{…}, {…}]
```

I get the same behavior when I remove all the async/await stuff from the liveQuery function. I'd love for liveQuery to work, let me know how I can make that happen or help diagnose.

**Comment by dfahlander** [comment]
That's because your callback to liveQuery() only return undefined.

**Comment by staab** [comment]
Sheesh, I apologize, I really did spend an hour on this before opening an issue. Thanks for sanity checking my work.

**Comment by dfahlander** [comment]
Note: The latest version of dexie@next (version 4.0.1-alpha.10) gives a bit better svelte and sveltekit support:

* Typings of Observables returned from liveQuery() is type-wise compatible with Svelte Readable
* No need to check for browser / SSR within your queries as the code executes fine on both server and browser
