### ISSUE TITLE
is not clear how work bulkput() and array keys...

### ISSUE THREAD

**Issue by mredodos** [dexie/Dexie.js#1505]
hi, for me is not clear how work bulkput() and array keys(i cant  understand how to use it)... can you explain better and put some example pls? 

best regards Edoardo

**Comment by dfahlander** [comment]
Normally you shall not provide the `keys` argument to bulkPut(). Only if the keys isn't be part of the value (not using [inbound](https://dexie.org/docs/inbound) keys). 

I refer to the docs of [bulkPut() When to use the keys array](https://dexie.org/docs/Table/Table.bulkPut()#when-to-use-the-keys-argument)

**Comment by mredodos** [comment]
thx after few hours of sleep i have understand all XD :D
