### ISSUE TITLE
Searching system

### ISSUE THREAD

**Issue by mredodos** [dexie/Dexie.js#1506]
hi, i try to build a searching system but i cant figure out

`const searching = await db.customers.where('first_name')
          // .startsWithIgnoreCase(searchTerm)
          // .or("first_name")
          .equalsIgnoreCase(searchTerm)
          .or("last_name")
          // .startsWithIgnoreCase(searchTerm)
          // .or("last_name")
          .equalsIgnoreCase(searchTerm)
          .or("email")
          // .startsWithIgnoreCase(searchTerm)
          // .or("email")
          .equalsIgnoreCase(searchTerm)
          .or("billing.phone")
          // .startsWithIgnoreCase(searchTerm)
          // .or("phone")
          .equalsIgnoreCase(searchTerm)
          .distinct()
          .toArray`

i have try with equalsIgnoreCase but when word is used and match both key return 0 results like first and last, and i dont have results if i write the first letter 

i have try with startsWithIgnoreCase found result from first letter but where you have the exact word not exclude the rest

how can mix better and use both in sequence ?

best regards edoardo

**Comment by mredodos** [comment]
i have solved, and found the perfect solution with .startsWithAnyOfIgnoreCase() solution and .or()  AND  fundamental pass an array of term trimmed and splitted from user string input.

```
let splittedSearchTerm = String(searchTerm.trim()).split(" ");

db.customers.where('first_name')
        .startsWithAnyOfIgnoreCase(splittedSearchTerm)
        .or('last_name')
        .startsWithAnyOfIgnoreCase(splittedSearchTerm)
        .or('email')
        .startsWithAnyOfIgnoreCase(splittedSearchTerm)
        .or('billing.phone')
        .startsWithAnyOfIgnoreCase(splittedSearchTerm)
          .toArray
```

hope it can be useful to everyone

best regards edoardo

**Comment by mredodos** [comment]
@dfahlander hi, have you some alternative or solution with email? because if i use the string after @ at symbol the search not work

**Comment by dfahlander** [comment]
> @dfahlander hi, have you some alternative or solution with email? because if i use the string after @ at symbol the search not work

I can't see the problem https://jsfiddle.net/kew7yjvo/

If you believe it's a bug, create a repro on jsfiddle or similar and post it as a new issue.

**Comment by mredodos** [comment]
> > @dfahlander hi, have you some alternative or solution with email? because if i use the string after @ at symbol the search not work
> 
> I can't see the problem https://jsfiddle.net/kew7yjvo/
> 
> If you believe you've found a bug, create a repro on jsfiddle or similar and post it as a new issue.

sorry maybe I explained it wrong

if I write @bar.com or just  bar.com the search returns 0 results, this is because it's obviously not the initial part.
