### ISSUE TITLE
Concurrency and queue

### ISSUE THREAD

**Issue by heyligengregory** [dexie/Dexie.js#1539]
Hi,

I would like to know if there is a locker concept for my usage of Dexie.

I'm using Dexie.js in a Service Worker (based on HTTP Request) where I need to perform an update on an object.

When two request come at the same time, if there is a latency or whatever, one of the two request will overwrite data.

`
public async update(id) {
  	await this.db.transaction('rw', this.db.myObjects, async () => {
      	const obj = await this.db.myObjects.get(id);
		//Perform update on properties
      	await this.db.myObjects.update(obj);
  	});
}
`

If another request come before `await this.db.myObjects.update(obj);`, obj won't have the updated value from request one (which is logical) so I would like that request two wait end of request one (by commited transaction or whatever).

Any similar case in documentation ?

Thanks for your fb.

**Comment by q389491729** [comment]
I have the same question as you. Have you found a solution?

**Comment by dfahlander** [comment]
Transactions locks the data so you can get and put data without risking other simultanous access. IndexedDB transactions are [ACID](https://en.wikipedia.org/wiki/ACID) compliant.
