### ISSUE TITLE
dexie-cloud-addon — Hanging on `db.$logins.toArray()`

### ISSUE THREAD

**Issue by hangtwenty** [dexie/Dexie.js#1546]
The `dexie-cloud-todo-app` is working well for me!

I'm seeing different behavior when I try to use the `dexie-cloud-addon` in my own project, though. I've isolated the issue somewhat: it's hanging when it tries `db.$logins.toArray()` inside `getCurrentUser()`. I've confirmed this by adding logs to `dexie-cloud` (locally). Also confirmed interactively, by attaching `db` to `window`, then in DevTools, doing `await db.$logins.toArray()`; it doesn't complete.

I've confirmed I'm using the same versions as `dexie-cloud-todo-app`, for these dependencies: `dexie` (4.0.0-alpha.1), `rxjs` (7.4.0). The `dexie-cloud-addon` version is also the same, `4.0.0-beta.17` (but with local modifications to add logs). 

I'll try to make an isolated reproduction and share it here.

**Comment by hangtwenty** [comment]
The main difference, in the project where I'm seeing this, is that the project is built with vite (rather than create-react-app/webpack). I'm not sure if that's the culprit, yet.

**Comment by dfahlander** [comment]
There is another issue with problems using Dexie with vite: #1484

**Comment by hangtwenty** [comment]
I think this can be closed now. Details are in https://github.com/dexie/Dexie.js/issues/1484
