### ISSUE TITLE
Dexie-cloud-addon default UI

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1568]
Would you be willing to put a class or id attribute on the `LoginDialog` component? Otherwise there doesn't appear to be a way to identify the component for styling without reimplementing it.

**Comment by dfahlander** [comment]
Definitely

**Comment by dfahlander** [comment]
In latest version dexie-cloud-addon@4.0.0-beta.20, LoginDialog has class "dxc-login-dlg".
