### ISSUE TITLE
where with multiple column and anyof()

### ISSUE THREAD

**Issue by hiren-jarvisbitz** [dexie/Dexie.js#1581]
I have table data as mentioned below.
Id Name Type
1 ABC SCAN
2 BDC SCAN
3 ABC MANUAL
4 BDC EXTDEV
5 ABC EXTDEV

As per the above Tbl data want ABC data including all 3 types.

I have tried below function
export const getInventoryScanProductByAccNameAndType = async (
accName
) => await db.InventoryScans
.where(['AccountName', 'ProductEnterType']).anyOf(accName, ['SCAN', 'MANUAL', 'EXTDEVICE']).toArray();

Can anyone help me to get the data below?

Id Name Type
1 ABC SCAN
2 ABC MANUAL
3 ABC EXTDEV

**Comment by dfahlander** [comment]
Given your table has an index '[AccountName+ProductEnterType]':

```ts
await db
  .InventoryScans
  .where('[AccountName+ProductEnterType]').
  anyOf([accName, 'SCAN'], [accName, 'MANUAL'], [accName, 'EXTDEVICE'])
  .toArray();
```

**Comment by hiren-jarvisbitz** [comment]
thanks a lot. Your answer is very helpful for me.

**Comment by hiren-jarvisbitz** [comment]
Thanks for the above query. This was very helpful to get the data I want.
