### ISSUE TITLE
Modern Dexie build should not be transpiled to es5.

### ISSUE THREAD

**Issue by minht11** [dexie/Dexie.js#1582]
Modern Dexie build should not be transpiled to the such. Right now it even transpiles assign and object spreads including helper functions for them such as `__assign`. Those features have been supported in browsers for 7 years now. If browser supports modules it supports those features. That adds A LOT of bloat to the already big package.

Generally transpiling should be left to the user and not the library so setting `esnext` inside tsconfig wouldn't be an issue, though if you want to be bit conservative `es2020` should be fine too.

CommonJS or other legacy builds can still be transpiled to `es5`, but other users using modern browsers should not pay the cost for that.

**Comment by dfahlander** [comment]
Dexie already has a modern build output in `dist/modern/dexie[.min].mjs`. Package.json is using the `exports` field to inform modern build tools about its existance (while keeping the legacy "main" field pointing to the legacy ES5 version).
