### ISSUE TITLE
Raise minimum supported Node verision from 6.

### ISSUE THREAD

**Issue by minht11** [dexie/Dexie.js#1583]
Current stable Node version is 18, the LTS release is 16. Based on engines field Dexie supports Node version 6. Since that version is no longer supported for a very long time, there is no point for Dexie to support it either, unless some internal build tools require it, but those then should probably be migrated to newer version of Node too. https://github.com/dexie/Dexie.js/blob/e65b7fa0d9321c93857ff684cddb70855b17e615/package.json#L117-L119

**Comment by dfahlander** [comment]
Thanks. The "engines" field was there for historical reasons. I've removed it.
