### ISSUE TITLE
bug sveltekit 

### ISSUE THREAD

**Issue by stloc** [dexie/Dexie.js#1589]
**TypeError: Cannot set property stack of [object Object] which has only a getter**

```
// routes/index.svelte
<script context="module">
	export const prerender = true;
</script>

<script>
	import { liveQuery } from "dexie";
	import { db } from "../lib/db";
	let contrats = liveQuery(
    () => db.contrats.toArray()
  );
</script>

<svelte:head>
	<title>Home</title>
</svelte:head>

<section>
index

<ul>
  {#if $contrats}
    {#each $contrats as contrat}
      <li>{contrat.nom}</li>
    {/each}
  {/if}
</ul>


</section>

<style>

</style>
```

![image](https://user-images.githubusercontent.com/4832070/176151050-9ae9abbb-2ae8-4d1d-9ff7-c453ba006dfb.png)

**Comment by dfahlander** [comment]
Sveltekit tries to run dexie on the server so there's no IndexedDB API to work against.

The solution is to query database on the client only and default to empty array when rendering it on the server:

```svelte
<script>
  import { liveQuery } from "dexie";
  import { db } from "../lib/db";
  import { browser } from '$app/env';
  let contrats = liveQuery(
    () => browser ? db.contrats.toArray() : []
  );
</script>
```

**Comment by dfahlander** [comment]
Repro URL: https://github.com/dfahlander/dexie-issue-1589

**Comment by stloc** [comment]
thank you @dfahlander

**Comment by leocaseiro** [comment]
I had similar issues, and I got the following error: https://tinyurl.com/y2uuvskb

which was related to `https://dexie.org/docs/DexieErrors/Dexie.MissingAPIError` and it was showing as 500 Error.

Thanks to @dfahlander, the workaround worked.

PS: the new API is renamed from `import { browser } from '$app/env';` to `import { browser } from '$app/environment';`

**Comment by dfahlander** [comment]
Thanks @leocaseiro I edited my comment from June 28 accordingly.

**Comment by dfahlander** [comment]
Note: The latest version of dexie@next (version 4.0.1-alpha.10) gives a bit better svelte and sveltekit support:

* Typings of Observables returned from liveQuery() is type-wise compatible with Svelte Readable
* No need to check for browser / SSR within your queries as the code executes fine on both server and browser
