### ISSUE TITLE
svelte Typescript example project issues

### ISSUE THREAD

**Issue by JamesForan** [dexie/Dexie.js#1592]
I am working through the example project which is here: 

https://dexie.org/docs/Tutorial/Svelte#using-typescript

Note, I am using this example with SvelteKit, which uses Vite, and has some default settings.

When simply pasting the example code into my db.ts file, I am getting an error:
```typescript
import Dexie, { Table } from 'dexie'
```

The following error occurs...

``` 'Table' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.```

My initial attempt to fix this was to change the import statement:
```typescript
import Dexie from 'dexie';
import type Table from 'dexie';

export interface Friend {
  id?: number;
  name: string;
  age: number;
}
```

However, when this occurs, I then get a separate type error declaring my database types:

```typescript
export class MySubClassedDexie extends Dexie {
  // 'friends' is added by dexie when declaring the stores()
  // We just tell the typing system this is the case
  friends!: Table<Friend>;  //error occurs here

  constructor() {
    super('myDatabase');
    this.version(1).stores({
      friends: '++id, name, age' // Primary key and indexed props
    });
  }
}
```

so, reverting back to the original example, I then updated by tsconfig.json file...

```typescript
	"compilerOptions": {
		...,
		"preserveValueImports": false, 
		"importsNotUsedAsValues": "preserve"
	}
```

This now works correctly. I am not sure if there will be any issues later on. just noting this for others who come after me :)

**Comment by kevinzg** [comment]
Not sure if this is the issue but you need import `Table` like this:
```typescript
import Dexie, { type Table } from 'dexie';
```

**Comment by JamesForan** [comment]
@kevinzg Thanks for your reply.

That worked perfectly for me. I was able to remove the tsconfig changes mentioned in the issue also.

Might be worth making a change to the Tutorial on the website. For now, I will close the issue. At least we have the problem and solution documented here for future reference.

**Comment by dfahlander** [comment]
Note: The latest version of dexie@next (version 4.0.1-alpha.10) gives a bit better svelte and sveltekit support:

* Typings of Observables returned from liveQuery() is type-wise compatible with Svelte Readable
* No need to check for SSR within your queries as the code executes fine on both server and browser
