### ISSUE TITLE
Nuxt/Vue app crashes with "primKeyAndIndexes.split is not a function" error

### ISSUE THREAD

**Issue by mod49** [dexie/Dexie.js#1619]
Hello everyone,
in a current nuxt2/vue2 app i have added Dexie 3.2.2 to the project. The database definition is in db/dbx.js:

```
// dbx.js
import Dexie from 'dexie'

const db = new Dexie('zeitmanagerDb')

db.version(1).stores([{
  accounts: '&id, username, email, *roles, companyName',
}])

export default db
```

In the logout page i import the db:
`import db from '~/db/dbx.js`
and in one method i simply delete content from the store:
`db.accounts.clear()`

The app crashes with the error shown on the screenshot.

<img width="1602" alt="primKeyAndIndexes" src="https://user-images.githubusercontent.com/49483551/191760676-e052fb36-2fac-4e29-a4e4-3973a7a1cf25.png">

Can anybody help me out with this error?

**Comment by dfahlander** [comment]
Remove the square brackets in the argument to db.version(1).stores(). It expected an object, not an array

**Comment by mod49** [comment]
Thanks for you quick answer. Reading the documentation (esp. https://dexie.org/docs/Version/Version.stores()) carefully i recognize my mistake. Sorry for the inconvenience.
Volker
