### ISSUE TITLE
liveQuery() sveltekit architecture

### ISSUE THREAD

**Issue by MCMattia** [dexie/Dexie.js#1634]
Hi guys, thank you a lot for the work on this library. I have a question about the liveQuery() function.

I am trying to have a observable store in a `.ts` file and import the store in multiple svelte components. It works but the live query gets re-executed each time a component that imports the store is rendered.

This is not the behavior that I would like to have since executing the query takes almost a second and doing this query each time that the same components gets rendered is useless. The component is a form that pop's up multiple times during a regular session.

My liveQuery in the `.ts` file: 
```
export const biosGroups = liveQuery(async () => {
	const staticBiosGroups = await indexedDB.staticBios.orderBy("info.group").uniqueKeys();
	const personalBiosGroups = await indexedDB.personalBios.orderBy("info.group").uniqueKeys(); 

	const joined = [...staticBiosGroups, ...personalBiosGroups];

	return joined as string[];
});
```

My import statement in `.svelte` files:
`import { biosGroups } from "$lib/IndexedDBManager";`

How I am using the store in `.svelte` files::
`items={$biosGroups}`

**Comment by dfahlander** [comment]
Observables returned by liveQuery() are "cold" by default and will re-execute for every call to subscribe(). This is something we are looking at to improve in dexie@4.

In your specific case though, you could use a simple trick to make the observable hot by using a writable store to your assistance:

```ts
import { writable } from 'svelte/store';
import { liveQuery } from 'dexie';

export const biosGroups = writable([] as string[]);

liveQuery(async () => {
	const staticBiosGroups = await indexedDB.staticBios.orderBy("info.group").uniqueKeys();
	const personalBiosGroups = await indexedDB.personalBios.orderBy("info.group").uniqueKeys(); 

	const joined = [...staticBiosGroups, ...personalBiosGroups];

	return joined as string[];
}).subscribe(result => biosGroups.update(result));

```

**Comment by MCMattia** [comment]
This is awesome :)) The svelte trick works perfectly

I hope other peoples will find this issue when they will look for it. 

On the svelte store I have used the `.set` method instead of  `.update `

**Comment by dfahlander** [comment]
Note: The latest version of dexie@next (version 4.0.1-alpha.10) gives better svelte and sveltekit support:

* Typings of Observables returned from liveQuery() is type-wise compatible with Svelte Readable
* No need to check for SSR within your queries as the code executes fine on both server and browser
