### ISSUE TITLE
How to measure how long a transaction takes?

### ISSUE THREAD

**Issue by bruce-c-liu** [dexie/Dexie.js#1641]
When there are a lot of transactions queued up, how do you measure how long any given transaction takes?

Since transactions are queued, there's no way to get the time a transaction actually starts(?). The attached code enqueues the transactions pretty much at the same time sequentially.
```
write 1: |
read:    |
write 2: | 
```

And the transactions execute one after another in the order they were enqueued:
```
write 1: [---]
read:        [---------------]
write 2:                     [---]  
```

But I can't find a way to get the time a transaction actually begins, so I can't calculate the time a given transaction takes. Below is my attempt at it, but it's clearly wrong:
```
write 1:      [---]
write 1 time: |---| // correct
read:             [---------------]
read time:    |-------------------| // wrong
write 2:                          [---]   
write 2 time: |-----------------------| // wrong
```

```js
db = new Dexie('someDB');
db.version(1).stores({
	entries: '++id'
});

console.log('write 1', performance.now());
db.entries.put(new ArrayBuffer(10000)).then(() => {
  console.log('write 1 finished', performance.now());
});
console.log('read', performance.now());
db.entries.toArray().then(() => {
  console.log('read finished', performance.now());
});
console.log('write 2', performance.now());
db.entries.put(new ArrayBuffer(10000)).then(() => {
  console.log('write 2 finished', performance.now());
});
```

**Comment by dfahlander** [comment]
Good question without a simple answer. There's no event triggered when a transaction has finished queuing and can resume, so it's hard go give an answer on it. Maybe you could start the transaction by reading a dummy value and start the timer when that read operation (such as table.get(undefined)) resolves. It would add some extra time to the overall operations but it would give a more correct measuring of the time being spend executing the transaction.

```js
db = new Dexie('someDB');
db.version(1).stores({
	entries: '++id'
});

db.transaction('rw', db.entries, ()=> {
  db.entries.get(undefined).then(()=>{
    console.log('write 1', performance.now());
    return db.entries.put(new ArrayBuffer(10000));
  }).then(() => {
    console.log('write 1 finished', performance.now());
  });
});

...

```

**Comment by bruce-c-liu** [comment]
Gotcha. In that case, wouldn't the below be sufficient? What's the purpose of the dummy call?

```js
db.transaction('rw', db.entries, () => {
   console.log('write 1', performance.now());
   db.entries.put(new ArrayBuffer(10000));
   console.log('write 1 finished', performance.now());
}
```

**Comment by dfahlander** [comment]
> Gotcha. In that case, wouldn't the below be sufficient? What's the purpose of the dummy call?
> 
> ```js
> db.transaction('rw', db.entries, () => {
>    console.log('write 1', performance.now());
>    db.entries.put(new ArrayBuffer(10000));
>    console.log('write 1 finished', performance.now());
> }
> ```

Not really because even if dexie executes the callback directly, the transaction might still be in queue, which can only be detected on first use of it.

**Comment by bruce-c-liu** [comment]
Oops, I meant to put an `await` there. See updated code below.

Hmm, I'm probably misunderstanding something fundamental here.

My understanding is that the callback is guaranteed to begin once the parent transaction starts. And since no other transactions can start, the child transaction's time measured should be correct below?
```js
// parent transaction
db.transaction('rw', db.entries, async () => {
   console.log('write 1', performance.now());
   await db.entries.put(new ArrayBuffer(10000)); // child transaction
   console.log('write 1 finished', performance.now());
}
```

If the above is still incorrect, could you go into a little more detail why the dummy call is necessary with an example?

**Comment by dfahlander** [comment]
The async / await would not really matter here. Callback is still executed before dexie can know whether this top-level transaction is queued or not. Basically - there's no API to know that until you've got your first response (or error) from an operation on the transaction.

*To make things complex, dexie ALSO has added custom support for sub-transactions, but that is only an explicit `db.transaction()` called under another `db.transaction()` call (which is not the case here unless the code was called from within another transaction).*

So, in this case we are only working on a top-level transaction (the put-operation does not fire off any sub-transaction) and there we let the native IndexedDB framework do the waiting for us.

**Comment by bruce-c-liu** [comment]
Ah, I think I have a better understanding now. This is pretty complicated. Thank you!
