### ISSUE TITLE
Large ArrayBuffers fails to sync (imported from StackOverflow)

### ISSUE THREAD

**Issue by dfahlander** [dexie/Dexie.js#1643]
Originally reported at https://stackoverflow.com/questions/74606599/maximum-call-stack-size-exceeded-when-syncing-arraybuffer

> I have a database which stores images (a thumbnail and a full size version) as ArrayBuffers.
> 
> When the dexie-cloud addon tries to sync the changes, it throws an error.
> 
> Thumbnails work fine because they have been resampled down to around 50-60 KB in size. However, the full size image (which can be 100-150 KB) fails in the b64encode function of base64.js:
> 
> ```
> Failed to sync client changes RangeError: Maximum call stack size exceeded
>     at b64encode (base64.js:22:41)
>     at b64LexEncode (b64lex.js:3:21)
>     at Object.replace (ArrayBuffer.js:6:16)
>     at Object.<anonymous> (TypesonSimplified.js:37:31)
>     at JSON.stringify (<anonymous>)
>     at Object.stringify (TypesonSimplified.js:33:31)
>     at syncWithServer.ts:60:16
>     at Generator.next (<anonymous>)
>     at fulfilled (tslib.es6.js:73:58)
> ```
> 
> specially at this line:
> 
> ```
> return btoa(String.fromCharCode.apply(null, ArrayBuffer.isView(b) ? b : new Uint8Array(b)));
> ```
> 
> Are there any work arounds for larger ArrayBuffers?

**Comment by bknode** [comment]
Any progress on this error?

Storing any kind of data over a couple of k is impossible because of the call stack error and it's a bit of a show-stopper for us.

Thanks.

**Comment by dfahlander** [comment]
Thanks for reminder. I'll have a look next week. I suppose it should be an easy fix, replacing btoa-strategy with something else.

**Comment by bknode** [comment]
I haven't seen any updates regarding this. Any progress resolving this issue?

Thanks.

**Comment by dfahlander** [comment]
Thanks and sorry for taking time. The issue is fixed in source but expect a few days until available in dexie-cloud-addon on npm.
