### ISSUE TITLE
How to use useLiveQuery in JavaScript while writing to IndexedDB from WebAssembly

### ISSUE THREAD

**Issue by ablochs** [dexie/Dexie.js#1659]
Is it possible use useLiveQuery from 'dexie-react-hooks' when writing to IndexedDB from WebAssembly (using [Rexie](https://crates.io/crates/rexie))?

I've tried implementing it, but useLiveQuery is not updating. I think this might be because the database transactions need to go through the js Dexie db instance, but I'm not sure. Is there a way to make this work?

**Comment by dfahlander** [comment]
useLiveQuery() will only detect updates done via Dexie.js, so if another indexedDB wrapper is used it will not detect changes since there are no native reactivity in indexedDB.

**Comment by ablochs** [comment]
created a SO question here, if you want credit for answering I will accept the answer https://stackoverflow.com/questions/75169067/how-to-use-uselivequery-in-javascript-while-writing-to-indexeddb-from-webassembl
(closing issue)
