### ISSUE TITLE
inserting duplicate IDs fails

### ISSUE THREAD

**Issue by FKPSC** [dexie/Dexie.js#1662]
redacted to avoid misleading

**Comment by dfahlander** [comment]
Could you provide a repro of this using an online tool such as jsitor or codesandbox? Thanks in advance!

**Comment by FKPSC** [comment]
I tried to replicate it on a jsfiddle but it worked there....
https://jsfiddle.net/qsw54mbe/1/

**Comment by dfahlander** [comment]
The issue you experienced could happen if you execute the code in parallel. Try to verify using console log whether that is the issue and try to avoid it. You could also use a transaction around it to avoid the situation but probably you should first check why the code is launched multiple times instead of one

**Comment by FKPSC** [comment]
We use string IDs and somehow we have duplicates with different capitalization.
I should have checked our data before assuming Dexie was not working with await.
I guess reading that Dexie does not use vanilla promises made me lean too much on that.

I am correct in understanding that the Dexie flavored promises are only important/different when in a transaction callback/block?

**Comment by dfahlander** [comment]
Dexie definitely supports await. String keys are case sensitive. The issue you experienced is most likely not a dexie problem but based on what you posted earlier, the exact behavior is explainable if you launched the code multiple times.

To prevent the code from being executed multiple times from an event handler, use a transaction and also check why it is being launched multiple times (if that is the case).

Based on the snippet you posted earlier before you erased it, using a transaction would mean:

```ts
async function setArticles (articleList) {
      await db.transaction('rw', db.articles, async () => {
          await db.articles.clear();
          console.log('cleared');      
          await db.articles.bulkAdd(articleList);
    });
}
```

Then, if the code would be launched multiple times in paralell, the second execution will wait for the first one to finish as they are locking the same table. Also, check if you can optimize the code to not run them twice if it is already running (for optimization).

**Comment by FKPSC** [comment]
We had duplicates in our production database. The front-end uses `.upper()` on each entry, resulting in duplicates for Dexie.
