### ISSUE TITLE
Array indexes returned as undefined even though they are stored as objects

### ISSUE THREAD

**Issue by shaharyarkhawar** [dexie/Dexie.js#1670]
I am storing an object with key items which is an array of objects itself. It is successfully stored in indexed db.
However, when I try to retrieve this data, (it is not indexed key of table) all other attributes returned are as per stored except for the items that are returned as [undefined, undefined], even though they are stored correctly

**Comment by shaharyarkhawar** [comment]
![image](https://user-images.githubusercontent.com/96112081/217511396-af55d763-2b3f-4b8b-8e90-9f6f54c4c6da.png)
this is returned

**Comment by shaharyarkhawar** [comment]
![image](https://user-images.githubusercontent.com/96112081/217511584-60afcc6b-42db-41ba-a2d4-d438a4ceda3b.png)
This is stored

**Comment by dfahlander** [comment]
Can you share the code that declares and configures the Dexie instance?

**Comment by shaharyarkhawar** [comment]
Sorry for the inconvenience, the issue seems to be somewhere else in the app that is modifying these items.
