### ISSUE TITLE
Paging Query

### ISSUE THREAD

**Issue by chris-jason1224** [dexie/Dexie.js#1673]
the speed of Paging queries will slow down as the number of pages grows. can u show me a demo of efficient Paging Query! thx bro!

my code as follow:
store.orderBy('id').filter(obj =>{
      ...
   
      return true
  }).offset(pageIndex-1 * pageSize).limit(pageSize).reverse().toArray(arr=>{
    ...
  })

**Comment by dfahlander** [comment]
Remove `.filter()` and it should be much faster. IndexedDB is able to natively forward to the correct page but only when not filtering entries using 'filter()'.

**Comment by chris-jason1224** [comment]
i have to attach some other complex conditions currently to filter when paging queries.

**Comment by chris-jason1224** [comment]
> Remove `.filter()` and it should be much faster. IndexedDB is able to natively forward to the correct page but only when not filtering entries using 'filter()'.

i have to attach some other complex conditions currently to filter when paging queries

**Comment by chris-jason1224** [comment]
> Remove `.filter()` and it should be much faster. IndexedDB is able to natively forward to the correct page but only when not filtering entries using 'filter()'.

does there any ways to make it possible?

**Comment by chris-jason1224** [comment]
thx bro,it works
