### ISSUE TITLE
`dexie-export-import` not exposing typings

### ISSUE THREAD

**Issue by eberfreitas** [dexie/Dexie.js#1674]
I see that `dexie-export-import` does have [typings defined](https://github.com/dexie/Dexie.js/blob/master/addons/dexie-export-import/package.json#L7) but I don't seem them in the [npm build](https://www.npmjs.com/package/dexie-export-import?activeTab=explore).

Am I missing something? How can I get those typings? Thanks!

**Comment by dfahlander** [comment]
Thanks for detecting this and reporting it. This must have been an issue with the latest version 4.0.5, as the typings are there in 4.0.4.

**Comment by dfahlander** [comment]
Try upgrade the addon and it should have the typings. If still having issues, please reopen this issue.
