### ISSUE TITLE
dexie-export-import: progressCallback Problem?

### ISSUE THREAD

**Issue by kjanusz** [dexie/Dexie.js#1678]
I am currently exporting data and wonder a little about the behavior of progressCallback (the last two editions are identical). Bug oder Feature?

```
// Console 
Progress: {"done":false,"completedRows":0,"completedTables":0,"totalRows":4,"totalTables":2}
Progress: {"done":false,"completedRows":4,"completedTables":1,"totalRows":4,"totalTables":2}
Progress: {"done":true,"completedRows":4,"completedTables":2,"totalRows":4,"totalTables":2}
Progress: {"done":true,"completedRows":4,"completedTables":2,"totalRows":4,"totalTables":2}
```

Sample Code

```
const exportBlob = await exportDB(db, {
      prettyJson: true,
      progressCallback: (progress) => progressCallbackExport(progress),
      filter: (table, value) => table === 'projekte' && value.id === props.projekt.id,
    });

...

function progressCallbackExport(progress: ExportProgress): boolean {
  console.log(`Progress: ${JSON.stringify(progress)}`);
  if (progress.done) {
    notification.successMessage('Message ... done');
  }
  return progress.done;
}
```

Dependencies:
"dexie": "^3.2.3"
"dexie-export-import": "^4.0.6"
"vue": "^3.2.47"

**Comment by dfahlander** [comment]
It seems to be a duplicate call to progressCallback at the end of the export at [export.ts](https://github.com/dfahlander/Dexie.js/blob/f306804aa6b483665d1b5cbdde9cd16cce7335bc/addons/dexie-export-import/src/export.ts) line 66 when it comes back from exportAll() which also emitted the final state. A safe change would be to remove lines 64-67.
