### ISSUE TITLE
Force liveQuery() to re-query?

### ISSUE THREAD

**Issue by Steve-OH** [dexie/Dexie.js#1683]
I am using Dexie as a browser-side data cache. Once the user signs in and is authenticated, the cache is refreshed from the server with any updates. I'm trying to use `liveQuery()` to notify the app both when real changes are made (works perfectly) and when the update from the server is received (works inconsistently). The problem in the latter case is that if the update from the server has no effect (i.e., the data are unchanged by the refresh), then `liveQuery()` sometimes fires, and sometimes doesn't. This is perfectly reasonable, since nothing actually changed, but it's thwarting my attempt to use `liveQuery()` to let the user know that they're fully up to date.

I can use `Dexie.on.storagemutated` to track this, but that seems to be a rather heavy-handed approach. I wonder if there is some way to tell `liveQuery()` to re-query even if it thinks it shouldn't have to?

The alternative to this is to go back to my Old Way (tm) of doing this, which is to send a message upon the actual receipt of data from the server, but if I do that I may as well not use `liveQuery()` at all, which seems kind of a shame.

**Comment by dfahlander** [comment]
Is there any way you could update the GUI when you're done downloading the data? Let's say you do a fetch() to download the data from server and then a dexie transaction with some bulk put operation? When that transaction is done, could you there trigger a signal to the GUI to update it about the download-done state? I might miss the problem point but need for me that would be a more natural way to provide user feedback from the successful download than liveQuery in this case?

**Comment by Steve-OH** [comment]
Yes, that's exactly what I meant by, "send a message upon the actual receipt of data from the server."

My point is that if I could coerce `liveQuery()` to do this, then I could use it for everything. But I'd rather not use two different mechanisms for what are effectively the same category of notifications (at least as far as this app is concerned). Therefore, if `liveQuery()` won't work for this, then I may as well "manually" send messages for all of these notifications, to avoid the complexity of having two separate but sort of equal notification mechanisms.

Alternatively, I think I might have a go at implementing a subscribable notification mechanism on top of `Dexie.on.storagemutated` that works kind of like `liveQuery()` but includes the additional notifications that I'm looking for.

**Comment by dfahlander** [comment]
I see what you're after and I've heard the same requirement from another customer. What I'm thinking though is that liveQuery is only a monitor of what is in the database. It seems you want to reflect the current sync state, which is rather a state. Another option would be for the download function to update a state-table containing properties of the download/sync state, such as a time-stamp for the last successful download. Then you could query that state-table with a liveQuery and reflect it in GUI. Maybe a successful download less than X minutes ago is regarded as being up-to-date.

**Comment by Steve-OH** [comment]
You're right. And since I'm already using state machines liberally all around the app, it's undoubtedly best to treat things that way.

I put together a small XState machine that I can plug in to wherever it's needed. It's set up to listen to a "data changed" message from `liveQuery()` and a "data fetched" message from the worker that handles data coming from the server.
