### ISSUE TITLE
`DBCoreIndex.primaryKey.name` is always `null`

### ISSUE THREAD

**Issue by FelixZY** [dexie/Dexie.js#1697]
I'm writing middleware where index names are used for a lookup table. This works fine for non-pk indices but for some reason `DBCoreIndex.primaryKey.name` always returns `null`. Since the primary key is not included in `DBCoreIndex.indexes`, this makes it impossible to get the name of the primary key.

Looking at the [source](https://github.com/dexie/Dexie.js/blob/46a430fedeaff6d950dd6bfc9be29317fec48583/src/dbcore/dbcore-indexeddb.ts#L58) there is indeed an always-null assignment on the name property. I assume this is an error?

**Comment by dfahlander** [comment]
I think what you are after is rather the keyPath than the index name.

The native IndexedDB engines has the concept of index names but primary key has no name.
All indices have keyPaths and [inbound](https://dexie.org/docs/inbound) primary keys also have keyPath.
A keyPath is a string or an array of strings.

For example, a dexie schema of:
```js
{
   friends: '++id, name, [name+age]'
}
```
...would have the keyPaths `'id'`, `'name'` and `['name', 'age']`.

**Comment by FelixZY** [comment]
Hm, I think you might be right. I'm too used to relational databases and what I'm really looking for is the "column" name - `keyPath` is probably the closer option.

The whole "array of strings" part has confused me somewhat though. What would the interpretation of `&[a+b]` be for example?

**Comment by dfahlander** [comment]
> What would the interpretation of `&[a+b]` be for example?

It would mean that the composite value of properties `a` and `b` must be unique.

For example if we have  `{a: 1, b:1}` we can safely add `{a: 1, b:2}` but not another `{a: 1, b: 1}`.

**Comment by dfahlander** [comment]
The index name is conceptually only for identifying an index when deleting it and does not need to correspond to the property name. Dexie can pick up databases created by other wrappers and still apply its schema even if they named the indexes arbritarily.

**Comment by FelixZY** [comment]
Got it, thank you for clarifying! Issue resolved IMO.
