### ISSUE TITLE
Dexie Cloud with Chrome Extension

### ISSUE THREAD

**Issue by lelouchB** [dexie/Dexie.js#1699]
I am trying to use Dexie Cloud with a Chrome Extension, but it seems to mess with the service worker from the Chrome extension. 

This is the error
```
Uncaught (in promise) DOMException: Failed to read the 'ready' property from 'ServiceWorkerContainer': 'ready' is only supported in pages.
```
This error occurs as soon as I import the following in db.js

```
import dexieCloud from "dexie-cloud-addon";
```

**Comment by dfahlander** [comment]
Hi! I know we used to have this problem in an earlier versions. Which version of dexie-cloud-addon are you using?

**Comment by dfahlander** [comment]
If you're on the latest version, the issue could also arise if having set self.document to something, or just declare a variable `document` globally, as we avoid calling swContainer.ready() if `self.document` is falsy.

**Comment by lelouchB** [comment]
Thank @dfahlander 
I am on earlier version, will update and try again
