### ISSUE TITLE
[feature request] Support async functions in `.modify()`

### ISSUE THREAD

**Issue by josephrocca** [dexie/Dexie.js#1703]
I had to do some extra hacking because the system that I'd built to upgrade database docs relied on `.modify()` and at some point I needed to add some async code as part of the update process. Unless I misunderstand, async functions aren't supported in `.modify()`, and it fails silently (i.e. doesn't modify the records, because it expects a sync function).

**Comment by dfahlander** [comment]
That's true. The callback is a syncronous callback. But it would embrace a coding style with bad performance code if we'd allow it. Better to just do the query (toArray), then modify the records and then bulkPut them back again. Note however that IndexedDB wont keep a transaction alive if your async call involves non-indexeddb calls.

**Comment by josephrocca** [comment]
I guess that's fair - I'm assuming the `modify` has a guaranteed order, and so you couldn't parallelize the async calls without introducing some unexpected inconsistencies. Thanks for your reply!
