### ISSUE TITLE
WebSocket/Cloud sync errors

### ISSUE THREAD

**Issue by naton** [dexie/Dexie.js#1708]
Not sure if this ie new, old, me or something temporary, but these have been starting to show up in my dev tools, both live and via localhost:

```
POST https://zyh2ho4s6.dexie.cloud/sync 500

Failed to sync client changes HttpError: 500 
    at index.0c75a52a.js:28:16686
    at Generator.next (<anonymous>)
    at s (index.0c75a52a.js:24:22083)
index.0c75a52a.js:32 error in syncIfPossible() HttpError: 500 
    at index.0c75a52a.js:28:16686
    at Generator.next (<anonymous>)
    at s (index.0c75a52a.js:24:22083)
```

**Comment by naton** [comment]
Could this be related to me having a list ID containing a dot (".")? (I invited the user `x@xxxxx.nu`, which produced a list ending in `.nu` whereas email adresses ending in `.org` does not produce lists with dots in their ID:s)

Then (related?) I get `substr` errors like this:

![image](https://user-images.githubusercontent.com/444538/235080840-a0dc58cd-309e-4905-82d4-85f0492dbf68.png)

**Comment by naton** [comment]
Any findings here..? I've tried deleting my local db but still get these sync issues. Current (failing) sync payload is 46 objects in changes array, I guess this empties out once the sync is successful..?

**Comment by dfahlander** [comment]
I found where in the code the issue happens yesterday but have not found a way to reproduce it yet. If it would be possible to repeat it, please have devtools open when repeating it and right click the failing request on devtools / Network tab, and choose copy as cURL and send to me in a private email or slack message. I just sent you an invitation on Slack.

**Comment by dfahlander** [comment]
This issue should have been solved for a couple of weeks ago. If not please reopen.
