### ISSUE TITLE
dexie cloud unable to whitelist tauri://localhost

### ISSUE THREAD

**Issue by tallenh** [dexie/Dexie.js#1710]
I wanted to try using dexie cloud and tauri together.  In dev mode, works so far, as the dev build loads from http://localhost.

The build version comes from tauri://localhost, so:

$ npx dexie-cloud whitelist tauri://localhost
Whitelisting tauri://localhost
Error: Given origin should be of the form: https://hostname, http://localhost:<port>, capacitor://..., ionic://..., chrome-extension://... or app:<App name>. Use the **--force** flag to skip this check and add a custom origin.

So I tried to use the --force flag:
$ npx dexie-cloud whitelist --force tauri://localhost
error: unknown option '--force'

Now it seems I am stuck.

**Comment by tallenh** [comment]
For background, tauri (https://tauri.app) is much like Capacitor.  Currently supports Mac, Windows and Linux and the 2.0 alpha adds support for IOS and Android.  Where a Capacitor app needs capacitor:// whitelisted, a tauri app needs tauri:// whitelisted.  Since the --force flag on whitelist appears to be broken, I cannot add tauri:// to my whitelist.

**Comment by dfahlander** [comment]
Sorry for late reply. dexie-cloud@1.1.5 is needed to whitelist with --force. It was not tagged "latest" until just now, my bad!
If you have installed the `dexie-cloud` package, please upgrade it to latest (dexe-cloud@1.1.5) and then re-execute the command:

```
npx dexie-cloud whitelist --force tauri://localhost
```

You can also try
```
npx dexie-cloud@latest whitelist --force tauri://localhost
```
