### ISSUE TITLE
Question:  How do you make the where clause typesafe?

### ISSUE THREAD

**Issue by ShravanSunder** [dexie/Dexie.js#1713]
i have a table `documentData: Dexie.Table<TDocumentData, number>;`
with type 
```

export type TDocumentData = {
	/**
	 * PK, this can be used as id! for queries.
	 */
	id: number;
	name: string;
	fileName: string;
	fullFilePath: string;
	fullLink: string;
	/**
	 * FK
	 */
	vectorId: number;
} & TRelationshipData;
```

I would like to make the where clause type safe?  it looks like where will take any string in `.where(xxx)`

```

const documents = await db.documentData.where('kjkjjk').anyOf(fullFilePaths).toArray();
```

where(index: string | string[]): WhereClause<T, TKey>;

I'd be happy to contribute code if you can provide some guidance @dfahlander 

would something like this work? or is there additional complexity with this?  `where(index: keyof T): WhereClause<T, TKey>;`

**Comment by dfahlander** [comment]
I'm closing it for now. Feel free to reopen.
