### ISSUE TITLE
issue with arrays and UpdateSpec type

### ISSUE THREAD

**Issue by twmillett** [dexie/Dexie.js#1714]
In ^4.0.1-alpha.10

```
interface WithArray {
  fielda: number[]
}

const err  : UpdateSpec<WithArray> = {
  fielda: [1]
}
```

gives a typescript error 

```
Type 'number[]' is not assignable to type 'void'.(2322)
input.tsx(30, 22): The expected type comes from property 'fielda' which is declared here on type 'UpdateSpec<WithArray>'
(property) fielda: number[]
```

It seems to be an issue with the final OR of this statement in KeyPaths<T>:

```
	  ? P | `${P}.${number}` | `${P}.${number}.${KeyPaths<T[P][number]>}` 
```

If I remove the final clause from that type definition, there's no error.

```
          // no error with this definition
	  ? P | `${P}.${number}` 
```

[Playground](https://www.typescriptlang.org/play?ssl=5&ssc=3&pln=5&pc=74#code/C4TwDgpgBA0hIAUCGwAWBnAPAFQHxQF4oBvAWACgBIAbQSgEsA7KAa3gHsAzKbAXQC4oFSpToQAHsAiMAJuijpgAJyYBzIVREB+HrV5QJU2fKSMQ1fcJFQoOugB8oAAwAkxBAF8AdG8YBXAFsAIwglDycoR1d3b19AkLCfYjhEFAwcPWp-YNDeXHCNGyKiwWw9A0lpOSgACi96pCVVdEFTc14ASkJ8NqgAej6oAFkINHYZYShrIp1GCAA3UI1p4tLywyr5diCAKwgAY2BC4pObO0jnN08klOQ0LDKEPIKKU9PBOleTwTnFpQBuCgeahsEBcHi8QHkCigSBQADK9ACYAANqFbmkHvgiGQqLQGMxQeC+IIrGJKsYFMo1MttLonhUjNU2hZaZQzlAHJcYklsgkXuQ3lA1gyNpS6g0mi0oCzOt0ZWZ+oMRmMJlQpuyZlBfksrO96foxdVtntDschRyudFrm4MfcMk98hEvhbhZzzSVtQtQlDgUTuHwoTDwNA7agAGpIFF+CA4AA0nIAgtgABLYpOpxmbblMThLABKsWIuaW8IKOnzWcp-p4tlg8DuEajMYy+d4Cfh+FKVeZZlZdmTKZ78mifNCRZLSgR5frqTQkejsbKY6U7YRXag83Y9Bkbq3O7dCEHw+5K5n2BPsrry-iuT3293H2PRvkNYvOkeg-0gn3MihsOgRFkTRJQwwXFtsATI9U3TaChxfHNGDzKdCySSdpwiCsTzfOsgNRdEGzScCl2oNsOw3C8EKvAdMwQ0db0SNx0LLTCESRfDQMI+dmxIlc107e8Dx-B9D2fClqnonIwlYyjxJMPt9A-LIGO-TcRKfWi5NYDgA2vWgv0Ev8KGDOEAFUwBkFAIHhSB9hwdNcRoGA6CYWdGyxXgtEEMCePjWAEFwX1-xDNjgNCczLKkGyDnswgSGEahnIJUKOLDDyvJSkCfMXPznMCoEg2hcgmCkJROCQfZoAAOXYRMlCUJAQHiwUoE4egIBRSyfgYuMvjajqZCCQRcWKfrOqCABGbqpK+DwgWM8h9nYRhFCgdgWDdCKrOiuyarqhqQAcvr2s6pBBAm3qWrGwbhpdVqTsGqaoAAJlm+aipK0JysqqAAHV6DQfbGuamxrrO7UGIsd6KCWlajlCKdNos7bbMwf7Afqxqjquh7weoCbeGhxbltWxh2ARmxBDwkCtqi1H0dQIHDrikb7oGvGCaBIA).

**Comment by twmillett** [comment]
Here's an attempt: [Playground](https://www.typescriptlang.org/play?ssl=14&ssc=12&pln=1&pc=1#code/C4TwDgpgBA0hIAUCGwAWBnAPAFQHxQF4oBvAWACgooBtBKASwDsoBreAewDMpsBdALigUAkMLoQAHsAiMAJuijpgAJyYBzIeVHCA-D1q8ok6XIUBBZcqQhMTThGWxcFKq9d6YRqTPlQAShAAxuzKsphKqoxqADRQSIwgzlqibnp0AD5QAAYAJMQIAL4AdHmMAK4AtgBGDgVZUJm5+cWllTXKLcRwiCgYmDC4dZpuI1CCGdl5hSXE5dW1WS6jY-oIhsY+CgAURbtIymrogvEg1LwAlIT4J1AA9LdQALIQaOyyIlAp7lCMEABuDk0XzcgmwBi8Jl87CqACsgsBhstUlAJk1pnlusg0FgwWtBvUlkiqONESCfv8HABuCgFahsEBcHi8ankCigSCweBY1AANSQABsyhAcLEEGZsAAJfBEMWSiGbSbEOyAvydZWOADKQz0fnlplYHG42CgHi5vT5guFYL8vFiGvwoL1vhOZxNKPFEqdCiac3aasY9k12s5PTQFqFOGovoctqg9pWf3Y9FkCaTKfGHq9iujHXqemNG31LsM+ajbRjqeTK1lnsLvnpjONpZrhkEieTLLZ4GgAFUwLIUBANZBAjhpSQRNQYHQmCHuTjcLwdIJMeaBRHsLFp7gWQVO+R2dB0OwKhAAPKwwgTyhQABESCQt8EOZpFAoTGkyk4SEC0AA6vQaAWFYIDXlQnD0BA-IDoIx6nheMJnK+rLkMEjBKFA7AsOgI6CH2A7SMOQSYABQGWNY45kDet4QVBA5FAAjEUD5PlADHIRQaEYVUSDyCOxJQPhg5EaOpGoMBFFXlRVA0ZB0FIIxRRVFUrHseQBQUEAA).

The addition is to restrict the final clause highlighted above to cases where the array element is an object:

```
type KeyPaths<T> = {
  [P in keyof T]: 
    P extends string 
      ? T[P] extends Array<infer K>
        ? K extends object // only drill into the array element if it's an object
          ? P | `${P}.${number}` | `${P}.${number}.${KeyPaths<K>}` 
          : P | `${P}.${number}`
        : T[P] extends (...args: any[]) => any // Method
           ? never 
          : T[P] extends object 
            ? P | `${P}.${KeyPaths<T[P]>}` 
            : P 
      : never;
}[keyof T];```

**Comment by dfahlander** [comment]
Thanks! Your suggestion seems to be correct. I'm adding a PR with it and some new typings tests.

**Comment by AndyVu2311** [comment]
issue still exist in 4.0.1-alpha.25 with table.update()
```
export interface WithArray{
  id?: number;
  array: string[];
}
const arr: WithArray = {
  array: ['foo','bob']
}
```
with `table.update(0, arr)` cause typescript error

```
Argument of type 'WithArray' is not assignable to parameter of type 'UpdateSpec<WithArray> | ((obj: WithArray, ctx: { value: any; primKey: IndexableType; }) => boolean | void)'.
  Type 'WithArray' is not assignable to type 'UpdateSpec<WithArray>'.
    Index signature for type '`array.${number}`' is missing in type 'WithArray'.(2345)
```

looking for workaround
