### ISSUE TITLE
`KeyPaths` and `TableProp` are not being exported from `dexie`

### ISSUE THREAD

**Issue by dtsamitros** [dexie/Dexie.js#1725]
https://github.com/dexie/Dexie.js/blob/552005de4f89cf0eb61c8195ae116cb1fd724919/libs/dexie-react-hooks/src/usePermissions.ts#L3

While using dexie-react-hooks the linter caught an import error, eg. 

![image](https://github.com/dexie/Dexie.js/assets/13154981/2f7fb4da-bc59-40bb-822a-31945be4aeab)

It seems `KeyPaths` and `TableProp` are not being exported from `dexie`

**Comment by dfahlander** [comment]
Thanks for the report. Are you using dexie 3 or dexie 4?

**Comment by dfahlander** [comment]
Fixed in dexie-react-hooks@1.1.4. Please help me verify this is fixed or else reopen the issue. Thanks!

**Comment by dtsamitros** [comment]
> Fixed in dexie-react-hooks@1.1.4. Please help me verify this is fixed or else reopen the issue. Thanks!

Yes, it is now fixed. Thank you for your efforts!
