### ISSUE TITLE
Exporting databases that are over the maximum string length allowed by the browser

### ISSUE THREAD

**Issue by josephrocca** [dexie/Dexie.js#1726]
Here's some example code:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/dexie/3.2.3/dexie.min.js"></script>
<script src="https://unpkg.com/dexie-export-import@4.0.7/dist/dexie-export-import.js"></script>

<script type="module">
  // drop existing database:
  Dexie.delete("test");
  // create database
  const db = new Dexie("test");
  db.version(1).stores({
    dummy: "++id, name, age"
  });
  // add dummy data
  for(let i = 0; i < 1000; i++) {
    await db.dummy.add({ name:"John Doe".repeat(100000), age:30 });
  }
  // export the db
  let blob = await db.export({ prettyJson:true });
  let text = await blob.text();
  console.log(Math.round(text.length/(1024*1024)) + " MB");
  let json = JSON.parse(text);
  console.log(json);
</script>
```
This errors with "Invalid string length" at `db.export` in Chrome, specifically on line 146 of `export.ts`:

![image](https://github.com/dexie/Dexie.js/assets/1167575/45c6de38-0b51-4d61-8f72-850cf568821c)

You can remove a zero from `"John Doe".repeat(100000)` to check that it works fine if we're under the string length threshold, of course.

In Chrome, at least, the string length limit is around 500mb. I'm wondering what the general approach should be for exporting/importing databases that can be significantly larger than this?

My particular use case is [OpenCharacters](https://github.com/josephrocca/OpenCharacters), where it turns out that it's quite easy to go over 500mb given that the user may end up storing thousands of vector embeddings, which each have ~1500 floating point elements - this can obviously take up quite a bit of space in string form.

**Question**: Is there perhaps some way to export in a non-string form, or some other way around this?

**Comment by josephrocca** [comment]
Also, there's a seemingly related error that I've not yet been able to create a minimal reproduction for - basically where the blob is about 500MB, but when I call `await blob.text()` it returns an empty string. In the above replication I wasn't able to produce that type of failure, so I'm not too sure what's going on there, but it seems likely related to string length limits.

**Comment by josephrocca** [comment]
Hey @dfahlander, apologies for the ping - just wondering if you have any idea how solvable this is, or ways to work around it in the meantime?

**Comment by dfahlander** [comment]
Check if decreasing numRowsPerChunk option to a lower value helps. The default is 2000 and if each row is very large, it might have to be chunked to a lower value such as 100.

**Comment by josephrocca** [comment]
Ah, thank you! Might be worth catching this ([here](https://github.com/dexie/Dexie.js/blob/bf9004b26228e43de74f7c1fa7dd60bc9d785e8d/addons/dexie-export-import/src/export.ts#L146)) and throwing a more helpful error message than "Invalid string length".

Thanks again! :pray: 

(Just in case others reach this issue via Google: note that there's a Chromium bug which was causing the empty string bug that I referred to in [my second comment](https://github.com/dexie/Dexie.js/issues/1726#issuecomment-1567685512). Here's the bug report for reference: https://bugs.chromium.org/p/chromium/issues/detail?id=1453496)

**Comment by dfahlander** [comment]
I'm happy this turned out to fix the issue for you! Yes, it would be a good advice to catch that error and propose user to use a lower numRowsPerChunk when it happens. I'll change that.
