### ISSUE TITLE
useLiveQuery returns undefined on initial render

### ISSUE THREAD

**Issue by hubertdej** [dexie/Dexie.js#1732]
After upgrading dexie from version 3.2.3 to 3.2.4, when `useLiveQuery` is called with the `defaultResult` set, it returns `undefined` during the initial render. I suspect this issue might be related to the assignment of `currentValue` as `undefined` here:
https://github.com/dexie/Dexie.js/blob/a3e1689ac2ab6edc612ef5a80933d265c9215409/src/live-query/live-query.ts#L35
and potentially overriding the default result of `useObservable` here:
https://github.com/dexie/Dexie.js/blob/a3e1689ac2ab6edc612ef5a80933d265c9215409/libs/dexie-react-hooks/src/useObservable.ts#L80-L81

**Comment by dfahlander** [comment]
Thanks. Please try with dexie-react-hooks@1.1.5. The issue was mainly that useObservable was trying getValue before hasValue. Should be fixed now.

**Comment by Thorvarium** [comment]
Hey @dfahlander , I am on version 1.1.7 and dexie 4.0.4 and it is returning undefined here even after setting the default parameter
![image](https://github.com/dexie/Dexie.js/assets/6555325/461cecde-f6d9-413f-b68c-ef4e8717899f)
