### ISSUE TITLE
Optimistic cache not purged on database deletion

### ISSUE THREAD

**Issue by dfahlander** [dexie/Dexie.js#1736]
If components are live-querying data and an action does Dexie.delete(database) or db.delete(), the optimistic cache isn't wiped out.

See https://github.com/dexie/Dexie.js/issues/1689#issuecomment-1584405386

**Comment by b-straub** [comment]
Any news on this?

**Comment by dfahlander** [comment]
The solution does wipe the cache on reopen. Ongoing live queries will not be triggered at the time of database deletion, but rather at the time when a database has been created. In case a database is deleted and then recreated, the cache will be wiped out on successful open and the ongoing queries will be retriggered.

A deletion without reopening the database will leave ongoing live queries as they are. If they are retriggered for another reason (state update in app etc), they might auto-open the database and get the results from a recreated database.

If app code wants to delete database and force it to not reopen automatically, application code must do both db.close() and db.delete().
