### ISSUE TITLE
How could the loaded objects keep mutable?

### ISSUE THREAD

**Issue by rayzhao99** [dexie/Dexie.js#1739]
Our codes will modify/update the loaded objects in memory, since we implement our own cache mechanism before dexie provides a cache in the latest release. After updated to the latest, errors are thrown when our codes try to modify the objects. It seems due to dexie changes the objects to immutable. 

According to the release notes, 
>`A new constructor option to Dexie is {cache: 'immutable' | 'cloned' | 'disabled'}`

However, even the `cache` is set `'disabled'`，the loaded objects seem to be immutable still. How could we disable this, so the objects can be kept as-is after loaded? This might not be an uncommon problem for the legacy codes.

The `'cloned'` option is not appropriate yet, since it costs unnecessarily.

**Comment by dfahlander** [comment]
Thanks for the report. I'm my tests, both 'cloned' and 'disabled' allow mutation of returned objects, but obviously some change in the latest version has something that breaks it for you. Are you using dexie@4.0.1-alpha.19? (There were a few issues in alpha.17 and a new release note is on its way) Would it be possible to either create a repro in for example jsitor.com or so to pinpoint where it actually breaks?

**Comment by rayzhao99** [comment]
Yes, you're right. We create a dedicated project, in which objects loaded with `'cloned'` & `'disabled'` are mutable. So there should be problems in our own codes.
