### ISSUE TITLE
Error detail link to bitly has been blocked

### ISSUE THREAD

**Issue by cha0sCat** [dexie/Dexie.js#1745]
The error details link to bitly is blocked by bitly.

Here's an example:
http://bit.ly/2kdckMn
```
Failed: Transaction committed too early. See http://bit.ly/2kdckMn
```

https://github.com/dexie/Dexie.js/blob/7a15d4f50f0cfe288a96a96854e7241a1d955bb4/src/classes/dexie/transaction-helpers.ts#L98

**Comment by dfahlander** [comment]
ok thanks! That's strange but I'll see if they could unblock these links or I'll have to move to another short url service

**Comment by dfahlander** [comment]
The URL it was supposed to link to is this: https://dexie.org/docs/DexieErrors/Dexie.PrematureCommitError

I've requested unblocking of the URL from bit.ly.
