### ISSUE TITLE
Table.update() performance problem

### ISSUE THREAD

**Issue by NoraH1to** [dexie/Dexie.js#1758]
**Ver `3.2.3`**

I have a table structure like the following, which I use to store some books and their reading progress:

```typescript
type BookTable = Table<{
  file: File;
  cover: Blob;
  readProgress: {
    value: string;
    percent: number;
  }
}>
```

But when I use `bookTable.update(key, { readProgress })` to update only the reading progress.

I notice that the disk is writing like crazy, and I guess it re-writes other fields like `file` and `cover` at the same time as updating `readProgress`.

Here is my code snippet:

```typescript
async updateBook({ hash, info }) {
  return db.transaction('rw', db.books, async () => {
    const code = await db.books.update(hash, info);
    if (code === 0) throw new Error(`Update book fail, book ${hash} unexist`);
  });
}

// And I called it like this
updateBook({ hash: 'any', info: { readProgress } });
```

Is this a bug? Or maybe it's a feature of this library?

**Comment by dfahlander** [comment]
That is down to the implementation of IndexedDB in the browser. Dexie 's update uses IDBObjectStore.put() under the hood. According to the IndexedDB spec, the object being put is cloned before being stored in the db. However, implementations should not need to clone blobs as they are immutable, and I don't think the structuredCloning specification requires copying blob contents. It surprises me a bit that this seems to be the case of you experience lots of disk writes when just updating the non-blob values. It may differ depending on which browser you use - some may optimize this and some not.

A doable workaround would be to store the blobs in a different table and refer to the id of the stored content (like a foreign key)

**Comment by NoraH1to** [comment]
Thanks for your reply!

> It may differ depending on which browser you use - some may optimize this and some not.

I just tested it on the latest versions of `safari (VMware macOS13)`, `firefox (Windows11)`, `edge (Windows11)` and they all behave like this, it's crazy...

> A doable workaround would be to store the blobs in a different table and refer to the id of the stored content (like a foreign key)

I think this is the best solution now.

I will close this issue, thanks again😊
