### ISSUE TITLE
Have any recommended length of string of index ?

### ISSUE THREAD

**Issue by MJRT** [dexie/Dexie.js#1769]
Hi, I'm reading docs and found a [wanring](https://dexie.org/docs/Version/Version.stores()#warning) :
> Never index properties containing images, movies or large (huge) strings. Store them in IndexedDB, yes! but just don’t index them!

So, I would like to know how long is the max setting so that it's not affecting user experience? Is 200-500 `words` acceptable?

**Comment by dfahlander** [comment]
When you say `words`, do you mean a string containing several words, a multiIndexed array of strings or double-bytes?

**Comment by dfahlander** [comment]
Can you give an example on how you plan to use the index (av example where-query)

**Comment by dfahlander** [comment]
You should probably use a [MultiEntry](https://dexie.org/docs/MultiEntry-Index) index - an array property where you store all the words to be searchable (you can omit duplicates). If you'd just index the whole summary as a single string, you'd only be able to search for the exact same summary or the start of it. With multiIndexed arrays you can get a match of any of the containing words or the start of any word.

**Comment by MJRT** [comment]
Good idea! I'll try it. By the way, Does MultiEntry index have similar limitations? Such as the length of array?

**Comment by dfahlander** [comment]
No there's practically not a limit but of course the more items you have in the array, the slower writes and updates of those entries. I suppose a summary of 500 words would not be a problem. Just a bit slower to add the entry and to update it when having many words. It's not the same as a large binary blob. Many people index entire images or even movies and experience instable behavior when every index can be megabytes of data. With MultiEntry, each index is short and it's less of a problem having many short indexes than having one extremely large one.
