### ISSUE TITLE
Two objects are added when I'm trying to add one

### ISSUE THREAD

**Issue by garcialo** [dexie/Dexie.js#1773]
I have a Dexie db with several tables and to add a new "Audit" within my app I'm adding a few defaults objects to multiple tables. But the .add()s are seemingly run twice, so I end up with two new Audits.

```
async function addAudit(checklist_ID: number) {
	try {
		const page_state_ID = await db.page_states.add({
			name: "Initial",
		});

		const page_state_ID_number = Number(page_state_ID);
		const page_state = await db.page_states.get(page_state_ID_number);

		const page_ID = await db.pages.add({
			name: "Untitled Page",
			page_state_IDs: [page_state_ID_number],
			url: "example.com",
		});
		... more .add()s
```
...and the function is called by...

`if (given_checklist_ID) addAudit(given_checklist_ID);`

I'm new to Dexie and still relatively new to React/TypeScript, so I suspect I'm just overlooking something pretty straightforward.

**Comment by dfahlander** [comment]
It's impossible to find the issue without the rest of the code. Please create an online repro of the issue on jsitor, codesandbox or similar and post the link to a stackoverflow, tagging it dexie.
