### ISSUE TITLE
Error: Unable to delete database because it's blocked

### ISSUE THREAD

**Issue by aparzi** [dexie/Dexie.js#1779]
When I try to delete a database I get this error: **Unable to delete database because it's blocked**
I open connection in indexeddb both in the webworker and in the main thread. Can you tell me the problem?

Thanks

**Comment by dfahlander** [comment]
The problem you describe indicates that there is an active connection to the database that is preventing the deletion. Dexie.js uses IndexedDB as the underlying database, and IndexedDB has certain restrictions on deleting databases when there are open connections.

Active Connections: You mentioned that you have opened connections in both the web worker and the main thread. If any of these connections are still active when you try to delete the database, the operation will be blocked.

IndexedDB has a generic way to handle this situation - the [blocked](https://dexie.org/docs/Dexie/Dexie.on.blocked) event. By default, Dexie will listen to this event and release its connection when this happens, so the situation normally don't occur if you are using Dexie.js only and not another wrapper, or if you listen to the [blocked](https://dexie.org/docs/Dexie/Dexie.on.blocked) and provide your custom implementation that does not close the connection. Another reason could be if devtools keeps the connection open for some reason.

**Comment by aparzi** [comment]
Hi @dfahlander, I sure devtools not keeps the connection open. In my project I use Dexie and API native (in worker) of Indexeddb for DB management.
Can I force close all connection or you suggest me another solution? 

Thanks.

**Comment by dfahlander** [comment]
If there's another piece of code having your database open - you can't force close it programmatically from your app. But if you can control the code that keeps an indexeddb connection open - be it some non-dexie code doing this - make sure to listen to the [versionchange event and close the native indexedDB connection](https://dev.to/ivandotv/handling-indexeddb-upgrade-version-conflict-368a). This situation is rare when using Dexie.js only for indexedDB because it already does listen to versionchange [by default and close its connection](https://dexie.org/docs/Dexie/Dexie.on.versionchange), but there might be other tools you are using that keeps the same db open. makes sure to automatically release its connection when another peer needs to perform an upgrade or deletion.

**Comment by aparzi** [comment]
Hi @dfahlander,
thanks for the suggestion.
Another question. is it possible to use Dexie.js within webworkers?

**Comment by dfahlander** [comment]
> Hi @dfahlander, thanks for the suggestion. Another question. is it possible to use Dexie.js within webworkers?
Yes

**Comment by aparzi** [comment]
Hi @dfahlander,
can you share an example? Thanks.

**Comment by dfahlander** [comment]
## With build step (recommended)
If you build your worker from webpack or similar, just code the same way as you'd do on web:

Declare your db module:

```js
// db.js (or db.ts)
import Dexie from "dexie";
export const db = new Dexie("mydb");
db.version(1).stores({
  myTable: 'id'
});
```

Then from your main file:

```js
import { db } from './db';

db.table1.put({id: 1, foo: "bar"})
  .then(()=> console.log("Successfully put object into indexeddb");
  .catch(err => console.error(`Could not put object into indexeddb ${err}`);
```

If you use vanilla JS, your worker can be legacy or module:

## Vanilla JS, module worker:

* Make sure dexie.mjs is downloaded
* import Dexie from "./path-to-downloaded-dexie.mjs"

```js
import Dexie from "./path-to-downloaded-dexie.mjs";

const db = new Dexie("myDB");
db.version(1).stores({
  myTable: 'id'
});
```


## Vanilla JS legacy worker:

```js
importScripts ("./path-to-downloaded-dexie.js");

const db = new Dexie("myDB");
db.version(1).stores({
  myTable: 'id'
});
```


## Observing changes from tabs / browser windows

You can also use Dexie as a persistent communication channel between workers and browser windows using [liveQuery()](https://dexie.org/docs/liveQuery()). Let's say your worker logs things to a table and you want to make that visible in frontend app, you can do liveQuery of the data you need to observe and display it in frontend. Whenever the worker writes something to dexie, frontend'd liveQuery will react to the new values written.

**Comment by aparzi** [comment]
Thanks @dfahlander fantastic.
I will be using Dexie.js in the workers. Though I understood that even Dexie.js doesn't guarantee 100% that during deletion the db is locked. Right?

**Comment by dfahlander** [comment]
deletion and upgrading both generates an upgradeneeded event to other peers with a connection open. None of them can complete without every connection reacting to upgradeneeded and closing it's db instance. Dexie does this by default but it's overridable.

**Comment by aparzi** [comment]
@dfahlander thanks for all.
