### ISSUE TITLE
Failed to execute 'createObjectStore' on 'IDBDatabase': The keyPath option is not a valid key path.

### ISSUE THREAD

**Issue by secondl1ght** [dexie/Dexie.js#1781]
Hello there,

I am building an application with Dexie for the first time and I ran into this error when trying to use `bulkAdd`. I tried looking into the docs for information on the error `message` (the issue title) and `name`: `DatabaseClosedError`, but I didn't see anything that applied to my code so far. I am wondering if maybe I am trying to store some data types that are not supported by IndexedDB? Here is a list of the data types I am storing within my table:

- string
- Uint8Array
- ArrayBuffer
- number
- boolean
- array of objects

Please let me know what you think about this or if there are other debugging methods you suggest trying.

Thanks for the great project

**Comment by secondl1ght** [comment]
NOTE: I checked the Application tab in DevTools and noticed there is no database initiated, so this could be the root of the issue and not the data types. I am following this tutorial https://dexie.org/docs/Tutorial/Svelte using SvelteKit to setup my Dexie DB. I added the `db.ts` file (using TypeScript) as shown there.

**Comment by secondl1ght** [comment]
Update: I have tried explicitly calling the `db.open()` method to ensure that the database is opened but I still receive the same `DatabaseClosedError` with nothing showing up in `IndexedDB`. I am not sure what I am doing differently from the tutorial to receive these errors...

**Comment by secondl1ght** [comment]
I even tried using `await` on `db.open()` and the Promise resolves successfully but still it looks like no DB is opened and the error is thrown?

**Comment by secondl1ght** [comment]
If this helps to debug here is a code snippet of my `db.ts` file:

```js
export class MySubClassedDexie extends Dexie {
	conversations!: Table<Conversation>;

	constructor() {
		super('MyDB');
		this.version(1).stores({
			conversations: '&pubkey blocked' // Primary key and indexed props
		});
	}
}

export const db = new MySubClassedDexie();
```

**Comment by dfahlander** [comment]
Ok there's a space in the primary key "pubkey blocked". Haven't seen that before and i don't remember if that is valid in IndexedDB. Try with "pubkeyBlocked" or if blocked was meant to be a secondary index, "pubkey, blocked"

**Comment by secondl1ght** [comment]
Ah thanks a lot, I totally missed the `,` that is required. I was trying to set `pubkey` as the primary and `blocked` as another key. Sometimes it's the little things that take the longest to notice... It's working now. :)

**Comment by dfahlander** [comment]
> Ah thanks a lot, I totally missed the `,` that is required. I was trying to set `pubkey` as the primary and `blocked` as another key. Sometimes it's the little things that take the longest to notice... It's working now. :)

Great to hear that it was the issue! Logging error.inner on the catched DatabaseClosedError would have revealed 'SyntaxError: Failed to execute 'createObjectStore' on 'IDBDatabase': The keyPath option is not a valid key path.'.

This reminds me that there might have been a good idea to let DatabaseClosedError.prototype.toString() reveal also the message from the inner exception.
