### ISSUE TITLE
useLiveQuery not re-rendering React Component

### ISSUE THREAD

**Issue by TravisBumgarner** [dexie/Dexie.js#1782]
I've got a very simple todo list and I've simplified the code here as much as possible. I've got a TodoList and a TodoListItem, referenced below.

The flow of importance:
1. Use `useLiveQuery` to get `selectedDateTodoListItems` 
2. Pass data to `TodoListItem`
3. Click button in `TodoListItem`, triggering `handleStatusChange` to update IndexedDB.

What I expect to happen next - `useLiveQuery` triggers a new `selectedDateTodoListItems` and `TodoListItem` rerenders.

What actually happens - Nothing.

If I trigger a change elsewhere in the app that causes `state.selectedDate` to change, `useLiveQuery` will be called again and the data will update. I thought `useLiveQuery` would be responsible for watching all other changes in IndexedDB, and update the UI accordingly but that doesn't seem to be happening here. 

TodoList:
```typescript
const TodoList = () => {
  const { state } = useContext(context)

  const selectedDateTodoListItems = useLiveQuery(
    async () => {
      const items = await database.todoListItems.where('todoListDate').equals(state.selectedDate).toArray()

      return await Promise.all(items.map(async ({ id, projectId, taskId, details }) => {
        const task = await database.tasks.where('id').equals(taskId).first() as TTask

        return {
          taskStatus: task?.status,
          taskId
        }
      }))
    }, [state.selectedDate]
  )

  if (!selectedDateTodoListItems) {
    return <p>Not found</p>
  }

  return (
    <div>
      {selectedDateTodoListItems.map((details) => (
        <TodoListItem
          key={details.taskId}
          {...details}
        />
      ))}
    </div>
  )
}
```

TodoListItem
```typescript
const TodoListItem = ({ taskId, taskStatus }: TodoListItemProps) => {
  const handleStatusChange = async (
    event: MouseEvent<HTMLElement>,
    value: ETaskStatus | null
  ) => {
    await database.tasks.where('id').equals(taskId).modify({ status: value })
  }

  return (
    <ToggleButtonGroup
      value={taskStatus}
      exclusive
      onChange={handleStatusChange}
    >
      <ToggleButton value={ETaskStatus.NEW}>
        <Tooltip title="Pending">
          <PendingIcon />
        </Tooltip>
      </ToggleButton>
      <ToggleButton value={ETaskStatus.IN_PROGRESS}>
        <Tooltip title="In Progress">
          <PsychologyIcon />
        </Tooltip>
      </ToggleButton>
    </ToggleButtonGroup>
  )
}
```

**Comment by dfahlander** [comment]
Please create a repro in [codesandbox](https://codesandbox.io) and I'll debug it.

**Comment by TravisBumgarner** [comment]
Hi @dfahlander Sorry for the delay.

Here's a codesandbox: https://codesandbox.io/p/github/TravisBumgarner/dexie-demo/draft/musing-wave?file=/webpack.js:42,16&workspaceId=6f97a8a1-ec88-44e7-9861-afe1a7dd6897

And a quick recording of what's going on:
https://github.com/dexie/Dexie.js/assets/11890057/777d2825-223b-4a75-b146-d9e6cbeb3ce7

**Comment by dfahlander** [comment]
Thanks for the nice recording! <3 I can't open the sandbox link though. Could you change its access to public (or allow access for david.fahlander@gmail.com)?

**Comment by TravisBumgarner** [comment]
Whoops sorry about that! 

I just tried thre share feature, which generates this link:
https://codesandbox.io/p/github/TravisBumgarner/dexie-demo/draft/musing-wave?file=%2Fwebpack.js%3A42%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cllpsdhjy000h3b6d6cemz3cj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cllpsdhjy000c3b6dns90m71b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cllpsdhjy000g3b6dx32jjtow%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cllpsdhjy000e3b6dclx2pf8e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cllpsdhjy000c3b6dns90m71b%2522%253A%257B%2522id%2522%253A%2522cllpsdhjy000c3b6dns90m71b%2522%252C%2522activeTabId%2522%253A%2522cllpsg5cu022n3b6dytv8n8q4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cllpsdhjx000b3b6dd8l6eqem%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cllpse5lb01np3b6da3nl5kic%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fwebpack.js%2522%252C%2522id%2522%253A%2522cllpsg5cu022n3b6dytv8n8q4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cllpsdhjy000e3b6dclx2pf8e%2522%253A%257B%2522id%2522%253A%2522cllpsdhjy000e3b6dclx2pf8e%2522%252C%2522activeTabId%2522%253A%2522cllpsdtie011c3b6d6yt2417t%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cllpsdtie011c3b6d6yt2417t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cllpsdhjy000g3b6dx32jjtow%2522%253A%257B%2522id%2522%253A%2522cllpsdhjy000g3b6dx32jjtow%2522%252C%2522activeTabId%2522%253A%2522cllpsdqzo00q43b6d71f9xggz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cllpsdhjy000f3b6dtyrzdlav%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cllpsdhuf000id7hu5noy0ik7%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cllpsdqzo00q43b6d71f9xggz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

But It's giving me errors when I try to access that link myself. 

If it works for you, I also have the repo here:
https://github.com/TravisBumgarner/dexie-demo

With setup instructions.

**Comment by TravisBumgarner** [comment]
Thank yo so much!
