### ISSUE TITLE
Is it possible to use Dexie inside a Service Worker?

### ISSUE THREAD

**Issue by secondl1ght** [dexie/Dexie.js#1791]
I have read that using Service Workers can help make a web app more like a native app by being able to run processes even when the app is not visible. So my use-case would be to setup a Subscription to a server that adds new records to Dexie when they are received. Using a SW for this doesn't sound like a requirement for my app but something that may be nice to have, so I would like to know if this is even possible. Thanks!

**Comment by dfahlander** [comment]
You can use dexie from within a service worker. However, you can't receive background push notifications from a service worker without also notifying the user visually. You can't either setup a web socket from a service worker. What you can do is to register periodic sync (supported in chromium browsers only still) that may execute some times a day if the user keeps using your app now and then (the browser decides whether the user seem to use your app). The service worker can then pull a server for new data and store them in dexie.
