### ISSUE TITLE
indexedDB存储报告异常

### ISSUE THREAD

**Issue by yichenw7** [dexie/Dexie.js#1793]
_e: Error at gr(https://............)
name: AbortError,
message: QuotaExceededError An ettemp was made to add something to storage that wxceeded the quota
inner: DOMException: An ettemp was made to add something to storage that wxceeded the quota

**Comment by dfahlander** [comment]
https://dexie.org/docs/DexieErrors/Dexie.QuotaExceededError

**Comment by yichenw7** [comment]
How to modify the storage disk of indexDB?

**Comment by dfahlander** [comment]
If quota exceeded, it means that the client has too little space. Client need to increase storage space or clear storage in browser. Using StorageManager it is also possible to read the numbers of available space on client storage. Examples are in the link provided in one of my recent comments.
