### ISSUE TITLE
typescript error on 4.0.1-alpha.25

### ISSUE THREAD

**Issue by j-5-s** [dexie/Dexie.js#1802]
First want to say that Dexie cloud looks really great and am excited to use it.  I am running into a typescript error that I cant figure out what am doing wrong:

```
Unsafe member access .add on an `any` value.
```

![Screen Shot 2023-09-23 at 7 49 51 AM](https://github.com/dexie/Dexie.js/assets/666455/f42fb37c-6acb-4a61-af8d-1161d9bff049)

I've created a repo and simple example [here](https://github.com/j-5-s/dexie-example-ts/blob/main/src/db.ts)

**Comment by dfahlander** [comment]
Thanks for the repro - I love when issues have it!

I cloned, did npm install and then opened it in vscode. However, I could not reproduce the issue so maybe you'd need to clear your .next/cache or node_modules and redo npm install.

What I get however, is eslint compaining about not taking care of the promise returned from db.contacts.add():

<img width="686" alt="image" src="https://github.com/dexie/Dexie.js/assets/6791329/34b7fc9f-c4e8-4ccd-95c2-e7c8abea3f7e">

But everything is fine after doing that:

<img width="483" alt="image" src="https://github.com/dexie/Dexie.js/assets/6791329/bcff4f12-7ee6-44d7-b3c7-ff954aa74a41">

Building goes fine as well:

<img width="891" alt="image" src="https://github.com/dexie/Dexie.js/assets/6791329/fd7ef421-c833-40a3-bced-fa436670f3e7">

**Comment by j-5-s** [comment]
Thanks for the quick response! So clearing node_modules and .next/cache as well as restarting vscode seems to have fixed it!
