### ISSUE TITLE
Ability to by pass events.

### ISSUE THREAD

**Issue by muratbeser** [dexie/Dexie.js#1804]
as I see it there no ability to disable events for particular mutation method calls. it would be great option. other wise we have to remove and recreate hooks.

**Comment by dfahlander** [comment]
Does this question regard to liveQuery or [crud hooks](https://dexie.org/docs/Table/Table.hook('creating')#see-also)?

**Comment by muratbeser** [comment]
hi yes crud hooks, I went over source code also in example.
x.add(..., byPassHooks=boolean | string | string[])

boolean: disable all hooks
string | string: disable particular hooks

when I look into syncable package and observable they access private variables which I consider internal API.  

(I write this in hurry, sorry if its confusing.

**Comment by dfahlander** [comment]
There are no plans to do that kind of changes in the API. A hook listener, or a [middleware](https://dexie.org/docs/Dexie/Dexie.use()) can inspect the triggered data and do conditional filtering the way the user prefers.

**Comment by muratbeser** [comment]
if I do a pull request would you merge it ?

**Comment by dfahlander** [comment]
I do not see the reason for the change, thanks anyway.
