### ISSUE TITLE
Detect change from cloud db

### ISSUE THREAD

**Issue by albarin** [dexie/Dexie.js#1812]
I have a doubt, in Dexie Cloud, is there a way to detect a change from the cloud DB in a table? And how?

Let me explain a bit my case, I have an app with a `days` table, if I open the app in two browsers and insert a `day` in one of them, it gets synchronized and shows up in the second browser, that's fine. But I want to detect that synchronization event in the second browser and react to it. How can I do it?

Sorry if this is documented, I have tried to find a solution, but I haven't managed to. Any help is greatly appreciated, thanks a lot! 🙏

**Comment by dfahlander** [comment]
Your welcome! [Sync state](https://dexie.org/cloud/docs/SyncState) can be observed using `db.cloud.syncState` documented in [dexie-cloud-addon#properties](https://dexie.org/cloud/docs/dexie-cloud-addon#properties).

```ts
const subscription = db.cloud.syncState.subscribe(state => {
  console.log(`Sync phase is now ${state.phase}`);
});
```
The observable can also be treated as a Svelte Readable Store
```svelte
<script>
  import { db } from "../stores/db.js";

  let syncStatus = db.cloud.syncStatus;
</script>

<div>
  <p>Sync Status: {$syncStatus.status}</p>
  <p>Sync phase: {$syncStatus.phase}</p>
</div>
```

Would any of these things solve the use case you have, or would you expect? I'm open for any idea that can improve your experience with Dexie Cloud!

**Comment by dfahlander** [comment]
There's also the event `db.cloud.events.syncComplete` which will only trigger after a successful sync request has completed. It does not provide any data but will never fire more for any other reason than a complete sync request.

However, if the purpose is to update the view when data changes, I would recommend to use liveQuery() and render its results using Svelte's `$` syntax. That will make sure that the view mirrors what is in the database at all times, no matter if it was updated locally or from another open tab, or from another device and got synced over dexie cloud.

If only listening for syncComplete, the view would not get updated when changed locally or from another browser tab. Code will also be less imperative and more declarative if sticking to liveQuery and render its result. If you have helper methods or functions to query dexie, you wouldn't need to change them - you can call your helper method from within a liveQuery and it will magically observe the results.

**Comment by albarin** [comment]
Thanks for you reply! I'm using `liveQuery` to show data, which is working perfectly fine when updating from another browser tab 👌 But then I want to run a function after any change happens in the first table (`days`).

I have tried:
```javascript
db.cloud.syncState.subscribe(state => {
    console.log(`TEST2: Sync phase is now ${state.phase}`);
});
```
and also:

```javascript
db.cloud.events.syncComplete.subscribe(() => {
    console.log('TEST1: Sync complete, refreshing cycles');
});
```
They do seem to work when a new row is created on the same browser, but they never trigger when is created from another browser tab.

As you can see here👇 only, those 2 `console.log` messages only appear in the browser where the actual action happens, not in the other one, even thought the data is synchronized.

https://github.com/dexie/Dexie.js/assets/186112/951e650f-ebae-41c7-89e9-01ef1f8409ce

Thank you!!!

**Comment by dfahlander** [comment]
Ok, thanks for the repro! These two events uses a BroadcastChannel to communicate across tabs, but there might be some issue with that implementation. The intent is that the state should be synced across all tabs no matter if there's a service worker performing the actual sync or if the service worker is disabled and the sync happens in one of the tab windows. Now that I have a repro this should probably be easy to find and fix. Thanks!

**Comment by albarin** [comment]
Hey @dfahlander, was there any progress in fixing this issue? Thanks!

**Comment by dfahlander** [comment]
Thanks for the reminder. I'll be able to look into it on monday.

**Comment by dfahlander** [comment]
Ah, these 2 clients seem to run in different profiles that don't share the same local database. The first one will actively push its changes and update the sync status while doing that while the other one will be notified with the changes over web socket and make sure to reflect its local database with the new state of the server database. There is no sync request performed from the other client because it gets the changes served over web socket. That is also the reason why the sync state isn't updated on the second client - it never goes into a sync flow. If these two clients would have been 2 windows from the same browser and profile, they would reflect immediately the changes and they would both reflect the changes in sync state as they represent a single client.

So the question is what you want to achieve by listening to these events? Can you describe what you want to do when a sync has been completed or when the sync status changes?

**Comment by dfahlander** [comment]
Closing for now, feel free to reopen.
