### ISSUE TITLE
CLI Request failing with 500

### ISSUE THREAD

**Issue by albarin** [dexie/Dexie.js#1816]
I'm getting errors on most of the commands I try to run with the `dexie-cloud` CLI (whitelist, delete, etc.):

```500:Internal Server Error Cannot read properties of undefined (reading 'userType')
Request failed with status code 500
```
Am I doing something wrong? Missing something maybe? I'm able to create a db but nothing else.

Thank you 🙏

**Comment by dfahlander** [comment]
The issue should be solved now. Please let me know if you still having problems
