### ISSUE TITLE
Dexie 4 optimistic updates are not reverted

### ISSUE THREAD

**Issue by m1st1ck** [dexie/Dexie.js#1823]
"dexie": "4.0.1-beta.1",
"dexie-cloud-addon": "4.0.1-beta.52",
"dexie-react-hooks": "^1.1.7",

When I add/bulkAdd item with a key that already exists, as expected, optimistic update triggers liveQuery with the new value and I also get error: `message: "Key already exists in the object store.\n ConstraintError: Key already exists in the object store."`. However liveQuery is never triggered with reverted optimistic update.

```js
liveQuery(() => db.items.toArray()).subscribe({
  next: (items) => {
    console.log({ items });
  },
  error: (error) => console.error(error),
});
```

```js
db.items
  .add({
    uid: "test",
  })
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  });
```

**Comment by dfahlander** [comment]
Thanks! I could reproduce it. Created a PR #1824 (in progress)

**Comment by dfahlander** [comment]
Failing transactions revert correctly but catched add/delete/put operations within a transaction were not reverted. The code was there to revert them but failed to interpret the promise from DBCore correctly. This is fixed now and there will be a new version out with it soon.
