### ISSUE TITLE
Write buffer is failing for large size

### ISSUE THREAD

**Issue by balasaravanan02** [dexie/Dexie.js#1827]
I am trying to store parquet file data as buffer in indexeddb, but is failing with no error logged 
the file size is around 430mb

`"dexie": "^3.2.4",
`

```
  const db = new Dexie('duckDB');

  db.version(1).stores({ datasets: 'token,data' });

  const writeStart = performance.now();

  db.table('datasets').put({
    token: `taxi123`,
    data: file.data,
  });
```

![image](https://github.com/dexie/Dexie.js/assets/115446026/f6a66835-97de-4493-8a61-144938d624f3)

But I can overcome it by removing the field `data` in schema like below and it works:

```
  const db = new Dexie('duckDB');

  db.version(1).stores({ datasets: 'token' });

  const writeStart = performance.now();

  db.table('datasets').put({
    token: `taxi123`,
    data: file.data,
  });
```
<img width="647" alt="Screenshot 2023-11-20 at 11 58 02 PM" src="https://github.com/dexie/Dexie.js/assets/115446026/acea7dec-97de-402d-b4ed-3053ea0093e6">

Is there any limit set for buffer size ? if yes then why second way was not failing

**Comment by dfahlander** [comment]
See https://dexie.org/docs/Version/Version.stores()#warning

**Comment by balasaravanan02** [comment]
Yeah works 👍
