### ISSUE TITLE
Readwrite transaction in liveQuery context

### ISSUE THREAD

**Issue by dfahlander** [dexie/Dexie.js#1831]
The error ReadOnly Error: "Readwrite transaction in liveQuery context" can happen in dexie v4.0.1-beta.1, v4.0.1-alpha.25, v4.0.1-alpha.24 and v4.0.1-alpha.23 even when the querier did not perform any 'rw' transaction at all if the observer of the liveQuery performs a 'rw' transaction in the next micro task after it has been triggered. The issue was reported on a nextjs application using dexie@4.x and was a result of react scheduling an useEffect that did an 'rw' transaction.

**Comment by frankleng** [comment]
@dfahlander still getting this consistently 
```
Error\n    at getErrorWithStack (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:317:12)\n    at new DexieError (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:416:19)\n    at Object.transaction (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:4489:27)\n    at Transaction.create (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:2680:32)\n    at eval (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:4040:23)\n    at eval (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:1167:23)\n    at callListener (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:890:19)\n    at endMicroTickScope (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:964:25)\n    at eval (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:946:34)\n    at usePSD (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:1154:16)\n    at physicalTick (webpack-internal:///../../node_modules/.pnpm/dexie@4.0.1-beta.4/node_modules/dexie/dist/modern/dexie.mjs:945:5)"

ReadOnlyError: Readwrite transaction in liveQuery context. Querier source: async ()=>{
     //.....
    }
```

**Comment by dfahlander** [comment]
You're right. I've found the reason and will release a new version today.

**Comment by frankleng** [comment]
reverted back to 3.2.4 for now.
thank u for the hardwork!

**Comment by dfahlander** [comment]
@franleng thanks! The new release 4.0.1-beta.5 should probably be a better as long as the querier only performs pure read queries only and does not have any side effects (like setting state of another component, mutating DOM etc). The same principle goes for 3.2.4, but the difference is that it will not complain when it happens.

Let me know if you'd have a chance to try 4.0.1-beta.5 just to verify the problem goes away. If not, check whether your callback to liveQuery() may have side effects or write to the DB. If still any issue, I'd be happy to troubleshoot it.
