### ISSUE TITLE
A few questions about dexie-import-export

### ISSUE THREAD

**Issue by forsakeninfinity** [dexie/Dexie.js#1838]
I am using dexie-import-export to export and import some data and seeing some strangeness so seeking some clarity.

Does Dexie add more rows for metadata proposes than what is in the source database when exporting? Are those rows also written to the database when importing? If yes, is there a way to not write those rows? I just want to be able to clean transfer the source database exactly as-is but the size of imported database is significantly larger than the source one and apparently contains more rows too.

Perhaps related question: does Dexie add an index by default when opening a database? I believe it doesn't but I am wondering if it does and if it exports that information such that importing loads it too. A user of my code ran into `DataError: Failed to read large IndexedDB value` when trying to export a database and this stackoverflow answer makes me wonder if indexing has got anything to do with that, and if so, perhaps it is contributing to the extra crud: https://stackoverflow.com/questions/76686618/dexie-js-very-large-indexeddb-but-empty-tables

FWIW, I use very simple, straight-off-the-shelf code [to export](https://github.com/forsakeninfinity/yomibaba/blame/master/ext/js/pages/settings/backup-controller.js#L453-L458) and [to import](https://github.com/forsakeninfinity/yomibaba/blame/master/ext/js/pages/settings/backup-controller.js#L504-L509)

Any and all thoughts appreciated 🙏

**Comment by dfahlander** [comment]
dexie-export-import does not add any extra rows. It does not add any indexes either.

**Comment by forsakeninfinity** [comment]
Thanks!
