### ISSUE TITLE
In nextjs, dexie module executes in double instances

### ISSUE THREAD

**Issue by dfahlander** [dexie/Dexie.js#1843]
It turns out that nextjs will load dexie in double instances - not just one client and one server instance but actually double client instances. This is not good as dexie keeps global state. We need a way to prohibit double instances of dexie running in the same app.

**Comment by nlaurie** [comment]
I just got the latest code synced on my branch and started getting this build error with my Vite Build of a Vue 3 App.

I found this issue connected to a package.json change which may be related.  

Nick

[vite-plugin-pwa:build] "default" is not exported by "../../../Dexie.js/dist/dexie.min.js", imported by "../../../Dexie.js/import-wrapper-prod.mjs".
file: /Users/nlaurie/Development/metafig/Dexie.js/import-wrapper-prod.mjs:4:7
2: // multiple occurrancies of the same module in the same app
3: // (dual package hazard, https://nodejs.org/api/packages.html#dual-package-hazard)
4: import _Dexie from "./dist/dexie.min.js";
          ^
5: const DexieSymbol = Symbol.for("Dexie");
6: const Dexie = globalThis[DexieSymbol] || (globalThis[DexieSymbol] = _Dexie);
error during build:
RollupError: "default" is not exported by "../../../Dexie.js/dist/dexie.min.js", imported by "../../../Dexie.js/import-wrapper-prod.mjs".

**Comment by dfahlander** [comment]
Thanks! I'll look into this asap
