### ISSUE TITLE
Is it possible to modify data during importing/exporting?

### ISSUE THREAD

**Issue by rayzhao99** [dexie/Dexie.js#1848]
When importing/exporting data with the `dexie-export-import` (<https://dexie.org/docs/ExportImport/dexie-export-import>), it is possible to filter unwanted data. But, can we modify/change data yet?

A typical scenario (at least to us only) is to change the primary/foreign keys of the data. So when importing into an existed db, conflicts can be avoided. 

It would also be appreciated if the filtering & modification can be fulfuled within one callback. For example, current `filter()` callback could be upgraded to support a similar behavior to the `Collection.modify()`, so the in-param of `value` could be modified then.

**Comment by dfahlander** [comment]
That's a nice idea, but unfortunately not possible with the current version.

Would a new `transform` callback be ok? It would have to support both inbound and outbound tables. One suggestion would be to let the optional transform callback return `{ value }` for inbound keys and `{key, value}` for outbound keys.

<img width="696" alt="image" src="https://github.com/dexie/Dexie.js/assets/6791329/9ca0acca-1ebf-4ae6-b7e6-a139da6c9875">

**Comment by dfahlander** [comment]
I briefly created a PR for a proposal to add transform to export and import. Should add a unit test also. Change suggestions and additional changes welcome. A unit test is still missing for it.

**Comment by rayzhao99** [comment]
Great! Thank you for a so quick response:)

**Comment by dfahlander** [comment]
dexie-export-import@4.1.0 released recently with the transform option.
