### ISSUE TITLE
Explicit type for Observable via liveQuery fails (TS2740: Type Observable<X>  is missing the following properties from type  Observable<X> :  source, operator, lift, forEach , and  2  more.)

### ISSUE THREAD

**Issue by s-gbz** [dexie/Dexie.js#1857]
I'll keep it short, but hopefully clear:

### Works fine

```js
 songsToPractice$ = liveQuery(
    () => db.songsToPractice.toArray()
  )
```

IntelliJ inferes the type as `Observable<SongToPractice[]>`

### Fails

```js
  songsToPractice$: Observable<SongToPractice[]> = liveQuery(
    () => db.songsToPractice.toArray()
  )
```

With the message:
```
Type  Observable<SongToPractice[]>  is missing the following properties from type  Observable<SongToPractice[]> :  source, operator, lift, forEach , and  2  more.
```

### Workaround
Casting via unknown to Observable as suggested by ChatGPT with the note:
The liveQuery function from Dexie library is likely returning an object with an observable-like interface, but TypeScript can't verify it as a proper Observable type.
```js
  songsToPractice$: Observable<SongToPractice[]> = liveQuery(
    () => db.songsToPractice.toArray()
  ) as unknown as Observable<SongToPractice[]>;
```

**Is there any way except for using `as unknown as Observable<SongToPractice[]>`?**

### Versions used
I've looked for similiar issus, but didn't find exact matches.
Using Anglular 17 with  dexie ^3.2.4

**Comment by dfahlander** [comment]
The observable returned from liveQuery() is not an Rx.Observable but compatible with it using the `from` operator from rxjs.

**Comment by s-gbz** [comment]
Thanks for your response.
I should've waited 10 minutes longer before posting, because I noticed the (original) issue might've been caused by the brand new Angular 17 ng-for syntax (or my misshap).

I've updated my post to reflect the new question

"**Is there any way to use explicit typing without resorting to `as unknown as Observable<SongToPractice[]>`?**"

### Solution:

```js
songsToPractice$: Observable<SongToPractice[]> = from(
    liveQuery(() => db.songsToPractice.toArray())
  );
```
