### ISSUE TITLE
useLiveQuery with multi-entry-index in dexie 4.0.1-beta

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1863]
So.... this is hilarious. I had absolutely zero sense of deja vu when I was reproducing this bug, but after I got the repro completed, I checked to see if there were any existing issues and... look who reported this one: https://github.com/dexie/Dexie.js/issues/1240 😂 

So... this seems to be happening again with Dexie 4.0.1-beta-6. I made a repro here: https://stackblitz.com/edit/stackblitz-starters-vzuhr5

It's not a very minimal repro, for which I apologize, but the big comment around line 29 explains the problem. Live queries that query against `where` when the target is a MultiEntry index don't seem to be live-updating properly.

**Comment by dfahlander** [comment]
Wow. Surprises me though. Maybe the previous fix didn't cover all cases. I'll check it out after Christmas. Please remind me next week or so. Well when thinking, it could be the new optimistic cache spooking! If you have time, try to set { cache: 'disabled' } in constructor options. If bug disappears I will know where to look.

**Comment by dusty-phillips** [comment]
That's it! Setting `cache: 'disabled'` causes the repro to behave correctly. I updated it to include that info. I'll do that for now so we're unblocked on upgrading. Thanks!

**Comment by dusty-phillips** [comment]
@dfahlander heres the reminder you asked for. 😎
