### ISSUE TITLE
Index name different than keyPath

### ISSUE THREAD

**Issue by Stretsh** [dexie/Dexie.js#1870]
Submission of longer, more detailed description got messed up, so quickly adding a shorter one:

Could the possibility be added to define a separate name for an index, than the keypath? Unless that is already possible. 

https://dexie.org/docs/IndexSpec#name--string says that `Unless this is a compound index, name will always equal keyPath.`

I wrote an app for IndexedDB, using [createIndex](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/createIndex), where a value for name and keypath is required. They can be the same, but they need to be specified separately. I'm slowly switching to Dexie, but it would suck to have to rewrite everything that uses a different name for an index than the keyPath.

Suggestion: use a forward slash: `'++id, name, latest/last_updated, *account/email'`

**Comment by dfahlander** [comment]
If you switch from raw indexeddb or other wrapper, Dexie will still pick up your index no matter what it was named, see https://dexie.org/docs/Tutorial/Migrating-existing-DB-to-Dexie. Would this solve your case?

**Comment by Stretsh** [comment]
Yes, this helped! Don't know how I missed that migration tutorial. Tested it out and can confirm that new items are also in the right index, despite the index name.

Thanks!
Closing this. Feel free to reopen, if you do decide to add the feature I mentioned.
