### ISSUE TITLE
Dexie Cloud REST API /all/<table> endpoint members

### ISSUE THREAD

**Issue by flipdav8** [dexie/Dexie.js#1874]
Is there a way to exclude retrieving members from the /all/table [endpoint](https://dexie.org/cloud/docs/rest-api#all-endpoint)?

For example when I call  /all/students  I get all members for the database along with all the students in the reponse.data array. It would be great to only return the students so I can count how many exist in the database for example. I have set the scopes for the accessToken to be "ACCESS DB" and "GLOBAL READ"  and tried variations with no luck.

Cheers,
Phil

**Comment by dfahlander** [comment]
A new version of the service has been published with this issue fixed.
