### ISSUE TITLE
Dexie not inserting a record into indexedDb when there is a property equaling a Null contained in the object when the insert is attempted.

### ISSUE THREAD

**Issue by gwheeloc69** [dexie/Dexie.js#1883]
![error](https://github.com/dexie/Dexie.js/assets/133680308/b2dc32cf-fcf2-47cd-bdb8-424c8bd6d29e)

I've upgraded to version 3.2.4 of Dexie from version 2.0.4.  I'm experiencing an error in dexie.js in this function when the obj is null.  I did not experience this in the older version.
I've attached an image of the code where the problem is happening. 
![SectionOfCodeWhereErrorHappens](https://github.com/dexie/Dexie.js/assets/133680308/bd2ec507-e0a4-45a2-8e6a-3f32bf68597f)

I don't know if there was a breaking change in version after 2.0.4 or not that effected how this works.  The data structure being attempted during the insert into indexedDb looks like this:

![HighlevelDataStructure](https://github.com/dexie/Dexie.js/assets/133680308/99ef9ee1-0544-4684-a838-3e871eb685a4)

**The issue is the Poni Property being null.**  If I give it a value the data is inserted with no problems.
This is the schema for the "table" in question:
'Inspection.Id,Inspection.AuditorId,Inspection.AuditorName,*PoniHeader.JobNumber,*Poni.Guid,*Inspection.Name,*Inspection.SourceId,Inspection.StatusId,Inspection.SubjectId,Inspection.InspectionItems.Id'

Any help would be appreciated. I'm happy to provide any additional information needed.

This is the call stack up to that point of the error if it helps.
![CallStackLeadingUpToError](https://github.com/dexie/Dexie.js/assets/133680308/be1e3b1b-3924-4ed7-8a02-1ae26faf1524)

Thank you.

**Comment by dfahlander** [comment]
Hi! Could you provide a repro of this? I could be a jsfiddle, a zipfile or a git repo with some code that reproduces this?
It surprises me that a property of null would cause this and I believe there must be other circumstances that causes this, such as addons or middlwares that fail when it happens.

**Comment by gwheeloc69** [comment]
David:

Thank you for looking into this.
Here is a jsfiddle I've created.
You will see it writes the record to the db, but generates an exception and stops the flow of the app, which is the problem.  I don't know if in version 2.0.4 generated the same issue, but the error was somehow consumed and not propagated.  I see the error being generated on line 23 of file util.ts.  For the sake of trying it with another version, I tried it with 3.25 and got the same result.
https://jsfiddle.net/w5ogj0qa/20/

I'm looking forward to your response on this.
Regards,
Glenn
315-385-3806

**Comment by dfahlander** [comment]
Thanks! I could track it down to the code where we try to resolve the indexed keys to track changes. It did not take hight for the case when a nested index exists and the parent object of that index is null. It did check for undefined only. Changed to check for null or undefined by using the double-equals instead of tripple-equals (which by the ecmascript spec will check of either null or undefined). New release will come soon on the 4.0 track and I will later on cherry pick this issue for the 3.x track.
