### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '{'

### ISSUE THREAD

**Issue by liuxilei** [dexie/Dexie.js#1886]
function parseScriptEvents(document, frame) {
    // TODO: parsed in iframe
    const scriptTags = document.getElementsByTagName('script');
    const parsedEvent = {}; // key: pixel ID, value: Map<eventName, code>
    for (const script of scriptTags) {
        // One script snippet might contain multiple pixelIds
        let pixelIds = [];
        if (script?.textContent?.length > 0) {
            for (const match of script.textContent.matchAll(regEx)) {
                // match[0] is the full string, like fbq("init", pixelId) or fbq("track", "PageView")
                // match[1] is the first matched element, eg "init" or "track"
                // match[2] is the second matched element, eg "pixelId" or "PageView"
                if (match[1] === 'init') { // ("init", "pixelId', optional something else")
                    const currentPixelId = match[2].match(/['"]?([\d]+)['"]?/)? match[2].match(/['"]?([\d]+)['"]?/)[1] : match[2];
                    // ======== There is a problem with the following line of code=======
                    if (!pixelIds.includes(currentPixelId) {
                        pixelIds.push(currentPixelId);
                        if (!parsedEvent[currentPixelId]) {
                            parsedEvent[currentPixelId] = {};
                        }
                    }
                } else if (pixelIds.length > 0) { // ("track", "pixelEventName', optional something else")
                    const pixelEvent = match[2].match(/['"]?([\w]+)['"]?/)? match[2].match(/['"]?([\w]+)['"]?/)[1] : match[2];
                    for (const pixelId of pixelIds) {
                        if (!parsedEvent[pixelId][pixelEvent]) {
                            parsedEvent[pixelId][pixelEvent] = {};
                        }
                        parsedEvent[pixelId][pixelEvent]["pixelCode"] = match[0];
                        parsedEvent[pixelId][pixelEvent]["frame"] = frame;
                    }
                }
            }
        }
    };

    return parsedEvent;
};

**Comment by liuxilei** [comment]
if (!pixelIds.includes(currentPixelId) { 

error code

**Comment by dfahlander** [comment]
I do not recognize the code. You might have posted to the wrong repository.
