### ISSUE TITLE
BigInt64Array getting corrupted after an update

### ISSUE THREAD

**Issue by michaelwallabi** [dexie/Dexie.js#1890]
Repro:
 - Create a table that contains a BigInt64Array nested within another object
 - Store a record
 - Update a field in the record

Expected:
 - only the updated field has changed

Actual:
 - The BigInt64Array is converted to an object after the update. It goes from `BigInt64Array[1n,2n]` to `{ 0: 1n, 1: 2n }`.

https://jsitor.com/Pb5sqDxM9p

Sample code
```
const db = new Dexie("usingbigint");
db.version(1).stores({
  obj: 'id',
});

Promise.resolve().then(async ()=>{
  await db.obj.put({id: 1, updated: Date.now(), cols: [{values: new BigInt64Array([1n,2n])}]});
  console.log((await db.obj.get(1)));
  await db.obj.update(1, {
    updated: Date.now()
  });
  console.log((await db.obj.get(1)));
}).catch(console.error);
```

**Comment by dfahlander** [comment]
Are you using dexie3 or 4? I can't open the jsitor link.

**Comment by michaelwallabi** [comment]
Thanks for taking a look @dfahlander. I'm using 3.2.4. Here's a jsfiddle with the repro as well:

https://jsfiddle.net/erpcwaz2/

**Comment by dfahlander** [comment]
Thanks a lot!

**Comment by michaelwallabi** [comment]
Thanks @dfahlander. Testing with 3.2.5 and all looks good to me.
