### ISSUE TITLE
KeyPath [time] on object store tran is not indexed

### ISSUE THREAD

**Issue by sayedfmurad** [dexie/Dexie.js#1891]
when I perform the following scan:
`
let r = await db.tran.where(["time"]).between(2, 1000, true, true).toArray()
`
it will throw an Exception 
KeyPath [time] on object store tran is not indexed

here is my implementation
`
let db=new Dexie('db');
db.version(1).stores({                              
                tran:'time'
            });
db.tran.put({"time":234});
`

**Comment by dfahlander** [comment]
Remove the square brackets because `time` is not a [compound index](https://dexie.org/docs/Compound-Index).

```ts
let r = await db.tran.where("time").between(2, 1000, true, true).toArray()
```
