### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '{' (at content.js:18:60)

### ISSUE THREAD

**Issue by liuxilei** [dexie/Dexie.js#1906]
![Snipaste_2024-02-22_10-17-31](https://github.com/dexie/Dexie.js/assets/30617094/074e2a01-2fe4-479b-b1de-f3fc0e083c4e)
![Snipaste_2024-02-22_10-18-44](https://github.com/dexie/Dexie.js/assets/30617094/c596e687-d161-46f0-aa36-3eb5261e5190)

**Comment by dfahlander** [comment]
You forgot a parentheeses. Closing.

**Comment by liuxilei** [comment]
this is your code error!!!!

**Comment by dfahlander** [comment]
It's not from Dexie source. Can you explain where I have written the code? Sample? Stackoverflow issue? I need a bit more of a context to make this constructive.
