### ISSUE TITLE
Please Sign the Open Letter to Tim Cook: Sabotaging Web Apps Is Indefensible

### ISSUE THREAD

**Issue by nickchomey** [dexie/Dexie.js#1908]
Hi there, I hope it is ok to share this here. 

In one week, Apple will be killing Progressive Web Apps in the EU so as to maintain their App Store extortion racket. 

The Open Web Advocacy group is leading the fight against this, and has launched this open letter which has gained nearly 2000 signatures in the first day. 

I figured I would share it here given that Dexie/IndexedDB is heavily used in PWAs. 

Please sign the letter and spread the word far and loud!

https://letter.open-web-advocacy.org/

**Comment by dfahlander** [comment]
Seems Apple reversed its course in this matter \O/

https://appleinsider.com/articles/24/03/01/apple-reverses-course-on-death-of-progressive-web-apps-in-eu?utm_source=tldrwebdev
