### ISSUE TITLE
Filter results in reading hook

### ISSUE THREAD

**Issue by scriptPilot** [dexie/Dexie.js#1911]
Is there any way to filter elements within the reading hook as proposed by ChatGPT ?

Seems not to work, I get an array of boolean.

My solution:

```js
// Filter deleted documents from results
table.hook('reading', doc => {
  return !doc.$deleted
})
```

ChatGPT proposal:

```js
// Assuming you have a Dexie database instance called 'db' and a table called 'myTable'

// Define your hook function
function filterRecords(primKey, obj, trans) {
    // Filter logic goes here
    if (obj.someProperty === 'someValue') {
        // Returning null from a 'reading' hook will effectively exclude the record from being read
        return null;
    }
    // Return obj if you want to include the record as is
    return obj;
}

// Hook the reading operation
db.myTable.hook('reading', filterRecords);
```

**Comment by dfahlander** [comment]
I think ChatGPT got it wrong there. The [reading hook](https://dexie.org/docs/Table/Table.hook('reading')) does not support filtering - only mapping.

Filtering as you request is possible to implement using a middleware and add it using [Dexie.use](https://dexie.org/docs/Dexie/Dexie.use()) and override the [query and openCursor methods](https://github.com/dexie/Dexie.js/blob/v4.0.1-beta.14/src/public/types/dbcore.d.ts#L199-L200). The latter is a bit verbose to override as you need also to return a cursor instance that pretends that the $deleted objects aren't there. There are examples of that in dexie source [createVirtualCursor()](https://github.com/dexie/Dexie.js/blob/v4.0.1-beta.14/src/dbcore/virtual-index-middleware.ts#L141-L181) that use Object.create() to create a "proxy" cursor. In your case it would need to override continue and continuePrimaryKey to call itself recursively if hitting a value with $deleted property set.

Note though that count() would not be correct - it would still count the $deleted rows unless it's also overrided. However, to do this with good performance, you might end up having to do something similar to what is done in [virtual-index-middleware.ts](https://github.com/dexie/Dexie.js/blob/v4.0.1-beta.14/src/dbcore/virtual-index-middleware.ts). That would probably also require to override Version.prototype._parseStoresSpec and prepend the $deleted property to all indexes making every index a [compound](https://dexie.org/docs/Compound-Index) index but pretend them to be normal indexes from your middleware.

Long answer of short question, sorry. It might be that you find some different and easier way of solving this.

If the question was about an application and not a library, I would rather suggest to let the application be aware of the $deleted property and include it in the indexes that would be queried, but I see you are creating a generic library.

**Comment by scriptPilot** [comment]
@dfahlander - Thanks for the very comprehensive answer. Well, indeed it sounds like a little challenge. Wondering why the reading hook does not provide such a helpful feature to exclude records entirely from the response. 🙈

**Comment by dfahlander** [comment]
Currently 'reading' hook is like Array.map() and not Array.filter(). A filtering hook can be built but would need an implementation in form of a middleware.

**Comment by scriptPilot** [comment]
Alright. I think it would be very helpful to follow the ChatGPT proposal indeed :-D
I have created the feature request #1913
