### ISSUE TITLE
Vue.js best practices for retrieving/joining tables?

### ISSUE THREAD

**Issue by karsvaniersel** [dexie/Dexie.js#1914]
So I have an employees table, each employee has some roles.

Now of course I want to display this data in a list so I do a `v-for="employee in employees`, but then when I want to display the `role.text` for example, I can't. Cause of course I only have an array `roleIds` on the Employee.

Now on the docs I have come across multiple ways to do this, but ideally I would want to load all the employees once + with their role (as retrieved objects so I can loop over those as well)

Am I missing something, or am I going completely the wrong way about this? Cause there seems to be so little on the internet about what I am trying to achieve, that I start to wonder if what I am doing is even the 'right' way to go about using Dexie.

In my head, I have 1 Pinia store, that gets filled on the initial request of the app, so that the user has instant load times throughout using the app. So I am not doing any queries after the initial page view (besides of course the user using search functionalities).

Bonus question:
How would I even go about doing this using the 
```useObservable(
    liveQuery(() => {
        return db.employees.toArray()
    }))
```

Cause in an ideal world, of course, the changes are automatically rendered on the Dashboard.

**Comment by dfahlander** [comment]
If the roles table is relatively small (less than 200 records), I would suggest the following:

```ts
liveQuery(async () => {
  const employees = await db.employees.toArray(); // or use a where clause to filter
  const roles = await db.roles.toArray();
  // Attach a resolved "roles" property to the result:
  return employees.map(empl => ({...empl, roles: empl.roleIds.map(id => roles.find(r => r.id === id))}));
});
```

In a situation where there are few employees returned but the related table is large, it would be better to:

```ts
liveQuery(async () => {
  const employees = await db.employees.where({foo: 'bar'}).toArray(); // or another criteria or offset/limit
  const roleIds = new Set(employees.flatMap(e => e.roleIds)); // Get all unique roleIds to resolve
  const employeeRoles = await db.roles.bulkGet([...roleIds]); // Assuming roles is a large table - request only the nescessary roles we need for this query.
  // Attach a resolved "roles" property to the result:
  return employees.map(empl => ({...empl, roles: empl.roleIds.map(id => employeeRoles.find(r => r.id === id))}));
});
```

**Comment by dfahlander** [comment]
We're not using Discord. Platforms we are active at are [stackoverflow](https://stackoverflow.com/questions/tagged/dexie) and github. There are quite a lot of issues explicitely marked as questions on [Github](https://github.com/dexie/Dexie.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Aquestion). We also have slack but I prefer having all questions publicly available for everyone to search - which we get with both github and stackoverflow.

**Comment by dfahlander** [comment]
Update: There's now an official Discord server at https://discord.gg/huhre7MHBF
