### ISSUE TITLE
Should 3.2.6 be latest?

### ISSUE THREAD

**Issue by mdr** [dexie/Dexie.js#1915]
[On npm](https://www.npmjs.com/package/dexie?activeTab=versions), version 3.2.5 is marked as `latest`, and 3.2.6 as `latest-3`. Should 3.2.6 also be tagged as `latest`?

**Comment by mdr** [comment]
@dfahlander Similar with 3.2.7? (I only notice because it pops up on `yarn upgrade-interactive` where it suggests I downgrade.)

**Comment by dfahlander** [comment]
Thanks again 🥇 Fixed
