### ISSUE TITLE
Can I ask a question about 'where'?

### ISSUE THREAD

**Issue by xiaofeng1998025** [dexie/Dexie.js#1916]
My query parameter age I want to add between condition [10,20] How to adjust it by using object?
    const searchCriteria = {
        name: "John Doe",
        age:10
    };
    bds.where(searchCriteria).toArray().then(data=>{
        console.log(data)
    }).catch(err=>{
        console.log(err)
    })

**Comment by dfahlander** [comment]
```ts
// Declare an index '[name+age]'
const db = new Dexie('dbname');
db.version(1).stores({
  friends: 'id, [name+age]'
});

// Query friends where name='John Doe' and name between 10 and 20:
await db.friends
  .where('[name+age]')
  .between(
    ['John Doe', 10],
    ['John Doe', 20],
    true,
    true
 ).toArray();

```
