### ISSUE TITLE
allow bulkPut to accept object with keys as primary key

### ISSUE THREAD

**Issue by tacman** [dexie/Dexie.js#1923]
I'd like to load https://www.floatrates.com/daily/usd.json into a dexie table, but the data is returned as an object, with each key of the object being the primary key of the object.

```json

  "aud": {
    "code": "AUD",
    "alphaCode": "AUD",
    "numericCode": "036",
    "name": "Australian Dollar",
    "rate": 1.5228242038472,
    "date": "Fri, 15 Mar 2024 23:55:10 GMT",
    "inverseRate": 0.65667461646174
  },
  "cad": {
    "code": "CAD",
    "alphaCode": "CAD",
    "numericCode": "124",
    "name": "Canadian Dollar",
    "rate": 1.3531700713821,
    "date": "Fri, 15 Mar 2024 23:55:10 GMT",
    "inverseRate": 0.7390054074863
  },
```

There is probably some slick javascript way to process these, but it'd be a cool feature if bulkAdd detected this format and treated it accordingly.  Obviously, it wouldn't work for compound keys, but I have to imagine that this formatted is somewhat common.

In the meantime, I'll use this:

```js
const sendUrl = "https://www.floatrates.com/daily/usd.json";
                const sendType = "GET";
                fetch(sendUrl, {
                    method: sendType,
                    headers: {
                        'Accept': 'application/json',
                    },
                })
                    .then(data => {
                        let arrayValues=[];
                        Object.keys(data).forEach(key => {
                            const value = data[key];
                            value['lcode'] = key;
                            console.log(value);
                            arrayValues.push(value);
                        });
                        console.log(arrayValues, db);
                        return db.currency.bulkAdd(arrayValues);
                    });
```

Thanks for your consideration.

**Comment by dfahlander** [comment]
I try to avoid special sugar unless they are extremely obvious or expected. Docs of the API would have to grow and with it, the time spent for users to understand it. In this case it's easy to implement once it's clear how bulkAdd works. Having this option would require some special options parameter or another bulk method specific to this. Closing this ticket. Feel free to reopen of there's something clearly convincing to implement it.
