### ISSUE TITLE
`karma-safari-launcher` may be not a dependency

### ISSUE THREAD

**Issue by emeryao** [dexie/Dexie.js#1924]
Hi Team

There is a `dependencies` of `karma-safari-launcher` on npm [here](https://www.npmjs.com/package/dexie/v/3.2.6?activeTab=dependencies)

But IMHO that may not be a dependency and I searched out the codebase and didn't find any code related with `karma-safari-launcher`

Please confirm and help

---

Sorry for my poor English

**Comment by dfahlander** [comment]
Thanks! This must have been by accident when releasing [dexie@3.2.5](https://github.com/dexie/Dexie.js/releases/tag/v3.2.5) when adapting the new CI flow for 3.x. Will fix asap.
