### ISSUE TITLE
How to validate client tokens

### ISSUE THREAD

**Issue by oyalhi** [dexie/Dexie.js#1931]
This is not an issue rather a question.

I'm curious how we can validate client tokens via dexie cloud. After a user logs in to the client app, we might want to make requests to our server using the client token obtained after a succesfull login. Our server will need to validate this token. How would this be possible please?

Congratulations on the release btw!

**Comment by dfahlander** [comment]
Thanks for a valid question. I've created a new endpoint for this in the staging environment. Please send me your database URL to david@dexie.org and I can enable staging for it so you can try it out.
