### ISSUE TITLE
Dynamically Upgraded Schema does not retain tables after page refresh

### ISSUE THREAD

**Issue by abduljabbar021** [dexie/Dexie.js#1937]
I have created a class for Dexie Database Management like

        //DBManager.js  (simplified version)
        class DBManager{
	       constructor(){}
	       createConnection(){
		     this.db = new Dexie('myDB');
                     let ver = localStorage.getItem('dbVersion') ?? 1;
                     let schema = {
                              tblA : '++id, cid', 
                              tblB : '++id, uid'
                     };
                     this.db.version(ver).stores(schema); //Problems seems here as it is always using same schema even for new version
                     return this.db;
	       }
        }

On every page load, I call like this
 
       let dbManager = new DBManager();
       let db = dbManager.createConnection();

and then use this db variable for database operations.

Now I upgrade schema and version of database like

       let newVersion = 2;  
       db.close();
       db.version(newVersion).stores({tblC : '++id, did'});
       db.open();
       localStorage.setItem('dbVersion', newVersion);

everything works good till here.

But when I refresh page, it does not have my new table tblC but only tblA and tblB. It's may be as I pointed because it always uses the same schema even with newer versions. Or am I missing something else?

My Questions are 

1) Do I need to store new Schema as well and use new Schema with new version? like

         localStorage.setItem('dbSchema', JSON.stringify(old + new schema)); //Add this new Schema with new version in
         this.db.version(localStorage.getItem('dbVersion') ?? 1).stores(JSON.parse(localStorage.getItem('dbSchema')));

2) Will my new version (2) have all my new and old tables along with data or I will have to migrate data from old version to new version of database?

3) What if I do not want to migrate because I may be needing to upgrade schema every now and then.

**Comment by dfahlander** [comment]
Don't know if you found an answer. But just for your knowlege, in dexie@4 unlike dexie@3 and 2, you can extend schema without incrementing version number.
