### ISSUE TITLE
Feature Request: add direction to sortBy() method

### ISSUE THREAD

**Issue by tacman** [dexie/Dexie.js#1954]
Instead of
   
     db.friends.orderBy('lastName').reverse().offset(10).limit(5);

I'd like to do

     db.friends.orderBy('lastName', 'desc').offset(10).limit(5);

That is, if I'm calling orderBy I'd like to optionally add the direction without having a separate statement.

**Comment by dfahlander** [comment]
Not sure whether it's the best signature for this as `orderBy('property', 'desc')` could be interpreted as if 'desc' was a property to order on secondly. I think we could wait with this as there's already another possibility to orderBy in descending order using `orderBy('property').desc()` (which is deprecated by the way to the favour of `orderBy('property').reverse()`.
