### ISSUE TITLE
Is it possible to invite a user who is not signed up?

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1980]
I was under the impression that a user who is not currently on the platform could be sent an invite by having their e-mail address added to a realm with invite set to true. However, I am finding that invitation e-mails do not go out unless the user being invited is already a member.

I don't know why I was under that impression; I can't find anywhere in the documentation that says it should be possible. If it's not possible, the docs should probably clarify that it isn't possible. Also, there probably needs to be some feedback to give to the inviting user that the invitation was never sent out.

**Comment by dfahlander** [comment]
The invite goes out no matter if user id registered or not. If this isn't the case it could be spam filter out similar prohibiting the invite from going out. However, of the user is invited over the REST api we do not currently process invites s they should. This is a limitation that will be fixed.

**Comment by dusty-phillips** [comment]
Hmm, I definitely didn’t receive any invite emails for a non-existing user after multiple attempts. But after they logged in a first time, if I sentmore invites I received them all immediately. I’ll experiment some more and report back.

**Comment by dusty-phillips** [comment]
Ok... I've tested with a dozen different e-mail addresses on three different domains (checking multiple spam folders) using three different dexie-cloud databases and I think I've narrowed down the behaviour:

**The first time I invite a user to a realm by a user that has never invited that user before, the invite is never received.**

This is true regardless of whether the user has an account on the database, and regardless of whether they have been invited to other realms by other users.

If I add the user to the realm a second time, the invite is always sent out.

if I send e-mails in this order:

1. user a invites user b to realm a1 --> email not received2
2. user a invites user b to realm a1 --> email received
3. user a invites user b to realm a2 --> email received
4. user c invites user b to realm c1 --> email not received
5. user c invites user b to realm c1 --> email received

This is not an urgent issue for me, but if it is reproducing for other users you might want to take a look @dfahlander.

**Comment by dfahlander** [comment]
I was almost certain that this must be related to the email system throttling emails to new addresses. However, I could repeat the issue and look in the sendgrid logs where I cannot find the first invite ever reaching it. So obviously something is blocking the first invite from going away for some reason.

**Comment by dfahlander** [comment]
I found the issue. It happened when a new realm was created and a user was invited to it in the same go. A fix is on the way on the server.

**Comment by dfahlander** [comment]
Server updated
