### ISSUE TITLE
circularly reference on update

### ISSUE THREAD

**Issue by Zetanova** [dexie/Dexie.js#2001]
I get a tslint error when I try to use the following entity 

```ts

//bufbuild generated class
export declare class User extends Message<User> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 3 [json_name = "n"];
   */
  name: string;

  /**
   * @generated from field: map<string, google.protobuf.Value> attributes = 10 [json_name = "atts"];
   */
  attributes: { [key: string]: Value };
 
  /**
   * @generated from field: google.protobuf.Value metadata = 25 [json_name = "meta"];
   */
  metadata?: Value;

  constructor(data?: PartialMessage<User>);

  //other stuff
}

//dexie table entity
export interface UserEntity {
  key: string,
  entry: PlainMessage<User>,
  //some other properties
}
```

This method call generates the error only if the `UserEntity.attributes` field is defined.
```ts
const entity:UserEntity

await db.users.update(entity, n => { })
//[ERROR] TS2615: Type of property 'values' circularly references itself in mapped type '{ values: "values" | `values.${number}` | `values.${number}.${any}`; }'
```

add, put methods working fine and I could narrow the issue down to `attributes: { [key: string]: Value };` definition. But have now clue how to fix it.

**Comment by dfahlander** [comment]
Seems as a circular issue in the class definition of User as it extends a generic with itself as argument?

**Comment by Zetanova** [comment]
the PlainMessage is only a helper to strip out the helper methods and description fields of the protobuf message
https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#plainmessage

The issue happens really only if the `attributes: { [key: string]: Value }` field exists

**Comment by dfahlander** [comment]
What is `Value`?

**Comment by Zetanova** [comment]
It is a wellknown type of `google.protobuf.Value`
https://buf.build/protocolbuffers/wellknowntypes/docs/main:google.protobuf#google.protobuf.Value

The ts definition comes with the base package, most languages provide one for the wellknown  types.

Found here:
https://www.npmjs.com/package/@bufbuild/protobuf?activeTab=code
/@bufbuild/protobuf/dist/cjs/google/protobuf/struct_pb.d.ts
line: 65 `export declare class Value extends Message<Value> { ... }`

The `Value` class used without the map works fine like with the `metadata?: Value` field

**Comment by dfahlander** [comment]
Please provide a repro

**Comment by Zetanova** [comment]
@dfahlander  Here is the repo to reproduce the issue https://github.com/Zetanova/dexie-issue-2001

**Comment by dfahlander** [comment]
There's nothing we could do to support recursive types since the number of possible keypaths would be infinite. I wish we could fallback to `any` when this is the case but I haven't found any way to do it. PRs are welcome though ;)

What I could do at least is to change the declaration of the overloaded method Table.update() so that it won't complain about circular references if the callback version is used. Runtime, you could continue using the object overload though but you'd have to make TS compiler ignore the line with `// @ts-ignore` if so.

The provided repro compiles now at least but it's only using the callback overload.

**Comment by Zetanova** [comment]
My typescript skill level is only medium and I don't really understand why the issue fully

What I discovered is that a field with `value:Value` produces a circularly references error 
but an optional field (default in protobuf) does not,  `value?:Value` works fine

Some goes for `value:PlainMessage<Value>` has the issue 
but `value:PartialMessage<Value>` works

Maybe the `dexie.KeyPaths<T>` can output a optional value for map/record?

Compiler ignores are always a possibility
Maybe there is one to set it on `dexie.KeyPaths<T>` ?

I can workaround the issue over get/put

**Comment by dfahlander** [comment]
Since this is a typing issue only, it's probably better to workaround the issue by disabling typechecking only for the line that does table.update():

```ts
  // @ts-ignore
  db.someTable.update(...)
```

**Comment by Zetanova** [comment]
thx, is the best current option
