### ISSUE TITLE
Bulkadd method called second time, doesnt succeed neither fail

### ISSUE THREAD

**Issue by VanderSP** [dexie/Dexie.js#2010]
Hi there, thanks for this awesome JS OSS Work!

as described in title, i dunno why this happen... just a simple test, i tried to bulkadd some array, its ok first time, then i can´t do it again... any light here?

**Comment by VanderSP** [comment]
Maybe I didn´t understand something correctly, if i create a simple example using id++, it works fine... but in my real case, i use as 
db.version(1).stores({ Applications: 'hash' })... why i can use like this when adding one by one? but with bulk add, even creating different hashes, i just only can do bulkadd one time

**Comment by dfahlander** [comment]
Please share repro

**Comment by VanderSP** [comment]
Sorry, what a shame! was a logic fault of mine! only understood when tried make a repo sometimes.... first time using bulkAdd... new into Dexie... but definetely will be on a very nice project that will come to big light soon...

Thanks for all your effort to the community, you´re like the eternal WEB DB BUNDLER!

**Comment by dfahlander** [comment]
No prob! Thanks for circling back.
