### ISSUE TITLE
Bulk put puts duplicate objects into DB even if they share an ID

### ISSUE THREAD

**Issue by clintonmedbery** [dexie/Dexie.js#2012]
I am using dexie `bulkPut` with `useLiveQuery` and in version `4.0.7` we are putting duplicate items into the dexie DB.

I forked a codesandbox that was using 3.2.2 and this was not an issue. I updated Dexie to 4.0.7 and you can see it creates multiple items by pressing `Add Friend` even though they share an id.

https://codesandbox.io/p/sandbox/eloquent-dirac-lhrmcm

Steps to reproduce:

1. Click add friend.
2. See that many items are now in the list.

Is this expected behavior?

**Comment by dfahlander** [comment]
Similar to #2011. Bug is in the liveQuery cache. To workaround, create Dexie with cache disabled:

```ts
const db = new Dexie('dbName', { cache: 'disabled' });
```

**Comment by clintonmedbery** [comment]
Thanks! I will close since this is a dupe.
