### ISSUE TITLE
PSD.trans undefined

### ISSUE THREAD

**Issue by mofada** [dexie/Dexie.js#2018]
In my project, I added a new data and then deleted other data. When I deleted it, this error occurred.

the first, i add one data

![image](https://github.com/dexie/Dexie.js/assets/22286246/af91b25d-b93f-46ad-9372-02cbb80b00d3)

and then, i delete other data

![image](https://github.com/dexie/Dexie.js/assets/22286246/5a439924-76ca-42d1-af41-005aad25e617)

now broke up
![image](https://github.com/dexie/Dexie.js/assets/22286246/02fbfdf6-db1b-492e-93fb-4b98297ab2cb)

**Comment by dfahlander** [comment]
Is there any other dexie addons or middlewares active?
Are you experiencing the same issue on dexie@3 or only with dexie@4?

**Comment by mofada** [comment]
I just used dexie@4

```
"dependencies": {
  "dexie": "^4.0.7"
}
```

**Comment by dfahlander** [comment]
Could you try with dexie@3 and see if you experience the same issue?

**Comment by mofada** [comment]
I think there might be a problem with the internal dependencies of my project. I used the CDN reference and it worked properly.
