### ISSUE TITLE
Struggling with permissions and roles and users

### ISSUE THREAD

**Issue by phil-w** [dexie/Dexie.js#2020]
I'm struggling with Dexie Cloud, although I've been using Dexie itself over a number of years.

I'm going to need user roles and access control based on that, and I can see some of that possibly in the API, although I'm not sure my use case will work with Dexie Cloud or not. There's a conceptual level of documentation for the Cloud stuff which I've either not found or not understood, so far. 

I'm using Sveltekit. 

Anyway, one thing I found in the reference function list is `db.cloud.permissions` which sounds like I will need at some point, and perhaps it will help me sleuth it out. 

But what does this code below mean? I just have a database like an old style Dexie database but with the stuff from the documents applied to it to make it Cloud. What is `databaseObject` and how do I make one?
~~~
// When table is not mapped to a DexieCloudEntity subclass:
const o = db.cloud.permissions("friends", databaseObject);

~~~

I don't recall mapping anything to anything, but `databaseObject` is obviously going to need to be set. What is a "database object", why do I need it, what is the relationship between that and a collection "friends"? It says it returns the following:
~~~
export interface PermissionChecker {
  add(...tableNames: string[]): boolean;
  update(...props: string[]): boolean;
  delete(): boolean;
}
~~~
I'm not sure what sense that makes to me. "add" "update" and "delete" look understandable, so I guess it's a list of permissions. Why does it have table names in it (I'm passing the table/ collection name in, right?) What's the "thing" it's checking the permissions of, exactly? The current user, I suppose?

I wonder if, say, you just had followed the install instructions for Dexie Cloud, and were not using React.... what's a minimal code I'd need to read whatever these permissions are, and is there an example I've not found which does that?

**Comment by dfahlander** [comment]
Thanks for valid questions that I could assume more people would wonder...

I'll do my best to explain here as a draft for doc update. I suppose more samples would explain better also.

**databaseObject**
This is an object returned from the DB. For the typical [friends](https://dexie.org/docs/Tutorial/Svelte#3-create-a-file-dbjs-or-dbts) database, this could be the result from:

```ts
const databaseObject = await db.friends.get(friendId)
```

or

```ts
const databaseObjects = await db.friends.where('age').above(25).toArray();
```

**Permissions**

Current user can have various permissions depending on the [permissions](https://dexie.org/cloud/docs/access-control#permissions) configuration of the realm that the object belongs to (pointed out by it's `realmId` property) but also depending on whether the current user is the owner of the databaseObject or not.

Use `db.cloud.permissions()` to find out what permissions current user has. The return value is an observable, so in Svelte, you can to treat it as a readonly store:

```svelte
<script>
  import { add } from "dexie";

  const friend = await db.friends.get(friendId);
  const can = db.cloud.permissions("friends", friend);
</script>

<div>
  {#if $can.update("age")}
    <button on:click={() => db.friends.update(friendId, {age: add(1)})}>Birthday</button>
  {/if}
  {#if $can.delete()}
    <button on:click={() => db.friends.delete(friendId)}>Delete friend</button>
  {/if}
  {#if $can.add("friends")}
    <button on:click={openAddFriendDialog}>Add more friends</button>
  {/if}
</div>
```

**update** permission
The permission to update a property on an object is determined by whether current user owns the object or not, and also if the object belongs to another realm than your own default private realmId, whether current user has enought permissions for that. This is determined by the permissions or roles properties of the member objects for that realmId.

**delete** permission
Same principle as for the update permission.

**add** permission
This permission is only tied to the realmId of the object. There is no way to add an existing object. This permission tells whether current user has permission to add new objects in the same realm as this object.

See https://dexie.org/cloud/docs/access-control

---
Please reply with additional questions! It's easy that I could have missed out some more details.

**Comment by dfahlander** [comment]
One side note! This code only helps the app avoid to breaking the access control rules. The app can try to break those rules and succeed locally, but the real permission checks are done server-side, so when the actions are synced, any transaction that broke the rules will be rolled backed.

**Comment by dfahlander** [comment]
Roles is an observable of an object (I've just updated [these docs](https://dexie.org/cloud/docs/db.cloud.roles) that used to suggest it to be an array), so a correct example should be:

```svelte
let roles = db.cloud.roles

{#each Object.keys($roles) as roleId}
  <span>{$roles[roleId].displayName} </span>
{/each}
```

**Comment by phil-w** [comment]
1. I have the /public and /my API things working, but of course they don't need auth beyond the user token.
2. I created some roles using the CLI with a json input file as per the example... and they appear very prettily in my UI.  I'll put that in git and I can probably re-run it to redefine the roles later.


### now I need to figure out how to assign roles to users

Roles - an array of strings which are the names  in that JSON file above - are a [property in the Members' table](https://dexie.org/cloud/docs/access-control#properties-of-objects-in-members-table)... but how to set it that property? Not through the client obviously, which would be insecure. 

So it's got to be through the UI at https://manager.dexie.cloud/, or the CLI.
 - I looked at the help for `npx dexie-cloud ` and can't find anything which looks like a way to assign roles.
 - I can't see how to do that in https://manager.dexie.cloud/ either.

I want to assign at least a couple of different roles and then confirm (say) that one of them ("admin") can list other users etc, and that the other can't. Then I'll make the admin user list the other users, if I can...

**Comment by dfahlander** [comment]
Roles can be assigned by realm owners or members that have the permission to {manage: "members"} or specifically to {update: {members: ["roles"]}}. They have this permission client side and this is access checked server side on sync just like the other permissions. 

You may also edit a member using the rest api. The admin gui for assigning roles must be managed using your own code - client side or server side.

Regarding logging, you could add log entry objects to a Dexie table (such as db.logs). If you skip specifying any realmId property on the object, each user will only sync their own log entries but they will also be accessible via REST API /all/logs for API clients with GLOBAL_READ scope in their JWT to download all logs. A query can specify things like ?date>20240620. There should be some strategy to clean up old log entries though - either on the client or a server side job the does it via REST.

**Comment by phil-w** [comment]
> Roles can be assigned by realm owners or members that have the permission to {manage: "members"} or specifically to {update: {members: ["roles"]}}. ...

>> You may also edit a member using the rest api. The admin gui for assigning roles must be managed using your own code -

#### But how? 
I mean I know how to write code. I just know what code I need to write in this case to make this do what I know must be possible.

## Looking at the REST API
I found the [REST API page](https://dexie.org/cloud/docs/rest-api) again via google, although it must be linked somewhere as I stumbled across it it a few days ago and wrote some tests of the bits which don't require privilege. I should have bookmarked the location at the time.

Looking at that, my user has scope ACCESS_DB and I reckon I'll need GLOBAL_READ and GLOBAL_WRITE to manipulate other users to (a) see them and (b) assign roles to them. 

I played at hitting /token to request more access (test only, using the secret I won't have in any app) and that just 401s. Reading the next section of the documentation, which I didn't understand until I'd tried to code the thing and failed, it says:
>You can only request a subset of the scopes that your client has. 
So that was never going to work. Perhaps it may be better to include that higher up the doc. But then I'm not sure if the 401 means "You can only request a subset of the scopes that your client has." or that I've made some other error in the credentials I provided.

So that's not the answer to the puzzle. Joy.

**Comment by dfahlander** [comment]
The clientId and secret is stored in your dexie-cloud.key file. You can also generate additional clients/secrets using the CLI. The default client has full access. Using it you can request tokens with any scope on the /token endpoint.

**Comment by phil-w** [comment]
I got through some of this, but I still can't find the key bit of documentation. I tend to end up using google etc to find stuff here. Perhaps separating out the basic Dexie stuff from the Cloud stuff would help me a bit?
 
- I built a "proxy server" which is secure and in which I store the secrets I don't want in the client. 
- The client stuff works as per the docs with client tokens etc. When I want to use the Dexie Cloud API, for example to list or edit a user, I proxy that call through my secure server. 
1. The secure server validates & verifies the bearer token for all accesses. Validation responses are cached in memory, and token expiration etc handled. This Sveltekit `hooks.server.js` stuff. You need CORS code there for the Authorization header pre-flights.
1. I white list my "super user" (me!) in code and allow me to access an /admin part of the secure server. 
1. That part of the server gets (and caches...) a "super user token" with the minimal priviledges I need.
1. The server then makes a request to Dexie Cloud to /users or whatever, passing the super user token and using the format required by Dexie. The proxy's good for this as I can keep the client simple and consistent and deal with any Dexie specific things in one layer. Plus I can securely log (to a MongoDB) from this place. 
1. The response is returned to the super user. The super user token stays on the server in a memory based cache.

 - [x] I have that listing `/users`. I don't love that paging style (how can I count users?) 
 - [x] I can patch via `/users` (Dexie uses a POST for that) a user and edit the data field. Note that that field MUST be an object and can't be a string. If a request is for JSON and returns an error, the response is HTML. I parse it back to data.
 
-----
## The Problem:  I can't work out how to edit the user role!
I'll fiddle around with it, maybe I'll work it out, but if anyone knows how to edit a user role that'd be helpful
The "roles" aren't even listed in the user list, although I can (and do) list them via `/public/roles`

That's my final step, then this can be closed:
 - [ ] Assign one of the existing roles to a user.

**Comment by dfahlander** [comment]
Roles are set per member, not per user. Unlike users that are server-only - and handled outside the client-server replication, members are replicated and can be update client-side as long as the user has permissions to do so in your realm (`{ update: { members: ["roles"] } }`). Will you be using a single realm for your app? If so, you can manage roles in members only.

A single realm means that all users will share all data with each other but the permissions will decide what parts of the data that can be manipulated. This can be valid for certain applications. The flexibility with using multiple realms is that ic supports a multi-tenant model. The same user can have different roles within different realms.

If we would build a Slack replica, we would probably let each channel be represented by a realm - everyone in it would see everything but some of the members would have reaonly access. The channel creator could decide who to invite and give appropriate permissions to anyone invited. (S)he could also give permission to other members to manage the channel.

> * [x]  I have that listing `/users`. I don't love that paging style (how can I count users?)

Yep, the paging-style of the [/users endpoint](https://dexie.org/cloud/docs/rest-api#users-endpoint) should be optional or there should at least be a count of total users in the initial result. I can agree.

> * [x]  I can patch via `/users` (Dexie uses a POST for that) a user and edit the data field. Note that that field MUST be an object and can't be a string. If a request is for JSON and returns an error, the response is HTML. I parse it back to data.

The  [/users endpoint](https://dexie.org/cloud/docs/rest-api#users-endpoint) has a strict schema documented [here](https://dexie.org/cloud/docs/rest-api#update-users), unlike the endpoint for replicated data where you can have any properties of the types that the application decides. There's only one metadata property where you can put anything you need in it - the `data` property. It needs to be an object but you may store anything you like in it as long as it is plain JSON (also unlike indexedDB replacated data that can contain exotic types like Date, Uint8Arrays etc.

**Comment by phil-w** [comment]
> Roles are set per member, not per user. Unlike users that are server-only - and handled outside the client-server replication, members are replicated and can be update client-side as long as the user has permissions to do so in your realm (`{ update: { members: ["roles"] } }`). Will you be using a single realm for your app? If so, you can manage roles in members only.

Thanks 

I'm not sure I understand the difference between a "member" and a "user" yet.

I'll go away and fiddle with it to see if I can make it work. However as _none of my clients can have any secrets_ [and still be secure], I'd be surprised if I can update roles at the client. I'd have expected to need the Super User Token, which I can generate only on a dev box or my proxy server. I'll try...

..but I need to get `/public/roles `editing working first, which I hope is similar to `/users` so I can reuse the code etc.

I don't understand the "realm" thing, but I expect if I need it, I will figure it out.  I expect one will suffice. 


- I got secure user editing going plus deactivate/ delete. I'm GDPR qualified, but I'll leave the full deletion as a manual process. Nice to have the feature though. I went the other way and stopped me accidentally deleting myself; I don't want admins doing that!

-  [x] **How to re-activate a deactivated user?** 
To deactivate you set `deactivated` to an ISO date. But to get it back active... you set it to a boolean `false`

**Comment by phil-w** [comment]
## 1 users
I have a single realm, rlm-public.  Users can create themselves, and my "super user" can list, edit and delete them using the Dexie Cloud API, through my proxy server which elevates my super user's privilege. I have a Sveltekit app which lets the user sign in and all that. If the user is the "super user", then they can:
 - list all the other users in the system
 - edit them
 - disable their accounts 

So that's **users** part of the problem which I can see is workable: we can build something on that and it will work in a real system. Some example code from this at he bottom here. It's work in progress, we're not close to production with this yet!

## 2 roles
Not looking so good here. I'm going to need to be able to assign roles to those users, and also to edit or delete roles, especially the ones I uploaded from the initial template!
1. I managed to create some roles with the JSON upload. I can't edit them by re-uploading that though, but I can add more roles. Which I can't then get rid of! 
2. I found the `/public/roles` API interface and I can list roles using that and the approach as per users above. The API paths seem inconsistent - roles are at `/public/roles`, users (who must use those roles...) are at `/users`.

### 2.1 delete a template role
3. I tried the simplest thing which is to delete one of the unused roles, say `friend-maker`. 
I'm using the same code as for deleting a user - DRY and all - so it ought to work in principle, but it fails with the error:
     'Given key is expected to be array according to schema ([realmId+name]) but was a string'
  
I'm not sure what that's asking for exactly. This must be possible (and the error doesn't contradict that).
I can't put an array in the url. The docs make it sound like `realmId` isn't needed for rlm-public, and my user is my super user of course.

 I've tried every way I can think of, like but nothing works.:
 'https://zlil*.dexie.cloud/public/roles/[rlm-public+friend-maker]'
 'https://zlil*.dexie.cloud/public/roles/[rlm-publicfriend-maker]'
 'https://zlil*.dexie.cloud/public/roles/rlm-publicfriend-maker'

The docs say:
~~~
/* DELETE method deletes any object in given table that matches the given primary key.
 * If primary key is compound, the JSON representation of the key shall be given.
 * Always encode <table> and <primaryKey> using URL encoding (encodeURIComponent() in JS).
 */
 ~~~
I tried various combinations of encodeURIComponent() but there's nothing here which would need escaping anyway. I'm pretty sure the URI MUST be a string, but the error message says it's after an array.  I could JSON.stringify() it... 

A [DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) request can have a body, is that what I need? I don't think so - it's saying that it has a string (what string, from where?), and it doesn't like it. 

Does anyone have an example of a successful role delete?

----

## 3  /user endpoint example code which works
I'll happily post examples of successful user CRUD stuff. 
- This can (and will!) be optimized once I have the whole thing down. 
- Note I strictly validate the email address so I know I can pull a [cached] SU token for it safely.
- wretch is just fetch with some sugar. It works fine in this case for users.
~~~
// This one works with for example path=`/users/emailAddress`
// If you're patching a user then `data` is an array with a single entry which has to 
// be an object with the changed fields in it.
export const post = async (path, editorsEmail, data) => {
	// Editing... Needs an SU access token, so.. get that 1st.
	const accessToken = await getSuToken(editorsEmail, cache)
	const r = await wretch(`https://${PUBLIC_DEXIE_DB}`)
	 	.headers({'Authorization': `Bearer ${accessToken}`})
		.url(path).post(data).json()
		.catch(error => {
			// It returns html if it doesn't work ... parse it out
			let msg = stripHTML(error.message)
			throw new Error(msg)
		})
}
// Get endpoint JSON for entity
export const get = async (path, email) => {
	const accessToken = await getSuToken(email, cache)
	const r = await wretch(`https://${PUBLIC_DEXIE_DB}`)
		.headers({'Authorization': `Bearer ${accessToken}`})
		.get(path)
		.json()
}
// Delete entity. Works for users, not roles though!
export const del = async (path, email) => {
	const accessToken = await getSuToken(email, cache)
	const r = await wretch(`https://${PUBLIC_DEXIE_DB}`)
		.headers({'Authorization': `Bearer ${accessToken}`})
		.delete(path)
		.catch(error => {
			console.log(error)
			let msg = stripHTML(error.message)
			throw new Error(msg)
		})
}
~~~

**Comment by dfahlander** [comment]
Roles table has compound keys [realmId+roleName]. The url part that represent the key should then be the json representation of the array [realmId, roleName] with urlEncoding on top.

Conceptually:

DELETE `/all/roles/${encodeURIComponent(
  JSON.stringify(
    ["roles","friendMaker"]
  )
)`

**Comment by phil-w** [comment]
Thanks!

That's a different path (from that in the docs which was `/public/roles`), but it doesn't error out, so some progress!
An example path is:
`/all/roles/%5B%22roles%22%2C%22readonly%22%5D`

That returns as JSON an empty array `[]`, but I refresh my roles table (via `/public/roles` or `/all/roles`, both work the same) and it doesn't update... I think delete isn't working for me.

**Comment by dfahlander** [comment]
Sorry, the example was wrong - first argument in the array is the realmId not the table, my fault. I just updated my sample

**Comment by Wolfhergang** [comment]
@phil-w Are you considering on your use case that everything on **rlm-public** is completely.... well.... public?

That means a user just needs your particular db url to get access to all the data (read only of course but still, everything is available through API or a small Dexie Cloud local setup)

Asking because I..... neglected that and now I have to migrate all the data to a new realm hehe...

You can test by just doing a GET request to https://[YOUR_DB_ID].dexie.cloud/public/[ONE_OF_YOUR_COLLECTIONS]

You should see all the collection's data without an auth header set

**Comment by phil-w** [comment]
Thanks for the doc fix, which allowed me to test first the fail case (always the right way!) and then fix & test the other path. That now works. I can now delete the roles I don't want from the UI. I don't need to create them because I can already do that via JSOn upload. Don't want to write UI I don't need (and have to secure!).

>...  Are you considering on your use case that everything on **rlm-public** is completely.... well.... public?
> That means a user just needs your particular db url to get access to all the data (read only of course but still, everything is available through API or a small Dexie Cloud local setup)
> 
> Asking because I..... neglected that and now I have to migrate all the data to a new realm hehe...
> You can test by just doing a GET request to https://[YOUR_DB_ID].dexie.cloud/public/[ONE_OF_YOUR_COLLECTIONS]
> You should see all the collection's data without an auth header set

No! I just haven't got that far yet! I figure if I can't create users and have roles then I can't use it anyway, but it looks like I shall probably get there with the users and roles - just one more step (assigning roles to users and removing them...) and then I can move on from that. 

 So I think that means that _I will need multiple realms_, because users are obviously going to need private data in my application. Assuming that's possible, I'll keep going (next task: work out how to assign a role to a user.
 
 Please shout if that makes no sense, @as I'm wasting my time if it doesn't fit in here.

**Comment by Wolfhergang** [comment]
@phil-w Yeah you're good, just take into consideration that the roles are created for a specific realm, so you might need to eventually recreate whatever roles you are going to need linked to your main realm

You can absolutely work with just one realm if everything needs to be shared and protected behind an auth screen, just make a single realm and link everything (including roles) to it.

Think of realms as regular database, each realm has its own data, owner, roles, even tables and all realms but the public one need authentication [as any database should! right?]; Any user can be added (as a member) to a realm, that provides them with read access and you add roles (again, on the members collection) to allow write/delete and finally, every user has its own "db" [aka private realm] linked to its account if they are authenticated, so if you want them to have private data you can allow them to write to their personal realm and even share it with other users.

there are some use cases for using the public realm, like using it to hidrate backend configurable stuff on an offline app, but you are usually going to want a shared "private" realm for your data.

Users are backend only and realm independent so you are good on that.

**Comment by phil-w** [comment]
@Wolfhergang, thanks! I'll re-read multiple times that when I get to that point!  Perhaps this should be a discussion?

- I want my user's data to be shared between sign-ins of that user across multiple devices, and to be inherently backed up in the cloud, but it's going to be private to that user, not shared with others. So that's the user's `private realm` I guess. They are not going to be sharing it with other people, ever. 

- There will probably be some "global data" which I'll maybe put in IndexedDB - look up tables for example. That sounds like a `shared private realm`. 
- I can see no reason I'd ever want `public`  access to anything in there at all.

----
I now have `role deletion`; `request authentication`; and `super user access via proxy server` running. Had some problems with Android native, where the "origin" for the JWT is `https://localhost`, so my call to `/token/validate` needs to first decode the Jwt to get the actual origin out of it, then put that in the fetch for the validation of the token.

- A possible improvement to `[Wolfhergang](https://github.com/Wolfhergang)` would be that if I don't specify `origin`, assume I don't care and validate it anyway. 

If it helps anyone, I mean:
~~~
const claims = jose.decodeJwt(key)
let origin = claims.origin

const r = await fetch(`https://${PUBLIC_DEXIE_DB}/token/validate`, {
  method:'GET', headers:{ 'Content-Type': 'application/json', 'Authorization': bearer, 'Origin': origin }
})
if (r.status === 200) {
  token = await r.json()
  ...
~~~

**Comment by dfahlander** [comment]
> ... there is a new-ish Slack channel that might be used for this kind of discussions and quick questions, that depends on @dfahlander plans for it.

Yes, [here's a link to the new slack channel for dexie-cloud](https://join.slack.com/share/enQtNzM2MzI0NTY3ODM4OC01MDdjYTIyYzU0N2JjZTcwOGU1MDM1YWI0MGE3Yzg2N2VhODYwNjFhZTU3NDRkNjU4NzllMDc5YWRiOGEwOTA5?cdn_fallback=1). The link will expire in 14 days. You're welcome to connect. I'm still trying out how to use Slack for this purpose.
