### ISSUE TITLE
Parameter scopes missing, but it's not

### ISSUE THREAD

**Issue by phil-w** [dexie/Dexie.js#2023]
I'm trying to get a user to "elevate their own privilege" (so they can do stuff like manage users etc). 
To do that the user needs to request a "super user" token, which in turn requires "secrets", so will ultimately need to be done with some care. For now I have a test harness, so that's not an issue and I have free (and secure) access to the secrets I need.

The man page for this is [here](https://dexie.org/cloud/docs/rest-api#scopes).

![image](https://github.com/dexie/Dexie.js/assets/4639007/5991f32e-e4cf-4ea2-8508-3a9da633ccb9)

####  Based on that, here's my actual payload in Brave
![image](https://github.com/dexie/Dexie.js/assets/4639007/45a8acb4-d39f-4a31-b628-54e79359681d)
The redacted fields look correct to me.

#### And Dexie Cloud's response...
`Parameter scopes missing`

I think I'm using the correct format, but presumably not. I've tried it a bunch of different ways around. Does anyone have a working sample for this? I think I can't get the source for the endpoint so I can't work it out that way.

- I have the bearer token (for the ordinary signed in user) in there. I can test that is good with for example the /my endpoint, so it's not that being incorrectly reported as a missing scope.

**Comment by dfahlander** [comment]
Check that you have header "Content-Type: application/json" and that the request comes with a Content-Length representing the number of bytes sent.

**Comment by phil-w** [comment]
Content type is wrong, confirmed kill on that. My bad.

**Comment by dfahlander** [comment]
*SIDE NOTE: I just updated the docs about another endpoint that can validate our JWT tokens if that would be useful in this scenario:  https://dexie.org/cloud/docs/rest-api#tokenvalidate*

**Comment by phil-w** [comment]
Actually that is going to be helpful, as I'm going to have to build a proxy to hold the secret and I'll need to validate "who can use that proxy". I was going to decode the JWT to see what was in it and all, but an end point will allow me to determine the user ID, and I will hard code in that [secure server endpoint] allowed users. 

So I'll use the proxy to acquire the "super user token", and then I can get on and create roles & assign them etc.

**Comment by phil-w** [comment]
later...
https://dexie.org/cloud/docs/rest-api#tokenvalidate works. However I can't use it in my proxy as I get:
` Token verification failed: JWT origin mismatch. Expected 'Origin: http://localhost:5173' but got 'Origin: undefined'`
Which is fair enough. The RFCs reckon I can't spoof origin and I expect that's correct.

----
On the other hand I can always use a generic JWT library to validate & decrypt the JWT, as I have the secret in my proxy server ( I need it to upgrade my "scopes").  

So my steps will be:
1. sign in user's client and get standard access token data including JWT
2. hit my proxy server, passing that JTW to it as a bearer token. 
3. Proxy decrypts & validates the JWT with the secret it securely holds. 
At that point my proxy server knows the user's ID.
4. If user is whitelisted and passes various other tests, I can then request a second token from Dexie's server with scopes sufficient to create roles.
5. I pass that second token back to the client, which can use the token with the highest privileges and assign users to roles, which is where I need to go. 

That may fail with the same error as `tokenvalidate` , but until I try I don't know.

---
An alternative approach could be to write a separate "development tool" which could create roles and manage users, but if that's the only way to do it, then I need to look elsewhere; these aren't going to be managed by developers.

**Comment by dfahlander** [comment]
You need to pass an origin header that is whitelisted using the cli whitelist
