### ISSUE TITLE
validating client tokens

### ISSUE THREAD

**Issue by phil-w** [dexie/Dexie.js#2025]
- I let Dexie Cloud create cloud tokens and those work as intended. 
- I also have a separate server I use for other things. 

I want to pass the JWT obtained from Dexie Cloud and stored in my client to my private server, and then use that to determine "who the user is". That is, I need to (a) check the token signature; (b) decode the token; (c) extract the user ID from it.

This is how I'm doing it:
https://dexie.org/cloud/docs/rest-api#tokenvalidate

## In Development
That works fine if I'm running a client connected to a dev server, with server code as below. I cache the results carefully. 
- Note use of "origin", without which it fails.
- `origin`  = `http://localhost:5173`
- web/mobile clients access this and it works as intended/ expected. 
~~~
const r = await fetch(`https://${PUBLIC_DEXIE_DB}/token/validate`,
   {  method:'GET', headers: { 'Content-Type': 'application/json', 'Authorization': bearer, 'Origin': origin} } )
~~~

## In Production
- `origin` = `https://ApplicationName.netlify.app/`, and I get the following error (I blanked the details):
- fails at server with: `Token verification failed: jwt audience invalid. expected: https://zuu**.dexie.cloud or zuu**`

 - Fair enough: it checks "origin", and `https://ApplicationName.netlify.app/` is different from those it expected, which are likely the "audience" values. 
 - I also that audience values in dev and production are different. I'd guess there are multiple Dexie Cloud servers in some balancing config, and in the two scenarios (Dev, Prod) I'm unlikely to be allocated the same machine. 

### Attempted Fix: hard coded correct expected origin into request
- Same problem, same error. 
- I added some trace to show the actual origin I'm using and it's definitely one of the two required:
 ~~~
Validate via zuu***.dexie.cloud with origin = https://zuu**.dexie.cloud
Token verification failed: jwt audience invalid. expected: https://zuu**.dexie.cloud or zuu**
~~~
- I tried it with the other audience with a similar failure.

## Ideas?
I just want to check the signature and get the userID plus the expiration date out of it.  Any ideas? 
- Could `/token/validate` return a list of errors and a list of the good stuff too? I mean, maybe knowing that the audience is wrong is useful, but I don't care about it in this case, and I do care about the other stuff. I can manually check the jwt with jwt.io and it reads/ sig-checks fine.
- I can probably ignore this error; I don't care about it, but I still need the other data out of the token, so that's not helping much.

**Comment by dfahlander** [comment]
The audience is the database id or database url. Maybe you have two different databases - one for prod and one for test? You need to send it to the /token/verify endpoint of the same database that created the token

**Comment by phil-w** [comment]
Thanks. If I manually copy the client's accessToken from the client browser and paste it into https://jwt.io/ I can see the audiences there, so I know they are  `aud: [   "https://z*.dexie.cloud",   "z*"  ],` where the `z*` bit changes over time as I'd perhaps expect. 

So I guess I need to use those values as my "origin". They're not ... easily accessible. I can decode the token on the server (not validate) using a JS library like jsonwebtoken , and extract the actual audiences from that. Then, I can put those values in the "origin" field. Ok, I'll try that:

1. On server, use jsonwebtoken to extract the audience fields from the incoming user token.
2. Pass that same token *plus* one of those or maybe the entire `aud` array in as origin. 

Then it should work. I can try also using jsonwebtoken on the server with the secret I have there to validate the token myself. Does using Dexie to validate these give me anything additional, as I already have that secret safe on that server as I use it to obtain other tokens (eg for Super Users).

**Comment by phil-w** [comment]
> The audience is the database id or database url. Maybe you have two different databases - one for prod and one for test? You need to send it to the /token/verify endpoint of the same database that created the token

Yeah.... This is likely what's happening:

1. I "point my system" to a DEV server and sign in, receiving a jwt. 
I can see the origin and audience claims in the jwt by decoding it - those were set, by Dexie for my DEV box.

2. Eventually I point the same client browser at the PROD server.
It has local "session" in which I have stored... the accessToken, which us unchanged. 

3. Then I hit the PROD server... 
That validates the signature on the token carried with the request and it barfs. 
`Token verification failed: jwt audience invalid. expected [the Dexie servers assigned to your DEV IP address]`
 
**Even** if I extract the actual audience or origin from the token, and put those values into the Dexie validation request, it fals exactly the same. => I think Dexie Cloud validation is validating (1) the token signature etc; and also (2) that the request comes from the place [IP address?] the token was originally assigned to. Is that right? The error actually means:
 'You're trying to validate a token issued for the Dexie server at IP address xxxx from the IP address yyyy and that's not allowed'

If so:
-  that will probably work if I make sure I sign out and back in again... I'll try that...
- it might help if a slightly different error message was used in the "you switched from staging to prod and forgot to sign out" case. If that's what it is.
