### ISSUE TITLE
/token/validate with mobile devices

### ISSUE THREAD

**Issue by phil-w** [dexie/Dexie.js#2028]
`/token/validate` works fine for me on web. I have to decode the jwt to deduce the "origin", then feed that origin to the endpoint on dexie.cloud, but if I do that, it works fine. Web is good. The endpoint, on web, is the same as it is for the client token, viz https://myEndPoint.dexie.cloud. I'm not sure if that's by chance, but the client always seems to use myEndpoint.

## Problem on mobile: audience is not my server!
On mobile I can't make it work. 

- There, Android uses https://localhost as a "server". My server can't validate anything passed up from mobile, whining that the audience for the token doesn't match the server I'm asking to do the validation. That's correct. But I can't control the "audience" in the mobile client token. So it can't work.

- I wrote some code to pull the audience out of the token from the mobile device, and then tried to validate against _that_ server instead. It is always a subdomain of Dexie, so as secure as anything else there. Except that doesn't work either. It fails with a fetch error as below, which I don't understand:
~~~
   [cause]: Error: getaddrinfo ENOTFOUND https
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
        at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -3008,
      code: 'ENOTFOUND',
~~~

#### I reckon that's a defect: mobile tokens should be validatable too
My suggestion, taking these two issues into account, would be that the endpoint `/token/validate` should work like the jsonwebtoken library does: 
 - If the caller doesn't specify `audience` or `origin`, the validation should not barf when they are not the same as the host.
 - Instead, the endpoint should just validate the token.
 - The caller can check the audience and origin or anything else once the token is validated, if necessary (it's irrelevant in this case).

**Comment by dfahlander** [comment]
It's a limitation that we need the origin header in the validation call - there's no security reason, but it's a limitation we currently have to live with. The origin header must just be a whitelisted origin for the database you are quering - you do not need to pass the origin from the caller. You could hard code a value of the "origin" header you send to /token/validate. Just make sure it it is whitelisted on your database.

**Comment by phil-w** [comment]
Origin I've got working as above. I'm pretty sure that the value was mandatory when I built it.

## Audience
This is where I'm unable to make things work, specifically with mobile clients whose origin are `https://localhost`.

1. My **Validating Server** is requesting `/token/validate` from my public Dexie Cloud server, say `z1.dexie.cloud`. That sub-domain name is used for the Dexie API etc through a single JavaScript constant `PUBLIC_DEXIE_DB`.
2. My mobile client is Android native, not web based. It reports its "server" as `https://localhost` . I have debug code there which shows the JWTs it gets from Dexie have audience of (say) `['https://z2.dexie.cloud', 'z2.dexie.cloud'].` 
3. When the Android client contacts my  **Validating Server** it passes the Dexie JWT in the Auth header. 
4. The  **Validating Server** uses `/token/validate` on PUBLIC_DEXIE_DB - `z1.dexie.cloud` to attempt to check the signature on the JWT, because I want to rely on that JWT to identify the user securely at that server.
5. This errors out

### Server Side Log Trace During Validate Attempt from Android Client
Here's a  partially redacted server-side log trace. This is what I repeatedly get when trying to run `/token/validate` on my server from an Android client. Web clients from multiple servers all work perfectly.

~~~
authorizationHandle https://*.netlify.app/api/user/test/success
    validate on zuu*.dexie.cloud origin: https://localhost   
~~~  
- Note `localhost` origin indicates  "request from Android"
- Requests from web clients all work fine, and use the expected audience set, _which is the same as PUBLIC_DEXIE_DB_ .
  
 The log continues...
~~~  
validate via Dexie failed (401) Token verification failed: jwt audience invalid. 
expected: https://zuu*.dexie.cloud or zu* {
  ...
  origin: 'https://localhost',
  ...
  aud: [ 'https://zlil*.dexie.cloud', 'zlil*' ],
  iss: 'https://dexie.cloud'
}
~~~  

The key thing is that the token which PUBLIC_DEXIE_DB issued to my Android clients has audience `zlil*.dexie.cloud`, but my server, also talking to PUBLIC_DEXIE_DB, gets told that Dexie expects `zuu*.dexie.cloud` in the audience field.

As I don't / can't control that audience field for the Android client, either:
- this just won't work
- Dexie could issue a token to the Android client which has the same audience as the one it issues to web clients.
- `/token/validate` needs to either ignore audience, or report on it, or allow me to feed in an audience in the same way I can pass in an origin.

**Comment by phil-w** [comment]
Ok, this was user error, I was mangling the audience server address.
To validate a Dexie Cloud JWT _from mobile_ via a proxy server I need to:
1. decode the jwt using a js library for example `jose`
2. pull out the token `audience` and `origin` fields from the token
3. send the `/token/validate` GET to the audience server.

On mobile the audience can be different from web. Are ALL subdomains of dexie.com, so it's safe to pull the domain from the token, then hit that. The zeroth entry is the server in all I've seen.

~~~
const r = await fetch(`${claims.aud[0]}/token/validate`, {
  method: 'GET', 
  headers: { 'Content-Type': 'application/json', 'Authorization':`Bearer ${accessToken}`, 'Origin': claims.origin }
})
if (r.status === 200) {
  token = await r.json()
  if (token.valid) {
...
~~~

### user error
