### ISSUE TITLE
Dexie Cloud not syncing yet in a Tauri App on Windows

### ISSUE THREAD

**Issue by retotito** [dexie/Dexie.js#2037]
Hy there does anybody have some experience with Dexie-Cloud in a Tauri App.
I have installed a Tauri App on Windows.
Unfortunately it does not work with the Dexie-Cloud, beccause the Login is not showing up and it does not sync from the cloud.
I don't know if this is a mater of whitelisting, or some setting on the Tauri App side.

Thanks for Suggestions

**Comment by retotito** [comment]
npx dexie-cloud whitelist https://tauri.localhost/
this solves the issue :)

**Comment by nickrmurphy** [comment]
In case anyone else stumbles upon this, I was having the same issue while running Tauri + Dexie in the iOS Simulator. Running `npx dexie-cloud whitelist tauri://localhost --force` resolved my issue
