### ISSUE TITLE
Sync changes with purpose full for expired licenses 

### ISSUE THREAD

**Issue by MuffinTheDragon** [dexie/Dexie.js#2038]
For my app I create a default user object on initial load (if one doesn't exist) so that the app is useable without an account.

If I then login as a user with an expired license, I get a 403 sync error. It seems like this is because there's already data in the local db, but even if I specify the intent to be pull, it still gives the error. 

Will doing `await db.cloud.sync({ purpose: "pull", wait: true })` not fetch changes if the local instance doesn't match the cloud instance? Is there a way to do a force pull for users with expired licenses?

**Comment by dfahlander** [comment]
The following line:

```ts
await db.cloud.sync({ purpose: "pull", wait: true }) 
```

...will both push and pull regardless. When `purpose` is "push", it would not do anything unless there were unsynced changes pending, but with purpose "pull" it will sync regardless. It still pushes any local changes on every sync.

If the response is 403, you should be able to inspect the reason in devtools along with the response.

Users with expired licenses cannot sync except for downloading (pulling) the data from the server if their local database is empty (an initial sync). The reason for that they can still sync with this precondition is that they should always be able to restore their client from the cloud data.

An expired evaluation user can continue working locally with sync automatically disabled (unless the app calls db.cloud.sync() explicitely, but that typically results in a 403 in this case).

There are three alternatives for expired evaluation users:

1. Continue using the app offline, without sync.
2. Convert to 'prod' user (must be done by the database owner using https://manager.dexie.cloud or the REST API).
3. Delete all data for the user to start over (via REST api DELETE /users/<userId>) and delete local database (db.delete()).

**Comment by MuffinTheDragon** [comment]
Thank you! I didn't realize it would push regardless
