### ISSUE TITLE
Waiting for data sync before running useEffect

### ISSUE THREAD

**Issue by MuffinTheDragon** [dexie/Dexie.js#2041]
I have a useEffect hook that runs after initial render and does some computations to modify the data.

An issue I noticed is if the client was offline when new changes were pushed, then comes online, the computation is done on stale data and breaks consistency.

I tried explicitly calling sync beforehand, but it doesn't pull anything as the socket connection hasn't been opened yet. So the computation happens before the data is updated: 
![image](https://github.com/user-attachments/assets/7b1e26af-291c-46f2-a083-daf29caaec35)

Is there a way I can wait for the connection to open and it to sync before rendering? Not sure what the best way would be to handle this

**Comment by dfahlander** [comment]
There is [db.cloud.events.syncComplete](https://dexie.org/cloud/docs/db.cloud.events.syncComplete). This is a pure event that emits at the time of a completed sync operation

You also have [db.cloud.syncState](https://dexie.org/cloud/docs/db.cloud.syncState). This one can be observed using [useObservable()](https://dexie.org/docs/dexie-react-hooks/useObservable()) to know when sync state is 'connected':

```ts
function MyComponent() {
  const syncState = useObservable(db.cloud.syncState);
  useEffect(() => {
    if (syncState.status === 'connected') {
      // Do things when connected.
    }
  }, [syncState.status);
}
```

**Comment by MuffinTheDragon** [comment]
I was initially trying `syncState.phase` but it ended up re-rendering too many times.  This worked much better though, thanks!
