### ISSUE TITLE
token updated, but how to get it?

### ISSUE THREAD

**Issue by phil-w** [dexie/Dexie.js#2042]
As per the enclosed trace, I'm struggling to get hold of an access token which I know Dexie Cloud has updated. If I refresh the page, the expired token is refreshed correctly, but I can't get the refreshed token back out of Dexie Cloud any other way.

I've read a lot of tickets here, and I've tried most combinations remotely likely, but I cannot get this to work. My current code is something like:

~~~
await db.cloud.sync()
...
await db.open()                     // As per various tickets here as I'm using Sveltekit..
let usr = db.cloud.currentUser      // Then get user to get user token.
let token = usr._value.accessToken  // ... but it's not been updated, it's the old one!
~~~

1. If DexieCloud gets to `Sync is needed: false` then it _must_ have authenticated to get that information, so it does have the updated token inside of it by that point. 
2. But the token I get above  is still out of date! 

A brutal full-page refresh tears everything down and puts it back, and of course I can get the updated token at that point. It's not acceptable to do that once per hour though, because typically the user will leave the system then come back only now and then, so effectively _every time_ they try to use it, it's going to do this ugly old page refresh.

## Is there a way to get Dexie Cloud to share the new token with my code?

![image](https://github.com/user-attachments/assets/8a574cf3-7b06-4673-a255-7895b770a78e)

**Comment by dfahlander** [comment]
It must be a bug that we don't update the db.cloud.currentUser correctly. The fresh value of the token can be found in:

```ts
db.$logins
  .get(db.cloud.currentUserId)
  .then(login => login.accessToken);
```

**Comment by phil-w** [comment]
Thanks - I will try that & report back.

**Comment by phil-w** [comment]
Slam, dunk. That fixed it - thanks.
