### ISSUE TITLE
What is expected support period for v3? (Especially for security patches)

### ISSUE THREAD

**Issue by marclaporte** [dexie/Dexie.js#2048]
Congrats on v4! https://github.com/dexie/Dexie.js/releases/tag/v4.0.1

I am wondering if v3 will continue to be supported for a little while? (Especially for security patches)

Thanks!

**Comment by dfahlander** [comment]
Trying to keep a previous major supported for critical security issues 2 years after any other major release. Dexie 4 was released 2024-03-26 so dexie@3 will be supported until 2026-03-26.

Current supported versions are available in [SECURITY.md](https://github.com/dexie/Dexie.js/blob/master/SECURITY.md).
