### ISSUE TITLE
Microsoft Edge Third-party cookie warning

### ISSUE THREAD

**Issue by CrashSensei** [dexie/Dexie.js#2050]
When every I user Dexie Cloud the console logs multiple warnings: 
Reading cookie in cross-site context will be blocked in future Microsoft Edge versions
![image](https://github.com/user-attachments/assets/fd19a5a1-4d2f-4c6c-a6ec-08431af447c7)

The details of the warning are:
Cookies with the SameSite=None; Secure and not Partitioned attributes that operate in cross-site contexts are third-party cookies. In future Microsoft Edge versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.
![image](https://github.com/user-attachments/assets/8d6011db-e7a6-474a-9a14-6d8fbdd8f784)

I do not seem to see anything on Dexie.js or GitHub addressing this potential issue.

I am using Dexie.js and Dexie Cloud inside the content script of a Chrome/Edge extension.  I am assuming that, if there is no fix for this warning, then the workaround would be to move all Dexie calls to a background/service worker script?

**Comment by dfahlander** [comment]
Thanks for notifying us about this. These cookies are generated by our Microsoft Azure infrastructure for load balancing but are not crucial for Dexie Cloud to function. The stickiness that this these cookies enables isn't needed for anything else than to control API rate limits. When the browser depricates them, Dexie Cloud will continue functioning exactly like before, but might allow a higher API rate-limit than anticipated.

I'll see what we could do to configure Azure app services differently, or if we could skip generating the cookies though, to find another way to control API rate limits.

**Comment by CrashSensei** [comment]
Thank you, that certainly alleviates my concerns.
