### ISSUE TITLE
Parallelism of `toArray` within a single transaction

### ISSUE THREAD

**Issue by BlakeSearlSonocent** [dexie/Dexie.js#2053]
Hi

Dexie version: `4.0.8`
Browser: Chrome

I'm looking at the performance of a web application. In this app, on startup, we read from a bunch of IndexedDB tables using `store.table.toArray`. I have found that this can be slow, likely because some tables can have 10s of thousands of rows.

Therefore, I've been looking in to whether it is possible to parallelise these read operations.  The [documentation](https://dexie.org/docs/Dexie/Dexie.transaction()#parallel-operations-within-same-transaction) suggests that this should be possible within the same transaction, but I am finding that the `.toArray` operations are running in sequence.

Below are the experiments that I have run:

`tableA`: 0 rows
`tableB`: 12 rows
`tableC`: 6000 rows

### Single transaction
Code snippet:

```
db.transaction('readonly', db.tableA, db.tableB, db.tableC, async () => {
  db.tableC.toArray().then(() => console.log('tableC'))
  db.tableB.toArray().then(() => console.log('tableB'))
  db.tableA.toArray().then(() => console.log('tableA'))
})
```

Output:
```
tableC
tableB
tableA
```

In this case, if they were running in parallel, I would expect the output to be the following:

```
tableA
tableB
tableC
```

### Separate transactions
Code snippet:

```
db.transaction('readonly', db.tableC, async () => {
  db.tableC.toArray().then(() => console.log('tableC'))
})

db.transaction('readonly', db.tableB, async () => {
  db.tableB.toArray().then(() => console.log('tableB'))
})

db.transaction('readonly', db.tableA, async () => {
  db.tableA.toArray().then(() => console.log('tableA'))
})
```

Output:
```
tableA
tableB
tableC
```

To me, this appears to be running in parallel - the smallest table is now finishing first and the largest table is finishing last

### Same transaction, different operation
The thought here was to verify that other operations do run in parallel within the same transaction.

Code snippet:

```
db.transaction('readonly', db.tableC, db.tableB, async () => {
  db.tableC.each(() => console.log('tableC'))
  db.tableB.each(() => console.log('tableB'))
})
``` 

Output:
```
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableB
tableC
tableC
tableC
...
```

So `.each` does seem to run in parallel within the same transaction.

### Summary
I'm finding that:
- `toArray` does not run in parallel for multiple tables within a single transaction
- `toArray` does seem to run in parallel for separate transactions
- `each` does run in parallel for multiple tables within a single transaction

Does anyone have further information on this and whether it is expected that `toArray` will block in this way?

**Comment by dfahlander** [comment]
The IndexedDB specification requires every request to be queued and answered in order on the same transaction. When using a simple toArray() query, we use IDBIndex.getAll() internall which is one single request. This is the fastest way to query IndexedDB. `each()` on the other hand opens a cursors and performs one IndexedDB request per row.

The absolutely most performant way of querying IndexedDB is using IDBIndex.getAll() or IDBObjectStore.getAll(). This is also what dexie uses internally with simple toArray() queries (equals, above, below, between etc as well as startsWith(), but not `or()`, `equalsIgnoreCase()`, `filter()`/`and()`, etc. `getAll()` supports a limit but not an offset.

**Comment by BlakeSearlSonocent** [comment]
@dfahlander that makes a load of sense. Thank you for the clear explanation.

I will run some profiling tests around multiple transactions to see if there is any performance benefit, but I think it seems unlikely that there will be.

**Comment by BlakeSearlSonocent** [comment]
Creating multiple transactions has improved our performance, but may be a case by case thing. It also comes with the risk of not reading from the same version of the data, which could be important.

Thanks for the help here.

**Comment by dfahlander** [comment]
> Creating multiple transactions has improved our performance, but may be a case by case thing. It also comes with the risk of not reading from the same version of the data, which could be important.
> 
> Thanks for the help here.

Thanks for the feedback. It's normally recommended to use fewer transactions, but as you say, this may vary from case to case - when it's important to not block, it could probably be better with separate smaller transactions than a few large and blocking transactions.
