### ISSUE TITLE
2 samples not functional because "Typeson is not defined"

### ISSUE THREAD

**Issue by Autsider666** [dexie/Dexie.js#2055]
The [Samples](https://dexie.org/docs/Samples) page contains 4 jsfiddle examples, but 2 of them don't start out of the box because of the same error `"<a class='gotoLine' href='#92:12'>92:12</a> Uncaught ReferenceError: Typeson is not defined"`:
- [Storing Binary Date](https://jsfiddle.net/dfahlander/kgsbbhca/)
- [Preserving custom types using typeson](https://jsfiddle.net/dfahlander/qacL14tu/)

**Comment by dfahlander** [comment]
Thanks! I've removed those two samples. The Typeson library has evolved a lot since those samples where created and I don't have time to figure out how to use it properly in this case. Don't think these samples are essential anyway.

**Comment by Autsider666** [comment]
I'm probably going to experiment with Typeson one of these days, so I'll add "Update Dexie/Typeson samples" to my nice-to-have list. (If you're interested in having them updated at least)

You're 100% right that it's not essential to Dexie, but pointing out the library in the docs with a working sample could provide people with a very useful abstraction layer. Not having to think about (de)serializing Date objects, for instance, would help me a lot already in my project.

**Comment by dfahlander** [comment]
IndexedDB has a built-in support for storing Date, Blob, ArrayBuffer even without Typeson, but to serialize other types, like custom classes other types not supported by [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), it could be useful.
