### ISSUE TITLE
Cannot read properties of null (reading 'substring')

### ISSUE THREAD

**Issue by iamjuanguillermo** [dexie/Dexie.js#2057]
When a user receives an email with invitation and accepts it, they are redirected to a page where the message is:

`Cannot read properties of null (reading 'substring')`

That has been happening since this morning. I haven't changed anything in the code.

**Comment by dfahlander** [comment]
I see lots of these same errors in the server log though so there is probably some situation where it happens. If it happens again please feel free to forward me the invite mail that leads to this error.
