### ISSUE TITLE
useLiveQuery does not update when multiple items are deleted

### ISSUE THREAD

**Issue by wesbos** [dexie/Dexie.js#2067]
hello! I have a query like this:

```js
const images = useLiveQuery(() => db.images.reverse().toArray());
```

When I delete a single item, it is reactive and updates:

```jsx
<button onClick={() => db.images.where('id').equals(2).delete()}>Delete</button>
```

But when I try to delete multiple items at once, it deletes the item, but the query does not react:

```jsx
<button onClick={() => db.images.where('id').above(0).delete()}>Delete</button>
```

I thought it may be related to: https://github.com/dexie/Dexie.js/issues/2021 but it seem anything that deletes more than one record doesnt cause reactivity

**Comment by imarinoff** [comment]
it seems that dexie observable in general does not react well to bulk actions.
On bulkAdd and bulkPut I get:
{
    "name": "DatabaseClosedError",
    "message": "Database has been closed",
    "inner": null
}
and on changes event does not get triggered

console.js:288 DexieError2 {name: 'DatabaseClosedError', message: 'Database has been closed', inner: null}
overrideMethod @ console.js:288
(anonymous) @ table.ts:73
(anonymous) @ promise.js:721
(anonymous) @ promise.js:426
callListener @ promise.js:426
endMicroTickScope @ promise.js:475
Table2._trans @ table.ts:79
Collection2._read @ collection.ts:50
Collection2.toArray @ collection.ts:166
readChanges @ Dexie.Observable.js:317
(anonymous) @ Dexie.Observable.js:290
(anonymous) @ vip.ts:15
usePSD @ promise.js:709
newScope @ promise.js:590
vip @ vip.ts:13
onLatestRevisionIncremented @ Dexie.Observable.js:289
(anonymous) @ chaining-functions.js:74
(anonymous) @ chaining-functions.js:74
(anonymous) @ wakeup-observers.js:11
ignoreTransaction @ dexie-static-props.ts:111
wakeupObservers @ wakeup-observers.js:10
(anonymous) @ override-create-transaction.js:29
Dexie: read _changes
Table2._trans @ table.ts:43
Collection2._read @ collection.ts:50
Collection2.toArray @ collection.ts:166
readChanges @ Dexie.Observable.js:317
(anonymous) @ Dexie.Observable.js:290
(anonymous) @ vip.ts:15
usePSD @ promise.js:709
newScope @ promise.js:590
vip @ vip.ts:13
onLatestRevisionIncremented @ Dexie.Observable.js:289
(anonymous) @ chaining-functions.js:74
(anonymous) @ chaining-functions.js:74
(anonymous) @ wakeup-observers.js:11
ignoreTransaction @ dexie-static-props.ts:111
wakeupObservers @ wakeup-observers.js:10
(anonymous) @ override-create-transaction.js:29
setTimeout
(anonymous) @ override-create-transaction.js:27
(anonymous) @ transaction-constructor.ts:59
(anonymous) @ promise.js:721
callListener @ promise.js:426
endMicroTickScope @ promise.js:475
(anonymous) @ promise.js:544

**Comment by dfahlander** [comment]
> hello! I have a query like this:
> 
> ```js
> const images = useLiveQuery(() => db.images.reverse().toArray());
> ```
> 
> When I delete a single item, it is reactive and updates:
> 
> ```js
> <button onClick={() => db.images.where('id').equals(2).delete()}>Delete</button>
> ```
> 
> But when I try to delete multiple items at once, it deletes the item, but the query does not react:
> 
> ```js
> <button onClick={() => db.images.where('id').above(0).delete()}>Delete</button>
> ```
> 
> I thought it may be related to: #2021 but it seem anything that deletes more than one record doesnt cause reactivity

Thanks @wesbos, I will look into this.

**Comment by dfahlander** [comment]
@imarinoff The DatabaseClosedError happens when the database has been closed and seem to be off-topic for this issue. Please file another issue with a repro for when it happens
