### ISSUE TITLE
undefined is not an object (evaluating 'this.name="BulkError"')

### ISSUE THREAD

**Issue by GravlLift** [dexie/Dexie.js#2081]
So I know this is going to be a frustrating level of detail, but I'm going to log it anyways. Been getting the title error intermittently in my production environments. Stack trace is a single line

```
/node_modules/dexie/dist/dexie.min.js:1:5286
```

which I assume corresponds with [this line](https://github.com/dexie/Dexie.js/blob/d6a73877f3f8fb912e2d2dafb8a93b3837f1de6f/src/errors/errors.js#L86).

Running on Dexie version 4.0.8. Over the past 30 days, I see the following distribution of occurrences by browser:

- Mobile Safari 18.0 - 51
- Mobile Safari 16.1 - 1
- Mobile Safari 17.6 - 22
- Chrome Mobile iOS 129.0 - 4

**Comment by dfahlander** [comment]
Aha! I think I know the reason. Searched through the code base to find if we ever throw or call BulkError without new, but we don't. However, Old dexie docs propose a way to catch errors in a custom way that only works with Dexie.Promise:

```js
db.friends.bulkAdd([...friends]).catch(Dexie.BulkError, error => {
  // Catching bulk errors only.
});
```
This is not compliant with standard Promises who lacks this java-ish way of catching a specific type of error. It would only work on the direct result from the dexie operation and not from a promise from an async function or Promise.all(), who would return a standard promise. A standard promise would instead invoke Dexie.BulkError as a function in case an error happens, resulting in this error being thrown instead.

What you can do is to search your code base for `.catch(Dexie.`. Wherever you find it, rewrite it to be standard compliant.

So if you see something like:

```js
  callSomeDbFunction().catch(Dexie.BulkError, e => {
    ...
  });
```
...then replace it with:
```js
  callSomeDbFunction().catch(e => {
    if (e instanceof Dexie.BulkError) {
       ...
    } else {
      throw e;
    }
  });
```

I'll go through the docs and remove those examples to avoid these kind of issues. Thanks for the issue.

**Comment by dfahlander** [comment]
Closing this. If I was wrong in my conclusion, please reopen!

**Comment by GravlLift** [comment]
Ah yep. That's exactly what's going on. Thank you!
