### ISSUE TITLE
`Table.update()` / `Table.put()` not always working for nested objects

### ISSUE THREAD

**Issue by kennyhei** [dexie/Dexie.js#2092]
Hi, I'm using Dexie with Svelte 5 + TS. Here's my db setup:

```ts
class WorkoutDatabase extends Dexie {
  workouts!: EntityTable<WorkoutGet, 'id'>;

  constructor() {
    super('WorkoutsDatabase');
    this.version(1).stores({
      workouts: '++id, created_at, updated_at, date, workout_exercises',
    });

    this.workouts.hook('creating', (primaryKey, workout) => {
      const timestamp = new Date().toISOString();
      workout.id = getCryptoRandomInt();
      workout.created_at = timestamp;
      workout.updated_at = timestamp;
    });
  }
}

const db = new WorkoutDatabase();
```

Workout objs have basically following structure:

```ts
{
  id: number;
  created_at: string;
  updated_at: string;
  date: string;
  workout_exercises: [
    {
      id: number;
      exercise: {
        id: number;
        name: string;
      },
      sets: [
        {
          id: number;
          reps: number;
          weight: number;
        }
      ]
    }
  ]
}
```

I have issues adding / removing new sets to specific workout_exercise, here's my code for adding new set:

```ts
const workoutsStore = {
  addExerciseSet: async (id, workoutExerciseId, weight = 0, reps = 0) => {
    const res = await db.transaction('rw', db.workouts, async () => {
      const workout = await db.workouts.get(id);
      if (!workout) {
        throw new Error('Workout not found');
      }
      const updatedExercises = workout.workout_exercises.map((we) => {
        if (we.id === workoutExerciseId) {
          return {
            ...we,
            sets: [
              ...we.sets,
              {
                id: getCryptoRandomInt(),
                reps,
                weight
              }
            ]
          };
        }
        return we;
      });

      return await db.workouts.update(id, {
        workout_exercises: updatedExercises,
        updated_at: new Date().toISOString()
      });
    });
    return res;
  },
}
```

After transaction is done and before returning `res`, I have checked with `console.log(await db.workouts.get(id))` that what does the workout object now look like and sometimes it doesn't have the new set object there. I have also tried to do this with `db.workouts.put` or with `db.workouts.update(id, { 'workout_exercises.0.sets': [...] })` but to no avail. It just randomly refuses to commit changes even though the operation is successful.

I was also wondering if the issue is with `const workout = liveQuery(() => db.workouts.get(id))` being out of sync but as I previously described how I debugged the state of workout in `addExerciseSet` before returning `res`, I don't think it's related.

**Comment by dfahlander** [comment]
What if the workoutExerciseId isn't present in the workout_exercises array of the found object. In that case there would be no change afterwards.

**Comment by kennyhei** [comment]
It's pretty much guaranteed that it's present 🤔  tested it to be sure. Also same result with this:

```tsx
const sets = workout.workout_exercises[0].sets;
db.workouts.update(id, {
  'workout_exercises.0.sets': [
    ...sets,
    {
      id: getCryptoRandomInt(),
      reps,
      weight
    }
  ]
});
```
In my UI you can't call `addExerciseSet` function if the workout_exercise is not there so there's always at least 1 obj

**Comment by kennyhei** [comment]
I can try to create codesandbox example later if that would help?

**Comment by dfahlander** [comment]
yes that would be very helpful

**Comment by kennyhei** [comment]
@dfahlander Looked at my code again and this part seemed to be the cause of the issue in my code:

```tsx
// Workout exercise set component

let weight = $state(set.weight || 0);
let reps = $state(set.reps || 0);

$effect(() => {
  workoutsStore.updateExerciseSet(workoutId, workoutExerciseId, {
    ...set,
    weight,
    reps
  });
});
```

So during initial render the effect was called, and the `updateExerciseSet` was doing `db.workouts.get` + `db.workouts.update` without using `db.transaction`. After I applied transaction, it started working. Although I should also check if the `$effect` is even needed at all.

**Comment by dfahlander** [comment]
Great that you found the culprit! Can I close the issue?

**Comment by kennyhei** [comment]
Yes! Let's close it 👍
