### ISSUE TITLE
useLiveQuery not triggering useEffect in functional component

### ISSUE THREAD

**Issue by lukasb** [dexie/Dexie.js#2093]
Apologies if I'm missing something basic about React, but when I run the code below I get these log statements:

pages undefined undefined
pages undefined undefined
mergedPages 298 { object }

The first two log statements don't surprise me, but shouldn't I get another log statement "pages 298 { object }" ?

```
function EditingArea({ userId }: { userId: string }) {
  
  const pages = useLiveQuery(async () => {

    const localPages = await localDb.pages
      .where("userId")
      .equals(userId)
      .toArray();
    const queuedUpdates = await localDb.queuedUpdates
      .where("userId")
      .equals(userId)
      .toArray();

    const mergedPages = [
      ...localPages
        .filter((page) => !page.deleted)
        .filter((page) => {
          const queuedUpdate = queuedUpdates.find(
            (update) => update.id === page.id
          );
          return !queuedUpdate?.deleted;
        })
        .map((page) => {
          const queuedUpdate = queuedUpdates.find(
            (update) => update.id === page.id
          );
          return queuedUpdate || page;
        }),
      ...queuedUpdates.filter(
        (update) =>
          !localPages.some((page) => page.id === update.id) && !update.deleted
      ),
    ];
    console.log("mergedPages", mergedPages.length, mergedPages[0]);
    return mergedPages;
  }, [userId]);

  useEffect(() => {
    console.log("pages", pages?.length, pages?.[0]);
  }, [pages]);```

**Comment by dfahlander** [comment]
Not unless you add/put/update/delete something

**Comment by lukasb** [comment]
When the useLiveQuery returns results for the first time, shouldn't that update the "pages" variable, and thus trigger the useEffect?

Right now the two "pages undefined undefined" log statements are happening because that useEffect is being called twice before useLiveQuery returns. I would expect that when useLiveQuery finishes, pages would be updated and the useEffect would trigger again.

**Comment by dfahlander** [comment]
Yes you're right. I misread what the code actually logged.
Maybe an exception happens in the query? Could you add a try...catch around the entire query and log something in the catch? (or add an [ErrorBoundrary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) in a parent of your component.

**Comment by lukasb** [comment]
Sorry, my mistake, unrelated to Dexie - "pages" being undefined was triggering an error later on that halted execution (but not before the mergedPages logging statement.)
