### ISSUE TITLE
How to prevent automatically changing version?

### ISSUE THREAD

**Issue by budarin** [dexie/Dexie.js#2099]
the database is created in the service worker, and in the application I just want to use Dexia to work with data - not to change the structure and version!
Dexia automatically changes the version, which breaks the logic of the application!

**Comment by dfahlander** [comment]
Not sure if you are referring to the new behavior in dexie@4 that allows changing the schema without updating the db version? If that is the case, the explanation is this:

* IndexedDB forbids to add/delete tables or indexes without specifying a higher version than the previous one.
* Dexie@4 works around this limitation: If the declared schema (tables + indexes) differ from what is installed on the client, it will increment the underlying version of the DB for the user to allow adding indexes or tables.
* If dexie wouldn't do this workaround, you would get an exception instead when changing schema in the same version

Is this the scenario you are referring to?

**Comment by budarin** [comment]
I realized that the schemas and indexes must match completely in order for Dexia not to generate a new version
