### ISSUE TITLE
Dexie Cloud: there is no parameter $1

### ISSUE THREAD

**Issue by leoyli** [dexie/Dexie.js#2102]
Hi there,

Thank you for the great work.  I think I hit some strange error 500 when I calling `https://zkrsa8ppj.dexie.cloud/token` to get the token.  The response shows 500 with message `there is no parameter $1`.  How should I provide the parameter $1?

It was working on yesterday, so I guess it might somehow related to my new subscription 🤔

**Comment by dfahlander** [comment]
Thanks for the report. Could you send the POST data (with secret stripped) that failed?

**Comment by leoyli** [comment]
Hi @dfahlander, 

```
curl --location 'https://zkrsa8ppj.dexie.cloud/token' \
--header 'Content-Type: application/json' \
--header 'Cookie: ARRAffinity=5857638cc5f4f42b8c1b610bb850f3dd88c80e77b0851d628556ed657cd057ed; ARRAffinitySameSite=5857638cc5f4f42b8c1b610bb850f3dd88c80e77b0851d628556ed657cd057ed' \
--data-raw '{
    "grant_type": "client_credentials",
    "scopes": [
        "ACCESS_DB"
    ],
    "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1HCp+VXh/qDU1ZaojSPc\nyPjH09PiPQVTSWAy4vbK0v1hjXAb5ogm89DJMWsC5grmYY/b3kAIdrfjHbwcMiB2\nwhNsPtTcWPGw3HEaByvCccfPyQd3mcO6pgkKJIUWui/RL1ASxySYaCgsv52XLAqD\nYeMCUDAct3usrv5FDea1iN/kQrqlgmGIO3ariKRAfqMg0bJhe9DlbegFoQK6Tpa9\nacW90sTA1D9XcRZuZEUp688Hl7IFwf9cFQmm1DJXGQbxpeiznYeWfbeCyj3g6W+f\ngTE0P1KYrlpO9d1LIcIjTSfg6PtnPC9Xw7M241aClCLofMzDsMyEoxh5WrecTDkH\nUwIDAQAB\n-----END PUBLIC KEY-----",
    "client_id": "mqdhgokpl86a8c5f",
    "client_secret": "_STRIPED_",
    "claims": {
        "sub": "e169d672-6603-4ed4-9842-c06350915b71",
        "email": "leo@beluga.team"
    }
}'
```

I found a workaround.  By keeping the default policy.

<img width="805" alt="Screenshot 2024-11-29 at 5 11 30 PM" src="https://github.com/user-attachments/assets/fda82866-3f7f-42bd-a23d-da6db70f0203">

But ideally I want to set the policy to "Automatically create production accounts for all new users", which seems to be the one is bugged.

**Comment by leoyli** [comment]
I'm testing again using my new db and it still doesn't work when calling the api to get the token for the first time for a new user... Maybe I missed something from here? https://dexie.org/cloud/docs/db.cloud.configure()#example-integrate-custom-authentication. Strangely, if I choose the default option, the new user is working fine. I'm auth using Supabase Edge function, but I can reproduce using postman.

<img width="1667" alt="Screenshot 2024-12-02 at 8 33 16 AM" src="https://github.com/user-attachments/assets/2bb69e63-5f66-45a0-983d-4435da4cbeca">

**Comment by dfahlander** [comment]
The fix for this issue is now in production.
