### ISSUE TITLE
Dexie Cloud: Cannot login to the dashboard

### ISSUE THREAD

**Issue by leoyli** [dexie/Dexie.js#2106]
I'm getting this error, tried different email to get the OTP but it doesn't work.

<img width="1840" alt="Screenshot 2024-12-06 at 8 27 27 AM" src="https://github.com/user-attachments/assets/e31e1a30-a14d-4ee0-bea9-0e9bf93ec9dd">

**Comment by dfahlander** [comment]
Thanks for the report! The system is now working again after reverting a node upgrade that wasn't compatible.
