### ISSUE TITLE
Couldn't import `useLiveQuery` from `dexie-react-hooks`

### ISSUE THREAD

**Issue by JinNguyen96** [dexie/Dexie.js#2109]
I'm using `dexie-react-hooks@1.1.7` for my react project with bun + vite (newest version).
after installing the package, all I have is dist folder with no js file, just type definition:
![image](https://github.com/user-attachments/assets/73f48f8e-3eee-464b-938b-ad0df32c45ea)
so because there's no js file, I couldn't use `useLiveQuery`, please help

**Comment by dfahlander** [comment]
I checked the package on npmjs 'code' tab: https://www.npmjs.com/package/dexie-react-hooks?activeTab=code

Seems it has the required files on version 1.1.7.

Check if you just need to delete node_modules and retry npm install. If that doesn't help, try `npm cache clean --force` and redo npm install.

**Comment by JinNguyen96** [comment]
thank you, after clearing cache from bun, I finally successfully installed the package now, @dfahlander
