### ISSUE TITLE
Broken sourceMappingURL for dexie.min.js

### ISSUE THREAD

**Issue by adi130987** [dexie/Dexie.js#326]
I just started using Dexie.js and I keep getting this console error:

```
Failed to parse SourceMap: http://localhost:8080/bower_components/dexie/dist/dist/dexie.min.js.map
```

I think dexie.min.js sourcemap url is broken:

``` javascript
//# sourceMappingURL=dist/dexie.min.js.map
```

it should be just:

``` javascript
//# sourceMappingURL=dexie.min.js.map
```

**Comment by zebzhao** [comment]
Can you please reopen this? I downloaded the latest rc.1 release from bower and npm and it still points to dist/dexie.min.js.map

**Comment by dfahlander** [comment]
Thanks. Regression bug.

**Comment by lvivski** [comment]
@dfahlander it looks like `sourceMappingUrl` is missing from the latest builds.

production: https://unpkg.com/dexie@3.2.3/dist/dexie.min.js
alpha: https://unpkg.com/dexie@4.0.1-alpha.7/dist/dexie.min.js

**Comment by dfahlander** [comment]
Thanks for reporting. It might be due to the upgraded dev-deps.

**Comment by lvivski** [comment]
[`2.0.4`](https://unpkg.com/dexie@2.0.4/dist/dexie.min.js) seems to be the last version to have `sourceMappingUrl`, starting with [`3.0.0-alpha.1`](https://unpkg.com/dexie@3.0.0-alpha.1/dist/dexie.min.js) it's gone
