### ISSUE TITLE
Can't instantiate two Dexie instances using the same database name

### ISSUE THREAD

**Issue by daviddias** [dexie/Dexie.js#353]
I've been using Dixie for a while through idb-pull-blob-store and quite recently, with the last release, I started seeing this error:

```
OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing
```

It turns out that is due trying to open two Dixie instances on the same path, if I had a bit of randomness to the path, it solves my issue. Is there a way to avoid having to do this?

Thank you!

**Comment by dfahlander** [comment]
What you mean with randomness in the path. What path are we talking about?

**Comment by diasdavid** [comment]
Sorry, I meant that if I add some random number to the path and therefore, creating a different path, it works. Also, I'm using path/dbname interchangeably, my bad.

**Comment by dfahlander** [comment]
I see. It seems you've probably increased the number passed to db.version() without leaving a copy of the old version spec in the code. See [this guide](https://github.com/dfahlander/Dexie.js/wiki/Design#database-versioning) on how to do it. To get it back, anotate the revision in your source where you increased the version,  then copy the old version spec with the old schema and put it side by side with the new version and schema.
