### ISSUE TITLE
Possible repository move

### ISSUE THREAD

**Issue by dfahlander** [dexie/Dexie.js#592]
Hi! I am evaluating a move of Dexie.js from:

https://github.com/dfahlander/Dexie.js

to:

https://github.com/dexie/dexie

I think it deserves a more community-ish place to live in, rather than on my personal account. I am also evaluating to let this new organization be sponsored / backed via [opencollective](https://opencollective.com). That way we might have a chance to secure the future development efforts of the project by allowing sponsors / backers and payouts for some larger contributions or costs. [opencollective](https://opencollective.com) has been a successful choice for other open source projects, such as [webpack](https://github.com/webpack/webpack), [preact](https://github.com/developit/preact), etc.

Thoughts or comments?

**Comment by nponiros** [comment]
I don't know if moving the repository is worth the effort in the long run but I definitely like the opencollective idea. Dexie is a great library and I think it would benefit if you actually got paid for the time spent developing it.

Assuming that you will go ahead with opencollective then it is probably best to have Dexie be its own organisation. I'm assuming that it will be trickier to do the move after creating an opencollective account. Without opencollective then probably it is not worth the trouble to move the repo currently unless you see any big advantages for you as the owner in having Dexie in its own organisation vs. having it in your personal account.

In any case you can let me know if you need any help with moving and/or opencollective.

**Comment by dfahlander** [comment]
Thanks, @nponiros! Tried to move another repo before and was like a breeze, as it continued to work on the old location for existing clones 👍 . Also web pages linking to the old location should get redirected if I remember correctly. Will need to check that again.

I'll leave some time for more reactions / comments / questions and then maybe just go for it in a week or two unless we stumble on issues or tricky questions of some kind.

**Comment by nponiros** [comment]
I had one more look at the opencollective page and to create an open collective for an open source project "You'll need a GitHub account, a repository with over 100 stars that you own & at least 2 contributors.". This could be an issue if the stars/contributors are not transferred to the organization.

**Comment by dfahlander** [comment]
@nponiros Thanks for checking. However, according to [this link](https://help.github.com/articles/about-repository-transfers/#whats-transferred-with-a-repository), stars, contributors, history, webhooks, etc are transferred with the repository.

**Comment by roj1512** [comment]
Should this be closed?

**Comment by dfahlander** [comment]
yep, thanks
