### ISSUE TITLE
Dexie DB within a web worker

### ISSUE THREAD

**Issue by ballabusta** [dexie/Dexie.js#789]
First of all, thank you for this IDB wrapper, the API is rich and well documented.

I am having some issues with opening (with the purpose of writing) an existing dexie database from a web worker (same origin).
The goal is to fetch a significant amount of data (500k+) and then write in chunks to indexedDB. The fetch part works well in the worker, however, opening the existing database fails.
I have also tried to create a new database from the worker, and then initiated a db.tableName.bulkPut but that new database would not even be created (not visible in Chrome > devTools > Applications tab)

Here's what I am currently doing:

- In window context:

import Dexie from "dexie";
const db = new Dexie("myDB");
db.version(1).stores({
  table1: "++key, AColumnName1",
  table2: "++key, AColumnName2",
  table3: "AColumnName3"
});
export default db;

- in worker context:

const initialLength = scenarioPostProcess.length; // Getting the data in scenarioPostProcess
Dexie.getDatabaseNames().then((names) => {
      log(`Here are the names ${names}`);
 });
              
new Dexie("myDB").open().then((db) => {
while (scenarioPostProcess.length) {
const bulkPutPromise = db.table1.bulkPut(scenarioPostProcess.splice(0, Math.floor(initialLength * 0.15)));
bulkPutPromise.then((lastKeyInsertInDb) => {
if (lastKeyInsertInDb) {
	 log(`The last key inserted in table is ${lastKeyInsertInDb}`);
}
});
}                
}).catch((error) => {
    log(`Issue with database: ${error}`);
});
Using React with JS ES6, webpack with worker-loader
Dexie 2.0.4

Any ideas would be greatly appreciated.

**Comment by opavader** [comment]
Facing the same issue myself. working fine from main thread but not in worker.
I am using the worker-loader with webpack as well.

**Comment by dfahlander** [comment]
It's mostly better to declare the db instance in its own module and import the same module from both worker and web.

```js
// db.js
import Dexie from "dexie";

export const db = new Dexie("myDB");
db.version(1).stores({
  table1: "++key, AColumnName1",
  table2: "++key, AColumnName2",
  table3: "AColumnName3"
});
```

```js
// worker.js
import { db } from './db'; // You get a db with property table1 attached (because the schema is declared)

self.onmessage = event => {
  ...
  db.table1.bulkPut(...).then(lastId => {
    ...
  }).catch(error => {
    ...
  });
}
```

**Comment by opavader** [comment]
Thnx @dfahlander, the `db.table('someTable')` approach seems to work. 
Not sure what I am doing wrong here that table fields are not getting populated.


``` typescript
const LATEST_VERSION = 1;

class ArchDB extends Dexie {
    eois: Dexie.Table<LDefs.IEntryEOI, string>; 
    alerts: Dexie.Table<LDefs.IEntryAlerts, string>;

    constructor(dbSuffix: string) {
        super('ArchDB_' + dbSuffix);
        // using unique id strings to prevent duplicates
        this.version(LATEST_VERSION).stores({
            eois: '&id, updated, StartTime, EndTime', // Only want index by StartTime & EndTime as rest of the filtering is done in crossfilter
            alerts: '&id, updated, opentime, closetime, acktime',
        });
    }
}

export interface IDriver {
    db: ArchDB;
    ready: boolean;
}

const driver: IDriver = {
    db: null,
    ready: false,
};


export const initDriver = (domain: string) => {
    console.log('initializing local data store for : ' + domain);

    driver.db = new ArchDB(domain);

    driver.db.open().catch(function (err) {
        console.error('Failed to open db: ' + (err.stack || err));
    }).then(() => {
        driver.ready = true;
    });
};
```


I am checking `ready` to be true before accessing the table fields.

**Comment by slominskir** [comment]
It appears Firefox doesn't support import of modules in web workers, so the example above doesn't work in Firefox:  https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

**Comment by slominskir** [comment]
Also worth mentioning that a web worker appears to have a [separate module map](https://html.spec.whatwg.org/multipage/webappapis.html#:~:text=imported%20module%20scripts%20are%20only%20fetched%2C%20parsed%2C%20and%20evaluated%20once%20per%20Document%20or%20worker.) vs the main script.  The ES6 module will be executed twice if for example your web worker imports the `db.js` for writing to the IndexDB and your GUI running on the main script context imports `db.js` to read from IndexDB.   This can cause a [blocked](https://dexie.org/docs/Dexie/Dexie.on.blocked) situation if you're attempting to [manually drop the database](https://github.com/dexie/Dexie.js/issues/349) on version upgrades.

**Comment by dfahlander** [comment]
Closing this issue. Dexie is supported in both web workers, shared workers and service workers. This issue was about how to import it, which is more of an issue with web workers itself.

To anyone using dexie in a web worker, I recommend to declare the db instance in its own module and import the same module from both worker and web. They will of course be different instances though but at least the code can be declared in a single place. For this to work, you will need a bundler such as webpack, vite, rollupjs, esbuild etc. It can also be achieved using vanilla javascript but then you'll need to mark the worker with `{type: "module}`when creating it from your web code and you need to use native es modules from your web javascript as well and import it as so `import Dexie from './path-to/dexie.mjs'.

**Comment by parsagholipour** [comment]
You can try this library:
https://github.com/parsagholipour/dexie-worker
